### PR TITLE
Make findColumn case insensitive

### LINKED ISSUE #5432: 4.1.0 Use PgSql +Jpa  Error accessing table metadata
### Which version of ShardingSphere did you use?
4.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
startup success
### Actual behavior
startup failed

```
Caused by: org.hibernate.exception.GenericJDBCException: Error accessing table metadata
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.convertSQLException(InformationExtractorJdbcDatabaseMetaDataImpl.java:98)
	at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.getTables(InformationExtractorJdbcDatabaseMetaDataImpl.java:341)
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.getTablesInformation(DatabaseInformationImpl.java:120)
	at org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:65)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:207)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:114)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:183)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:310)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:939)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
	... 20 common frames omitted
Caused by: java.sql.SQLException: Can not find columnLabel TABLE_CAT
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.DatabaseMetaDataResultSet.findColumn(DatabaseMetaDataResultSet.java:304)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.DatabaseMetaDataResultSet.getString(DatabaseMetaDataResultSet.java:147)
	at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.extractTableName(InformationExtractorJdbcDatabaseMetaDataImpl.java:913)
	at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.extractTableInformation(InformationExtractorJdbcDatabaseMetaDataImpl.java:197)
	at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.processTableResults(InformationExtractorJdbcDatabaseMetaDataImpl.java:394)
	at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.getTables(InformationExtractorJdbcDatabaseMetaDataImpl.java:336)
	... 32 common frames omitted
```
### Reason analyze (If you can)

 4.1.0 println log startup failed

```
ShardingSphere-SQL - Logic SQL: select relname from pg_class where relkind='S'
ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@7d4069b0, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@73f9fc72), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@73f9fc72, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=13, distinctRow=false, projections=[ColumnProjection(owner=null, name=relname, alias=Optional.empty)]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@6a15ec76, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@6e38260f, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@10cbdf91, containsSubquery=false)
ShardingSphere-SQL - Actual SQL: db-default ::: select relname from pg_class where relkind='S'
o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: null
o.h.e.jdbc.spi.SqlExceptionHelper - Can not find columnLabel TABLE_CAT
o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.GenericJDBCException: Error accessing table metadata
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown initiated...
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown completed.
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown initiated...
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown completed.
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown initiated...
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown completed.
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown initiated...
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown completed.
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown initiated...
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown completed.
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown initiated...
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown completed.
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown initiated...
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown completed.
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown initiated...
 com.zaxxer.hikari.HikariDataSource - DatebookHikariCP - Shutdown completed.
```

But 4.0.1  startup success

```
ShardingSphere-SQL - Rule Type: sharding
ShardingSphere-SQL - Logic SQL: select relname from pg_class where relkind='S'
ShardingSphere-SQL - SQLStatement: SelectSQLStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@675f9bc6, tablesContext=TablesContext(tables=[Table(name=pg_class, alias=Optional.absent())], schema=Optional.absent())), projectionsContext=ProjectionsContext(startIndex=7, stopIndex=13, distinctRow=false, projections=[ColumnProjection(owner=null, name=relname, alias=Optional.absent())], columnLabels=[relname]), groupByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.groupby.GroupByContext@27b8daa1, orderByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.orderby.OrderByContext@b8df260, paginationContext=org.apache.shardingsphere.sql.parser.relation.segment.select.pagination.PaginationContext@4f1a6259, containsSubquery=false)
ShardingSphere-SQL - Actual SQL: db-default ::: select relname from pg_class where relkind='S'
o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
```

### PR DESCRIPTION
**Pull request by rfscouto**
Fixes #5432 

Changes proposed in this pull request:
- Convert HashMap to TreeMap (case insensitive) to handle cases where column name diverges only in upper/lower case;
- This implementation can, and should, be improved as necessity arises;
- Implemented minor test, can improve further upon recommendation

### CODE REVIEW

**Comment by tristaZero** [comment]
@rfscouto Thanks for your work on this legacy issue. @sandynz @strongduanmu could you review this PR? It's about #5432.

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java [hunk 1]
```diff
@@ -30,15 +30,7 @@
...
-import java.util.ArrayList;
-import java.util.Collection;
-import java.util.HashMap;
-import java.util.HashSet;
-import java.util.Iterator;
-import java.util.LinkedList;
-import java.util.List;
-import java.util.Map;
-import java.util.Optional;
+import java.util.*;
```
Comment (strongduanmu) [inline shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java:33]: @rfscouto Please do not use `*` to import.

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java [hunk 2]
```diff
@@ -358,10 +350,27 @@ public Object getObject(final String columnLabel) throws SQLException {
     @Override
     public int findColumn(final String columnLabel) throws SQLException {
         checkClosed();
-        if (!columnLabelIndexMap.containsKey(columnLabel)) {
-            throw new SQLException(String.format("Can not find columnLabel %s", columnLabel));
+
+        Integer columnIndex = columnLabelIndexMap.get(columnLabel);
```
Comment (strongduanmu) [inline shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java:354]: @rfscouto The implementation of this logic is a bit complicated. Can we consider using `Map<String, Integer> columnLabelIndexMap  = new TreeMap<>(String.CASE_INSENSITIVE_ORDER)` to solve this exception?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Comment by strongduanmu** [comment]
Thank you for your pr @rfscouto, I have left some comments, welcome to reply. BTW, Please fix the CI exception first.

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java (hunk 2 above)
Comment (rfscouto) [reply shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java]: That is completely fine by me. It is exactly what I had initial though about, but then read https://github.com/apache/shardingsphere/issues/5432 and thought we wanted to be aligned with the implementation of one of the big ones (and I made it aligned with PostgreSQL).
Converted to TreeMap.

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java (hunk 1 above)
Comment (rfscouto) [reply shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java]: Thanks! The validation was also failing for this :)

**Review by strongduanmu — APPROVED** [review]
@rfscouto Thank you for your effort, and look forward to seeing you participate in apache shardingsphere community.
