### PR TITLE
Fix issues 18689

### LINKED ISSUE #18689: Add test case for OptimizerContext.dropTable()

### PR DESCRIPTION
**Pull request by tain198127**
Fixes #18689.

Changes proposed in this pull request:
- Add test case for OptimizerContext.dropTable

image

### CODE REVIEW

File: shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/test/java/org/apache/shardingsphere/infra/federation/optimizer/context/OptimizerContextTest.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+        tables.put(tableName, mock(ShardingSphereTable.class, RETURNS_DEEP_STUBS));
+        ShardingSphereDatabase database = new ShardingSphereDatabase(databaseName, new H2DatabaseType(), mock(ShardingSphereResource.class), null,
+                Collections.singletonMap(schemaName, new ShardingSphereSchema(tables)));
+        OptimizerContext optimizerContext = OptimizerContextFactory.create(Collections.singletonMap(databaseName, database), mock(ShardingSphereRuleMetaData.class));
+        int converterHashCodeBefore = optimizerContext.getPlannerContexts().get(databaseName).getConverters().get(schemaName).hashCode();
+        int validatorHashCodeBefore = optimizerContext.getPlannerContexts().get(databaseName).getValidators().get(schemaName).hashCode();
+        optimizerContext.dropTable(databaseName, schemaName, tableName);
+        int converterHashCodeAfter = optimizerContext.getPlannerContexts().get(databaseName).getConverters().get(schemaName).hashCode();
+        int validatorHashCodeAfter = optimizerContext.getPlannerContexts().get(databaseName).getValidators().get(schemaName).hashCode();
+        assertNotEquals(converterHashCodeBefore, converterHashCodeAfter);
```
Comment (terrymanu) [inline shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/test/java/org/apache/shardingsphere/infra/federation/optimizer/context/OptimizerContextTest.java:56]: Please use assertThat for binary assertion

**Review by terrymanu — CHANGES_REQUESTED** [review]

File: shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/test/java/org/apache/shardingsphere/infra/federation/optimizer/context/OptimizerContextTest.java (hunk 1 above)
Comment (tain198127) [reply shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/test/java/org/apache/shardingsphere/infra/federation/optimizer/context/OptimizerContextTest.java]: Has been replace with assertThat

**Review by terrymanu — APPROVED** [review]
