### PR TITLE
 Exclude dual when validate if a table exist. (#26091)

### LINKED ISSUE #26091: When checking for the existence of a table, dual was not excluded.
### Which version of ShardingSphere did you use?
5.3.3-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
select 1 from dual

### Actual behavior
java.sql.SQLException: Table 'DUAL' doesn't exist

### PR DESCRIPTION
**Pull request by iamhucong**
Fixes #26091.

Changes proposed in this pull request:
  -  Exclude dual when validate if a table exist. 

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: infra/context/src/main/java/org/apache/shardingsphere/infra/connection/validator/ShardingSphereMetaDataValidateUtils.java [hunk 1]
```diff
@@ -25,13 +26,17 @@
...
+import java.util.List;
+
 /**
  * ShardingSphere meta data validate utility class.
  */
 // TODO consider add common ShardingSphereMetaDataValidateEngine for all features
 @NoArgsConstructor(access = AccessLevel.PRIVATE)
 public final class ShardingSphereMetaDataValidateUtils {
     
+    public static final List<String> EXCLUDE_VALIDATE_TABLE = Lists.newArrayList("DUAL");
```
Comment (strongduanmu) [inline infra/context/src/main/java/org/apache/shardingsphere/infra/connection/validator/ShardingSphereMetaDataValidateUtils.java:38]: Please use set to replace arraylist.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Review by strongduanmu — APPROVED** [review]
LGTM, merged.
