### PR TITLE
extend mppdb_decoding plugin support types: bit,timestamp,time,smalldate ,eltime etc

### LINKED ISSUE #12813: some openGauss  datatype can't  migrate in  scaling increment task
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy
### Expected behavior
1. date/text/varchar2/time/bit/bytea/raw type can normal migrate from 2pcs proxy two 3pcs proxy.
### Actual behavior
1. some convert format Exception reported in scaling increatemt task. 
### Reason analyze (If you can)
most error because  replication data in mppdb_decoding was in quote 'xx', but MppdbDecodingPlugin not dispose it.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. start scaling and proxy
2. create a scaling task, the task table contain the issue type
3. add increatement data, such as  date/text/varchar2/time/bit/bytea/raw type data
4. look at proxy log, we can get some convert Exception.
### Example codes for reproduce this issue (such as a github link).
see: [test code](https://gitee.com/justbk/jdbc_test/blob/master/src/test/java/ReplicationTest.java)   in testReplication function.

### PR DESCRIPTION
**Pull request by justbk2015**
…atetime,bytea, raw, money, interval and delete '' by default action

Fixes #12813.

Changes proposed in this pull request:
- repair bit 、datetime、time、bytea ' issue
- add new type raw/text/character/nvarchar2/interval/reltime/money/smalldatetime support and change default behaive to remote single quote ''
- add some testcase.

### CODE REVIEW

File: shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/wal/decode/MppdbDecodingPlugin.java [hunk 1]
```diff
@@ -158,28 +160,77 @@ private Object readColumnData(final String data, final String columnType) {
...
+    }
+    
+    private static PGobject decodeBytea(final String data) {
+        try {
+            PGobject pgObject = new PGobject();
+            pgObject.setType("bytea");
+            byte[] decodeByte = decodeHex(decodeString(data).substring(2));
+            pgObject.setValue(new String(decodeByte));
+            return pgObject;
+        } catch (SQLException ex) {
```
Comment (sandynz) [inline shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/wal/decode/MppdbDecodingPlugin.java:223]: Could be `final SQLException ignored`, and also other places.

File: shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/test/java/org/apache/shardingsphere/scaling/opengauss/wal/decode/MppdbDecodingPluginTest.java [hunk 2]
```diff
@@ -50,14 +55,18 @@ public void assertDecodeWriteRowEvent() {
         MppTableData tableData = new MppTableData();
         tableData.setTableName("public.test");
         tableData.setOpType("INSERT");
-        tableData.setColumnsName(new String[]{"data"});
-        tableData.setColumnsType(new String[]{"character varyint"});
-        tableData.setColumnsVal(new String[]{"1 2 3"});
+        String[] insertTypes = new String[]{"character varying", "text", "char", "character", "nchar", "varchar2", "nvarchar2", "clob"};
+
```
Comment (sandynz) [inline shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/test/java/org/apache/shardingsphere/scaling/opengauss/wal/decode/MppdbDecodingPluginTest.java:59]: Blank line could be removed, and also other places

**Review by sandynz — CHANGES_REQUESTED** [review]

**Review by sandynz — APPROVED** [review]
