### PR TITLE
make VERSION() support alias

### LINKED ISSUE #19187: VERSION() do not support alias
## Bug Report

like #17949 , i found the same problem in VERSION().

Please assign it to me, i will fix it asap.

### Which version of ShardingSphere did you use?

5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior
select VERSION() as vid;
get:
vid: 8.0.29

### Actual behavior

VERSION(): 8.0.29

### PR DESCRIPTION
**Pull request by csonezp**
Fixes #19187.

Changes proposed in this pull request:
- make VERSION() support alias

### CODE REVIEW

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/ShowVersionExecutor.java [hunk 1]
```diff
@@ -39,15 +43,31 @@ public final class ShowVersionExecutor implements DatabaseAdminQueryExecutor {
     
     public static final String FUNCTION_NAME = "version()";
     
+    private SelectStatement sqlStatement;
```
Comment (TeslaCN) [inline shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/ShowVersionExecutor.java:46]: Could we make it final and use `@RequiredArgsConstructor`.

Comment (csonezp) [reply shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/ShowVersionExecutor.java]: done

**Review by terrymanu — APPROVED** [review]
