### PR TITLE
fix issue-8551

### LINKED ISSUE #8551: Data Fragment Doesn't Work for Negative
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
<dependency>
  <groupId>org.apache.shardingsphere</groupId>
  <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
  <version>5.0.0-RC1-SNAPSHOT</version>
</dependency>

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Actual behavior
* it reports "no database route info" while the value of the field which is used to distinguish the database is negative.
* it send the sql text like this while the value of the field which is used to distinguish the table is negative.
```sql
INSERT INTO org.apache.shardingsphere.sharding.rewrite.token.pojo.TableToken@a0d875d  ( id,order_no,user_id )  VALUES  org.apache.shardingsphere.sharding.rewrite.token.pojo.ShardingInsertValuesToken@693f2c89
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
INSERT INTO t_order ( id, order_no, user_id ) VALUES ( 1, -1, -1 );
INSERT INTO t_order ( id, order_no, user_id ) VALUES ( 1, -1, 1 );

##### data fragment configuration
        database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: database-inline
            table-strategy:
              standard:
                sharding-column: order_no
                sharding-algorithm-name: t-order-inline
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{user_id % 2}
          t-order-inline:
            type: INLINE
            props:
              algorithm-expression: t_order_$->{order_no % 16}

### Example codes for reproduce this issue (such as a github link).
```java
Order order = new Order();
order.setId(1);
order.setUserId(-1234231);
order.setOrderNo(112312312L);
orderService.save(order);

Order order = new Order();
order.setId(1);
order.setUserId(1234231);
order.setOrderNo(-112312312L);
orderService.save(order);
```

### PR DESCRIPTION
**Pull request by jingshanglu**
Fixes #8551.

### CODE REVIEW

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java [hunk 1]
```diff
@@ -67,7 +68,11 @@ private boolean isAllowRangeQuery(final Properties props) {
     @Override
     public String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Comparable<?>> shardingValue) {
         Closure<?> closure = createClosure();
-        closure.setProperty(shardingValue.getColumnName(), shardingValue.getValue());
+        Comparable<?> value = shardingValue.getValue();
+        if (value instanceof Number) {
+            value = (Comparable<?>) NumberMath.abs((Number) value);
```
Comment (strongduanmu) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java:73]: Can we replace NumberMath.abs with Math.abs?

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/impl/InsertClauseShardingConditionEngine.java [hunk 2]
```diff
@@ -109,6 +112,15 @@ private ShardingCondition createShardingCondition(final String tableName, final
         return result;
     }
     
+    private void generateShardingCondition(final CommonExpressionSegment expressionSegment, final ShardingCondition result, final String shardingColumn, final String tableName) {
+        try {
+            Integer value = Integer.valueOf(expressionSegment.getText());
+            result.getValues().add(new ListShardingConditionValue<>(shardingColumn, tableName, Collections.singletonList(value)));
+        } catch (NumberFormatException exception) {
```
Comment (strongduanmu) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/impl/InsertClauseShardingConditionEngine.java:119]: Please rename exception to ex.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Review by strongduanmu — APPROVED** [review]
