### PR TITLE
fix capitalization issue on EncryptTable

### LINKED ISSUE #17171: Encryption does not work ，shardingsphere-jdbc 5.1.1
`````
spring:
  application:
    name: lite-sys-uaa
  messages:
    basename: com/hollysmart/sys/messages
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        file-extension: yml
        server-addr: ${spring.cloud.nacos.server-addr}

  shardingsphere:
    datasource:
      names: ds-0,ds-1,ds-2
      ds-0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://${hollysmart.datasource-common.ip}/lite_admin_service?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
        username: ${hollysmart.datasource-common.username}
        password: ${hollysmart.datasource-common.password}
      ds-1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://${hollysmart.datasource-common.ip}/lite_admin_service?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
        username: ${hollysmart.datasource-common.username}
        password: ${hollysmart.datasource-common.password}
      ds-2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://${hollysmart.datasource-common.ip}/lite_admin_service?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
        username: ${hollysmart.datasource-common.username}
        password: ${hollysmart.datasource-common.password}
    rules:
      dataSources:
        ds:
          writeDataSourceName: ds-0
          readDataSourceNames:
            - ds-1
            - ds-2
          loadBalancerName: roundRobin
      loadBalancers:
        roundRobin:
          type: ROUND_ROBIN
      sharding:
        tables:
          sys_user:
            actual-data-nodes: ds-0.sys_user_$->{0..2}
            databaseStrategy:
              standard:
                shardingColumn: USER_ID
                shardingAlgorithmName: sys-user-database-alg
            tableStrategy:
              standard:
                shardingColumn: USER_ID
                shardingAlgorithmName: sys-user-table-alg
          sys_user_mobile:
            actual-data-nodes: ds-0.sys_user_mobile_$->{0..2}
            databaseStrategy:
              standard:
                shardingColumn: MOBILE
                shardingAlgorithmName: sys-user-database-alg
            tableStrategy:
              standard:
                shardingColumn: MOBILE
                shardingAlgorithmName: sys-user-mobile-table-alg
          sys_user_username:
            actual-data-nodes: ds-0.sys_user_username_$->{0..2}
            databaseStrategy:
              standard:
                shardingColumn: USERNAME
                shardingAlgorithmName: sys-user-database-alg
            tableStrategy:
              standard:
                shardingColumn: USERNAME
                shardingAlgorithmName: sys-user-username-table-alg
          sys_user_oauth:
            actual-data-nodes: ds-0.sys_user_oauth_$->{0..2}
            databaseStrategy:
              standard:
                shardingColumn: OPEN_ID
                shardingAlgorithmName: sys-user-database-alg
            tableStrategy:
              standard:
                shardingColumn: OPEN_ID
                shardingAlgorithmName: sys-user-oauth-table-alg
        shardingAlgorithms:
          sys-user-database-alg:
            type: INLINE
            props:
              algorithm-expression: ds-0
          sys-user-table-alg:
            type: INLINE
            props:
              algorithm-expression: sys_user_$->{USER_ID % 3}
          sys-user-mobile-table-alg:
            type: INLINE
            props:
              algorithm-expression: sys_user_mobile_$->{Math.abs(MOBILE.hashCode())  % 3}
          sys-user-username-table-alg:
            type: INLINE
            props:
              algorithm-expression: sys_user_username_$->{Math.abs(USERNAME.hashCode())  % 3}
          sys-user-oauth-table-alg:
            type: INLINE
            props:
              algorithm-expression: sys_user_oauth_$->{Math.abs(OPEN_ID.hashCode())  % 3}
      encrypt:
        encryptors:
          aes_encryptor:
            type: AES
            props:
              aes-key-value: 123456abc
        tables:
          sys_user:
            columns:
              MOBILE:
                cipherColumn: MOBILE
                encryptorName: aes_encryptor
```


==>  Preparing: INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, FIRST_NAME, MOBILE, CREATED_BY, DATE_CREATED, DATE_UPDATED, UPDATED_BY, TENANT_SITE_ID, TENANT_STORE_ID, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ACCOUNT_NON_EXPIRED, ENABLED) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

==> Parameters: 191003(Long), ywy913(String), $2a$10$R/Snj4NU7JgRo4ijeGTCvejD2IJt2Nb1NaIxHmzchGKyfoMePUsVK(String), 杨(String), 13146541464(String), 0(Long), 2022-04-28 14:11:37.42(Timestamp), 2022-04-28 14:11:37.42(Timestamp), 0(Long), 846e0800-3ff9-48db-9d60-d13a37c95f1e(String), 999999(Long), true(Boolean), true(Boolean), true(Boolean), true(Boolean)
<==    Updates: 1

Why is the MOBILE not encrypted？

### PR DESCRIPTION
**Pull request by cheese8**
Fixes #17171.

Changes proposed in this pull request:
- adjust testcase
- convert tablename into lowercase at get put places

### CODE REVIEW

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java [hunk 1]
```diff
@@ -40,21 +40,21 @@
...
 import java.util.Optional;
+import java.util.TreeMap;
 
 /**
  * Encrypt rule.
  */
 public final class EncryptRule implements SchemaRule, TableContainedRule {
     
     @SuppressWarnings("rawtypes")
-    private final Map<String, EncryptAlgorithm> encryptors = new LinkedHashMap<>();
```
Comment (strongduanmu) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java:55]: @cheese8 Can we use toLowerCase for map key instead of TreeMap?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java (hunk 1 above)
Comment (cheese8) [reply shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java]: ok

File: shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/config/query-with-cipher.yaml [hunk 2]
```diff
@@ -22,7 +22,7 @@ dataSources:
 rules:
 - !ENCRYPT
   tables:
-    t_account:
+    T_account:
```
Comment (strongduanmu) [inline shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/config/query-with-cipher.yaml:25]: Can we keep the encrypt config and add some more test case for encrypt capitalization?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/config/query-with-cipher.yaml (hunk 2 above)
Comment (cheese8) [reply shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/config/query-with-cipher.yaml:25]: Hi, I just mixed this logic table name with upper and lower cases, to simulate that issue, for testcases.

Comment (cheese8) [reply shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/config/query-with-cipher.yaml]: OK, i got your mean.

**Review by strongduanmu — APPROVED** [review]
