### PR TITLE
NPE occurs when execute show table status

### LINKED ISSUE #32680: NPE occurs  when  execute show table status
### Which version of ShardingSphere did you use?
5.5.1-SNAPSHOT master e55969073952e82c9192f1876d48bec3dba511c6

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Actual behavior
- Client
```plain
mysql> show table status;
ERROR 30000 (HY000): Unknown exception.
More details: java.lang.NullPointerException: Cannot invoke "java.math.BigInteger.add(java.math.BigInteger)" because "num1" is null
mysql> 
```

- Proxy log
```plain
[INFO ] 2024-08-26 18:04:06.880 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: show table status
[INFO ] 2024-08-26 18:04:06.880 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_1 ::: show table status
[INFO ] 2024-08-26 18:04:06.880 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: show table status
[ERROR] 2024-08-26 18:04:07.089 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: Cannot invoke "java.math.BigInteger.add(java.math.BigInteger)" because "num1" is null
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.sum(ShowTableStatusMergedResult.java:77)
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.merge(ShowTableStatusMergedResult.java:68)
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.init(ShowTableStatusMergedResult.java:58)
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.init(ShowTableStatusMergedResult.java:39)
	at org.apache.shardingsphere.infra.merge.result.impl.memory.MemoryMergedResult.<init>(MemoryMergedResult.java:57)
	at org.apache.shardingsphere.sharding.merge.dal.show.ShowTableStatusMergedResult.<init>(ShowTableStatusMergedResult.java:43)
	at org.apache.shardingsphere.sharding.merge.dal.ShardingDALResultMerger.merge(ShardingDALResultMerger.java:71)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:88)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:78)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.mergeQuery(DatabaseConnector.java:320)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.processExecuteQuery(DatabaseConnector.java:290)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.doExecute(DatabaseConnector.java:251)
	at org.apache.shardingsphere.proxy.backend.connector.DatabaseConnector.execute(DatabaseConnector.java:199)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:86)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.doExecuteCommand(CommandExecutorTask.java:126)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:121)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
```

### PR DESCRIPTION
**Pull request by comecny**
Fixes #32680 .

Changes proposed in this pull request:

To safely handle cases where either object is null and avoid NPE during type conversion, you can add an early return check for null values and return 0 if either object is null. This approach ensures that your method won't attempt to perform operations on null objects, which would cause an NPE.

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTableStatusMergedResult.java [hunk 1]
```diff
@@ -74,10 +74,16 @@ private void merge(final MemoryQueryResultRow row, final MemoryQueryResultRow ne
     }
     
     private BigInteger sum(final Object num1, final Object num2) {
+        if (num1 == null || num2 == null){
+            return BigInteger.ZERO;
```
Comment (totalo) [inline features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTableStatusMergedResult.java:78]: Maybe it should return a non-null num instead of returning zero directly.

**Review by totalo — CHANGES_REQUESTED** [review]

**Comment by totalo** [comment]
And plz fix the ci.

File: features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTableStatusMergedResult.java (hunk 1 above)
Comment (comecny) [reply features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTableStatusMergedResult.java]: Uh... it should return null， I’ve already made the modification.

Comment (totalo) [reply features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTableStatusMergedResult.java]: Both are null, return null, one is not null, return the non-null one. Is it more appropriate?

**Comment by totalo** [comment]
hi @comecny, Thank you for your contribution, now ci hesitant code style problem fails, please fix first. See: https://shardingsphere.apache.org/community/en/involved/conduct/code/

File: features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTableStatusMergedResult.java (hunk 1 above)
Comment (comecny) [reply features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTableStatusMergedResult.java]: if the bug  is caused by the view , then is  wouldn't  be a case where on is null and then other is not . but ,it is indeed not elegant !   changed.

**Review by totalo — APPROVED** [review]
LGTM, Thanks.
