### PR TITLE
deal pg flush command in proxy, support node typeorm case

### LINKED ISSUE #25536: [pg]node typeorm got  feature_not_supported
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

proxy

### Expected behavior
using node typeorm  execute sql  success 

### Actual behavior
got  feature_not_supported error

### Reason analyze (If you can)
pg  when using node typeorm  ,  it'll  send  flush_command(H..S)  before execute sql;   but  proxy PostgreSQLCommandExecutorFactory not support this command

```java
private static CommandExecutor getCommandExecutor(final PostgreSQLCommandPacketType commandPacketType, final PostgreSQLCommandPacket commandPacket, final ConnectionSession connectionSession,
                                                      final PortalContext portalContext) throws SQLException {
        switch (commandPacketType) {
            case SIMPLE_QUERY:
                return new PostgreSQLComQueryExecutor(portalContext, (PostgreSQLComQueryPacket) commandPacket, connectionSession);
            case PARSE_COMMAND:
                return new PostgreSQLComParseExecutor((PostgreSQLComParsePacket) commandPacket, connectionSession);
            case BIND_COMMAND:
                return new PostgreSQLComBindExecutor(portalContext, (PostgreSQLComBindPacket) commandPacket, connectionSession);
            case DESCRIBE_COMMAND:
                return new PostgreSQLComDescribeExecutor(portalContext, (PostgreSQLComDescribePacket) commandPacket, connectionSession);
            case EXECUTE_COMMAND:
                return new PostgreSQLComExecuteExecutor(portalContext, (PostgreSQLComExecutePacket) commandPacket);
            case SYNC_COMMAND:
                return new PostgreSQLComSyncExecutor(connectionSession);
            case CLOSE_COMMAND:
                return new PostgreSQLComCloseExecutor(portalContext, (PostgreSQLComClosePacket) commandPacket, connectionSession);
            case TERMINATE:
                return new PostgreSQLComTerminationExecutor();
            default:
                return new PostgreSQLUnsupportedCommandExecutor();
        }
    }
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

use node typeorm to execute pg sql

### PR DESCRIPTION
**Pull request by susongyan**
Fixes #25536.

### CODE REVIEW

File: proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/flush/PostgreSQLComFlushExecutor.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+import org.apache.shardingsphere.proxy.frontend.command.executor.CommandExecutor;
+
+import java.sql.SQLException;
+import java.util.Collection;
+import java.util.Collections;
+
+/**
+ * Command flush executor for PostgreSQL.
+ **/
+public class PostgreSQLComFlushExecutor implements CommandExecutor {
```
Comment (TeslaCN) [inline proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/flush/PostgreSQLComFlushExecutor.java:30]:
```suggestion
public final class PostgreSQLComFlushExecutor implements CommandExecutor {
```

File: db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/flush/PostgreSQLComFlushPacket.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+import org.apache.shardingsphere.db.protocol.postgresql.packet.command.PostgreSQLCommandPacket;
+import org.apache.shardingsphere.db.protocol.postgresql.packet.command.PostgreSQLCommandPacketType;
+import org.apache.shardingsphere.db.protocol.postgresql.packet.identifier.PostgreSQLIdentifierTag;
+import org.apache.shardingsphere.db.protocol.postgresql.payload.PostgreSQLPacketPayload;
+
+/**
+ * Command flush packet for PostgreSQL.
+ **/
+public class PostgreSQLComFlushPacket extends PostgreSQLCommandPacket {
```
Comment (TeslaCN) [inline db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/flush/PostgreSQLComFlushPacket.java:28]:
```suggestion
public final class PostgreSQLComFlushPacket extends PostgreSQLCommandPacket {
```

**Review by TeslaCN — APPROVED** [review]
Thank you.
