### PR TITLE
Fix the error that the process does not exit after proxy startup fail

### LINKED ISSUE #32338: Start proxy multiple times, the process does not exit after the port is occupied
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

proxy

### Expected behavior
After the port is occupied, the process exits

### Actual behavior
```shell
  proxy ./bin/start.sh
/Users/jml/.jenv/shims/java
we find java version: java17, full_version=17.0.5, full_path=/Users/jml/.jenv/shims/java
The classpath is /Users/jml/Desktop/temp/open-proxy/proxy/conf:/Users/jml/Desktop/temp/open-proxy/proxy/conf:.:/Users/jml/Desktop/temp/open-proxy/proxy/lib/*:/Users/jml/Desktop/temp/open-proxy/proxy/ext-lib/*
main class org.apache.shardingsphere.proxy.Bootstrap -1 /Users/jml/Desktop/temp/open-proxy/proxy/conf 0.0.0.0 false
Starting the ShardingSphere-Proxy ...^[[A PID: 85899
Please check the STDOUT file: /Users/jml/Desktop/temp/open-proxy/proxy/logs/stdout.log
➜  proxy ./bin/start.sh
/Users/jml/.jenv/shims/java
we find java version: java17, full_version=17.0.5, full_path=/Users/jml/.jenv/shims/java
The classpath is /Users/jml/Desktop/temp/open-proxy/proxy/conf:/Users/jml/Desktop/temp/open-proxy/proxy/conf:.:/Users/jml/Desktop/temp/open-proxy/proxy/lib/*:/Users/jml/Desktop/temp/open-proxy/proxy/ext-lib/*
main class org.apache.shardingsphere.proxy.Bootstrap -1 /Users/jml/Desktop/temp/open-proxy/proxy/conf 0.0.0.0 false
Starting the ShardingSphere-Proxy ... PID: 86035
Please check the STDOUT file: /Users/jml/Desktop/temp/open-proxy/proxy/logs/stdout.log
➜  proxy ps -ef|grep shardingsphere
  501 85761     1   0  3:38下午 ttys002    0:04.14 java -Djava.awt.headless=true -server -Xmx2g -Xms2g -Xmn1g -Xss1m -XX:AutoBoxCacheMax=4096 -XX:+UseNUMA -XX:+DisableExplicitGC -XX:LargePageSizeInBytes=128m -XX:+SegmentedCodeCache -XX:+AggressiveHeap -Dio.netty.leakDetection.level=DISABLED -classpath /Users/jml/Desktop/temp/open-proxy/proxy/conf:/Users/jml/Desktop/temp/open-proxy/proxy/conf:.:/Users/jml/Desktop/temp/open-proxy/proxy/lib/*:/Users/jml/Desktop/temp/open-proxy/proxy/ext-lib/* org.apache.shardingsphere.proxy.Bootstrap -1 /Users/jml/Desktop/temp/open-proxy/proxy/conf 0.0.0.0 false
  501 85899     1   0  3:38下午 ttys002    0:03.25 java -Djava.awt.headless=true -server -Xmx2g -Xms2g -Xmn1g -Xss1m -XX:AutoBoxCacheMax=4096 -XX:+UseNUMA -XX:+DisableExplicitGC -XX:LargePageSizeInBytes=128m -XX:+SegmentedCodeCache -XX:+AggressiveHeap -Dio.netty.leakDetection.level=DISABLED -classpath /Users/jml/Desktop/temp/open-proxy/proxy/conf:/Users/jml/Desktop/temp/open-proxy/proxy/conf:.:/Users/jml/Desktop/temp/open-proxy/proxy/lib/*:/Users/jml/Desktop/temp/open-proxy/proxy/ext-lib/* org.apache.shardingsphere.proxy.Bootstrap -1 /Users/jml/Desktop/temp/open-proxy/proxy/conf 0.0.0.0 false
  501 86035     1   0  3:38下午 ttys002    0:03.34 java -Djava.awt.headless=true -server -Xmx2g -Xms2g -Xmn1g -Xss1m -XX:AutoBoxCacheMax=4096 -XX:+UseNUMA -XX:+DisableExplicitGC -XX:LargePageSizeInBytes=128m -XX:+SegmentedCodeCache -XX:+AggressiveHeap -Dio.netty.leakDetection.level=DISABLED -classpath /Users/jml/Desktop/temp/open-proxy/proxy/conf:/Users/jml/Desktop/temp/open-proxy/proxy/conf:.:/Users/jml/Desktop/temp/open-proxy/proxy/lib/*:/Users/jml/Desktop/temp/open-proxy/proxy/ext-lib/* org.apache.shardingsphere.proxy.Bootstrap -1 /Users/jml/Desktop/temp/open-proxy/proxy/conf 0.0.0.0 false
  501 86208 86517   0  3:38下午 ttys002    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox shardingsphere


```

### PR DESCRIPTION
**Pull request by jiangML**
Fixes #32338.

Changes proposed in this pull request:
  - Fix the error that the process does not exit after proxy startup fail

---

Before committing this PR, I'm sure that I have checked the following options:
- [ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Review by RaigorJiang — APPROVED** [review]

File: mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/event/subscriber/dispatch/ResourceMetaDataChangedSubscriber.java [hunk 1]
```diff
@@ -128,7 +129,9 @@ public synchronized void renew(final DropViewEvent event) {
     
     private void refreshShardingSphereStatisticsData() {
         PersistRepository repository = contextManager.getPersistServiceFacade().getRepository();
-        if (repository instanceof ClusterPersistRepository) {
+        if (contextManager.getComputeNodeInstanceContext().isCluster()
+                && InstanceType.PROXY == contextManager.getComputeNodeInstanceContext().getInstance().getMetaData().getType()
+                && repository instanceof ClusterPersistRepository) {
```
Comment (menghaoranss) [inline mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/event/subscriber/dispatch/ResourceMetaDataChangedSubscriber.java:134]: useless instanceof , if contextManager is cluster, the repository must be ClusterPersistRepository

File: proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java [hunk 2]
```diff
@@ -52,6 +54,7 @@ public static void main(final String[] args) throws IOException, SQLException {
         YamlProxyConfiguration yamlConfig = ProxyConfigurationLoader.load(bootstrapArgs.getConfigurationPath());
         int port = bootstrapArgs.getPort().orElseGet(() -> new ConfigurationProperties(yamlConfig.getServerConfiguration().getProps()).getValue(ConfigurationPropertyKey.PROXY_DEFAULT_PORT));
         List<String> addresses = bootstrapArgs.getAddresses();
+        checkPort(addresses, port);
```
Comment (menghaoranss) [inline proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:57]: this method only solved the issue of port, if other unknown exceptions have occurred at proxy.start(), the proxy will not exit, and the jobs or other resources will not be released

Comment (jiangML) [reply proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:57]: After closing the ejob that collects metadata, if an exception occurs after startup, the process will be exited.
