### PR TITLE
Fixed Refresh SingleTableRule tables.

### LINKED ISSUE #15191: Table changed not refresh SingleTableRule.
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior

Refresh SingleTableRule when table meta data changed.

### Actual behavior

No refresh.

image

### PR DESCRIPTION
**Pull request by zjcnb**
Fixes #15191

### CODE REVIEW

**Review by strongduanmu — APPROVED** [review]

File: shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java [hunk 1]
```diff
@@ -248,19 +250,27 @@ public void alterSchema(final String schemaName, final ShardingSphereSchema sche
      * @param deletedTable deleted table
      */
     public void alterSchema(final String schemaName, final TableMetaData changedTableMetaData, final String deletedTable) {
+        ShardingSphereMetaData metaData = metaDataContexts.getMetaData(schemaName);
+        if (!containsInDataNodeContainedRule(changedTableMetaData.getName(), metaData)) {
+            metaData.getRuleMetaData().findRules(MutableDataNodeRule.class).forEach(each -> each.put(changedTableMetaData.getName(), each.getDataSourceNames().iterator().next()));
```
Comment (tuichenchuxin) [inline shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java:255]: This datasource can't be iterator.next().
It need to be the actual one.

Comment (zjcnb) [reply shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java:255]: Ok, i will fixed it.
