### PR TITLE
proxy support parse pg json parameter in bind phase

### LINKED ISSUE #25838: proxy update pg json field failed
### Which version of ShardingSphere did you use?
5.3.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy 

### Expected behavior
update json field success 

### Actual behavior
org.postgresql.util.PSQLException: ERROR: column "xx" is of type json but expression is of type character varying

proxy seems to treat json as text in backend

### Reason analyze (If you can)
in "bind" phase,  actual  parameter is not parsed correctly 

 PostgreSQLComBindPacket#getTextParameters doesn't  deal  with PostgreSQLColumnType.POSTGRESQL_TYPE_JSON
image

expected parameter object(i tried to fix myself):      update success 
image

### PR DESCRIPTION
**Pull request by susongyan**
Fixes #25838.

### CODE REVIEW

File: db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextJsonUtils.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+     * @param textValue text value to be parsed
+     * @return json pgobject
+     * @throws SQLWrapperException thrown if value is invalid for json type
+     */
+    public static PGobject parse(final String textValue) {
+        try {
+            PGobject jsonObject = new PGobject();
+            jsonObject.setType("json");
+            jsonObject.setValue(textValue);
+            return jsonObject;
```
Comment (sandynz) [inline db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextJsonUtils.java:45]: `jsonObject` name could be `result`

File: db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextJsonUtils.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+public final class PostgreSQLTextJsonUtils {
+    
+    /**
+     * Parse json in PostgreSQL text format.
+     *
+     * @param textValue text value to be parsed
+     * @return json pgobject
+     * @throws SQLWrapperException thrown if value is invalid for json type
+     */
+    public static PGobject parse(final String textValue) {
```
Comment (sandynz) [inline db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextJsonUtils.java:40]: Could `textValue` name be imporved? Maybe `jsonText` is more readable

File: db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextJsonUtils.java [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+        try {
+            PGobject jsonObject = new PGobject();
+            jsonObject.setType("json");
+            jsonObject.setValue(textValue);
+            return jsonObject;
+        } catch (final SQLException e) {
```
Comment (sandynz) [inline db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextJsonUtils.java:46]: `e` should be `ex`

**Review by sandynz — CHANGES_REQUESTED** [review]

**Review by sandynz — APPROVED** [review]
