### PR TITLE
Fix the JDBCRepositorySQL fails to load when using a Fat Jar. (#25784)

### LINKED ISSUE #25784: Spring Boot(Fat jar) fails to start in stand-alone mode when using JDBC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

JDBC
### Expected behavior

success
### Actual behavior

image

### Reason analyze (If you can)

Unable to read the `H2.xml` file
Related PR: https://github.com/apache/shardingsphere/pull/25161

### PR DESCRIPTION
**Pull request by iamhucong**
Fixes #25784.

Changes proposed in this pull request:
  - Fix the JDBCRepositorySQL fails to load when using a Fat Jar. 

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by iamhucong** [comment]
@zhaojinchao95  Hi, could you help me review this when you have time?

File: mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java [hunk 1]
```diff
@@ -57,49 +67,54 @@ public final class JDBCRepositorySQLLoader {
...
         }
+        JDBCRepositorySQL jdbcRepositorySQL = null;
+        while (resources.hasMoreElements()) {
+            URL resource = resources.nextElement();
+            jdbcRepositorySQL = isJarURL(resource) ? loadFromJar(resource, type) : loadFromDirectory(resource, type);
+            if (null != jdbcRepositorySQL && Objects.equals(jdbcRepositorySQL.isDefault(), false)) {
+                break;
+            }
+        }
+        return jdbcRepositorySQL;
```
Comment (zhaojinchao95) [inline mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java:82]: Please change `jdbcRepositorySQL`  to `result`.

**Review by zhaojinchao95 — APPROVED** [review]
