### PR TITLE
Fix #19224

### LINKED ISSUE #19224: Use DistSQL add resource have unexpected behavior
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

`e6328cb989cfb789189227892cb892740095d2d6`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
add resource have error .so `show database resources` should't have result
### Actual behavior
add resource have error . excute `show database resources` have result
image

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. use server.yaml start proxy
server.yaml
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: 0715distsql
      server-lists: 192.168.10.21:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
- !AUTHORITY
  users:
    - root@%:root
    - sharding@:sharding
  provider:
    type: ALL_PERMITTED
- !SQL_PARSER
  sqlCommentParseEnabled: true
  sqlStatementCache:
    initialCapacity: 2000
    maximumSize: 65535
  parseTreeCache:
    initialCapacity: 128
    maximumSize: 1024

props:
  proxy-frontend-database-protocol-type: "PostgreSQL"
```
2. psql -U root  -h 127.0.0.1 -p 3333(proxy  port) -d postgres
3. execute sql
```
ADD RESOURCE resource_0 (
 URL="jdbc:postgresql://192.168.10.21:5432/postgres",
 USER=gaussdb,
 PASSWORD=passwd
);
```
```
show database resources;
```

### PR DESCRIPTION
**Pull request by jingshanglu**
Fixes #19224 .

### CODE REVIEW

File: shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidator.java [hunk 1]
```diff
@@ -69,7 +71,9 @@ private void validate(final String dataSourceName, final DataSourceProperties da
         }
     }
     
-    private void checkFailFast(final DataSource dataSource) throws SQLException {
-        dataSource.getConnection();
+    private void checkFailFast(final DataSource dataSource, final DatabaseType databaseType) throws SQLException {
+        if (!dataSource.getConnection().getMetaData().getDatabaseProductName().equals(databaseType.getType())) {
+            throw new SQLException("Protocol mismatch for datasource.");
```
Comment (terrymanu) [inline shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidator.java:76]: data source are 2 words, please split them

**Review by terrymanu — CHANGES_REQUESTED** [review]

**Review by terrymanu — CHANGES_REQUESTED** [review]
Please add test case for the added logic

File: shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidatorTest.java [hunk 2]
```diff
@@ -29,7 +31,12 @@ public final class DataSourcePropertiesValidatorTest {
     
     @Test
     public void assertValidateSuccess() throws InvalidResourcesException {
-        new DataSourcePropertiesValidator().validate(Collections.singletonMap("name", new DataSourceProperties(HikariDataSource.class.getName(), createValidProperties())));
+        new DataSourcePropertiesValidator().validate(Collections.singletonMap("name", new DataSourceProperties(HikariDataSource.class.getName(), createValidProperties())), new H2DatabaseType());
+    }
+    
+    @Test(expected = InvalidResourcesException.class)
+    public void assertDatabaseTypeInValidateFail() throws InvalidResourcesException {
+        new DataSourcePropertiesValidator().validate(Collections.singletonMap("name", new DataSourceProperties(HikariDataSource.class.getName(), createValidProperties())), new MySQLDatabaseType());
```
Comment (jingshanglu) [inline shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidatorTest.java:39]: This is UT about the logic.

**Review by terrymanu — APPROVED** [review]
