### PR TITLE
MySQLNormalReplicationDatabaseDiscovery support min-enabled-replicas

### LINKED ISSUE #18380: DatabaseDiscovery keeps at least some replicas
### Describe the feature you would like.
If all replicas are disabled, using RandomReplicaLoadBalanceAlgorithm will throw an exception. I want to define a parameter 'min-enabled-replicas-threshold' in props of discoveryTypes, which means that at least a few replicas cannot be disabled. And the specific processing logic will be placed in the method 'updateStatus' of the class DatabaseDiscoveryRule.

### PR DESCRIPTION
**Pull request by natehuangting**
Fixes #18380 .

Changes proposed in this pull request:
- MySQLNormalReplicationDatabaseDiscovery support min-enabled-replicas

### CODE REVIEW

File: shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-core/src/main/java/org/apache/shardingsphere/dbdiscovery/algorithm/DatabaseDiscoveryEngine.java [hunk 1]
```diff
@@ -97,11 +98,26 @@ private Map<String, DataSource> getActiveDataSourceMap(final Map<String, DataSou
...
             if (!entry.getKey().equals(primaryDataSourceName)) {
-                ShardingSphereEventBus.getInstance().post(new DataSourceDisabledEvent(databaseName, groupName, entry.getKey(), createStorageNodeDataSource(loadReplicaStatus(entry.getValue()))));
+                StorageNodeDataSource storageNodeDataSource = createStorageNodeDataSource(loadReplicaStatus(entry.getValue()));
+
+                if (StorageNodeStatus.isEnable(storageNodeDataSource.getStatus())) {
+                    enabledReplicasCount += disabledDataSourceNames.contains(entry.getKey()) ? 1 : 0;
+                    ShardingSphereEventBus.getInstance().post(new DataSourceDisabledEvent(databaseName, groupName, entry.getKey(), storageNodeDataSource));
+                    continue;
+                }
+
```
Comment (zjcnb) [inline shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-core/src/main/java/org/apache/shardingsphere/dbdiscovery/algorithm/DatabaseDiscoveryEngine.java:115]: Please remove extra blank line

**Review by zjcnb — APPROVED** [review]
