### PR TITLE
Make sure ShardingSphereDriver can load configuration file from classpath with mutiple ClassLoaders

### LINKED ISSUE #22658: ShardingSphereDriver can not load the yaml file from the classpath in the multiple classloaders
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
It can load the yaml file from the classpath

### Actual behavior
file not found

### Reason analyze (If you can)
It seems that [ShardingSphereDriverURL](https://github.com/apache/shardingsphere/blob/master/jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java#L62) uses `ShardingSphereDriverURL.class.getResourceAsStream` and this does not work in the multiple classloaders, such as Quarkus framework.

It should try to load with `Thread.currentThread().getContextClassLoader()` or `ClassLoader.getSystemClassLoader()`

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
see https://github.com/quarkiverse/quarkus-shardingsphere-jdbc/issues/74

### Example codes for reproduce this issue (such as a github link).
see https://github.com/quarkiverse/quarkus-shardingsphere-jdbc/issues/74

### PR DESCRIPTION
**Pull request by zhfeng**
fromclasspath with mutiple ClassLoaders

Fixes #22658
Changes proposed in this pull request:
  - Add `getResourceAsStream` to load configuration file from classpath by using mutiple ClassLoaders which could be helpful to fix https://github.com/quarkiverse/quarkus-shardingsphere-jdbc/issues/74

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java [hunk 1]
```diff
@@ -72,4 +72,30 @@ public byte[] toConfigurationBytes() {
             return builder.toString().getBytes(StandardCharsets.UTF_8);
         }
     }
+    
+    private InputStream getResourceAsStream(final String resource) throws IOException {
+        ClassLoader[] classLoader = new ClassLoader[]{
+                Thread.currentThread().getContextClassLoader(),
+                getClass().getClassLoader(),
+                ClassLoader.getSystemClassLoader(),
+        };
```
Comment (sandynz) [inline jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:81]: It's better to put them in one line for shorter code

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java [hunk 2]
```diff
@@ -72,4 +72,30 @@ public byte[] toConfigurationBytes() {
...
+            if (null != cl) {
+                
+                // try to find the resource as passed
+                InputStream returnValue = cl.getResourceAsStream(resource);
+                
+                // now, some class loaders want this leading "/", so we'll add it and try again if we didn't find the resource
+                if (null == returnValue) {
+                    returnValue = cl.getResourceAsStream("/" + resource);
+                }
+
```
Comment (sandynz) [inline jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:93]: Empty lines in method could be removed

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java [hunk 3]
```diff
@@ -72,4 +72,30 @@ public byte[] toConfigurationBytes() {
...
     }
+    
+    private InputStream getResourceAsStream(final String resource) throws IOException {
+        ClassLoader[] classLoader = new ClassLoader[]{
+                Thread.currentThread().getContextClassLoader(),
+                getClass().getClassLoader(),
+                ClassLoader.getSystemClassLoader(),
+        };
+        
+        for (ClassLoader cl : classLoader) {
```
Comment (sandynz) [inline jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:83]: Variable name `cl` should be `each`

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java (hunk 1 above)
Comment (sandynz) [reply jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:81]: `classLoader` could be `classLoaders`

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java [hunk 4]
```diff
@@ -72,4 +72,30 @@ public byte[] toConfigurationBytes() {
...
+            if (null != cl) {
+                
+                // try to find the resource as passed
```
Comment (sandynz) [inline jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:86]: Comments in method could be removed

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java [hunk 5]
```diff
@@ -72,4 +72,30 @@ public byte[] toConfigurationBytes() {
...
+                InputStream returnValue = cl.getResourceAsStream(resource);
```
Comment (sandynz) [inline jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:87]: `returnValue` should be `result`

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java [hunk 6]
```diff
@@ -72,4 +72,30 @@ public byte[] toConfigurationBytes() {
...
+                
+                // now, some class loaders want this leading "/", so we'll add it and try again if we didn't find the resource
+                if (null == returnValue) {
+                    returnValue = cl.getResourceAsStream("/" + resource);
+                }
```
Comment (sandynz) [inline jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:92]: Did you test which class loader need '/'?
If the most frequent used one need '/', could we try to load with '/' firstly?

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java (hunk 1 above)
Comment (sandynz) [reply jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:81]: Did you test which class loader satisify most cases or the most common case?

Could we put `getClass().getClassLoader()` at first?

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java (hunk 6 above)
Comment (zhfeng) [reply jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:92]: `getClass().getClassLoader()` needs `/`

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java [hunk 7]
```diff
@@ -72,4 +72,22 @@ public byte[] toConfigurationBytes() {
...
+    private InputStream getResourceAsStream(final String resource) throws IOException {
+        ClassLoader[] classLoaders = new ClassLoader[]{
+                Thread.currentThread().getContextClassLoader(), getClass().getClassLoader(), ClassLoader.getSystemClassLoader(),
+        };
+        for (ClassLoader each : classLoaders) {
+            if (null != each) {
+                InputStream result = each.getResourceAsStream(resource);
+                if (null == result) {
+                    result = each.getResourceAsStream("/" + resource);
+                }
```
Comment (sandynz) [inline jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:85]: Could we bind resource path with class loader? Maybe it's more efficient and readable.
e.g. `TCCL` just use `resource`, `getClass().getClassLoader()` just use `"/" + resource`

Comment (sandynz) [reply jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:85]: 1, Could we remove the last `,` after `ClassLoader.getSystemClassLoader()`?

2, And did you try to run `mvn spotless:apply` in this module? Seems it might change the code formatting.

**Review by sandynz — CHANGES_REQUESTED** [review]

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java (hunk 7 above)
Comment (zhfeng) [reply jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:85]: I added  `,` in the arrays due to the checkstyle failures
```
[ERROR] src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:[79] (coding) ArrayTrailingComma: 数组尾元素后应有逗号','。
```
So it need to change the `checkstyle.xml` to remove `<module name="ArrayTrailingComma" />` ?

yeah, I run `mvn splotless:apply` and it looks good.

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java (hunk 6 above)
Comment (zhfeng) [reply jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java]: sorry, I think it is not correctly. It looks like when using `getClass().getClassLoader()`, it always uses the relative path. But if there is a custom classloader, it could need the leading of `/`.  Perhaps in case of some application containers, such as `Tomcat`

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java (hunk 7 above)
Comment (zhfeng) [reply jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:85]: And I think we can not bind `/` with class loader.  See my above explaination.

Comment (zhfeng) [reply jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java:85]: IIRC all `ClassLoader` uses relative path to load the resources. But in some case of custom classloader, it might need the leading of `/`. So it makes sense to try `resource` at first and if it fails, try `"/" + resource`.

File: jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java (hunk 1 above)
Comment (sandynz) [reply jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java]: OK

**Review by sandynz — APPROVED** [review]
