### PR TITLE
Fix issue 14175 resultSet.getBoolean() throw ClassCastException

### LINKED ISSUE #14175: sharding+group by+mysql8.x+execute()  ClassCastException
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC 
### Expected behavior
exeucte success
### Actual behavior
Exception in thread "main" java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.sql.Timestamp
### Reason analyze (If you can)
org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#execute() use inner class
image
image
but org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#executeQuery0 use PreparedStatementExecuteQueryCallback
image
if need merge PreparedStatementExecuteQueryCallback handle type use db type
inner class use getObject, in mysql driver 8.x DateTime return LocalDateTime
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Preparation phase
* mysql connector driver 8.x
* sql has group by
* table sharding or db sharding
2. Execute phase
* call org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#execute()
* call org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet#getTimestamp(java.lang.String)
### Example codes for reproduce this issue (such as a github link).
https://github.com/SirMin/shardingsphere5.x-demo

### PR DESCRIPTION
**Pull request by challengeof**
Fixes #14175 

Fixed the result of a grouped query of type varchar in the database is called resultSet.getBoolean() throw ClassCastException

The time zone problem in the issue does not exist, because the underlying implementation is jdbc driver, so to adjust the time zone, please use serverTimezone=UTC in jdbcUrl

Bug fixes refer to the jdbc driver implementation

### CODE REVIEW

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ResultSetUtil.java [hunk 1]
```diff
@@ -169,7 +172,7 @@ private static Object convertNumberValue(final Object value, final Class<?> conv
         Number number = (Number) value;
         switch (convertType.getName()) {
             case "boolean":
-                return 0 != number.longValue();
+                return longToBoolean(number.longValue());
```
Comment (strongduanmu) [inline shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ResultSetUtil.java:175]: @challengeof Why change this logic?

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ResultSetUtil.java [hunk 2]
```diff
@@ -224,4 +227,22 @@ private static Object convertByteArrayValue(final Object value, final Class<?> c
...
     }
+
+    private static Object convertBooleanValue(final Object value) {
+        if (value instanceof Boolean) {
+            return value;
+        }
+        String stringVal = value.toString();
+        if (stringVal.length() > 0) {
+            int c = Character.toLowerCase(stringVal.charAt(0));
+            return c == 't' || c == 'y' || c == '1' || "-1".equals(stringVal);
```
Comment (strongduanmu) [inline shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ResultSetUtil.java:238]: @challengeof Can we rename `c` to `firstChar`? And put constant on the left condition?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @challengeof, please take a look at review suggestions first.

File: shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-core/src/main/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryRule.java [hunk 3]
```diff
@@ -190,7 +190,7 @@ private void initHeartBeatJobs(final String schemaName, final Map<String, DataSo
         Optional<ModeScheduleContext> modeScheduleContext = ModeScheduleContextFactory.getInstance().get();
         if (modeScheduleContext.isPresent()) {
             for (Entry<String, DatabaseDiscoveryDataSourceRule> entry : dataSourceRules.entrySet()) {
-                Map<String, DataSource> dataSources = dataSourceMap.entrySet().stream().filter(dataSource -> entry.getValue().getDisabledDataSourceNames().contains(dataSource.getKey()))
+                Map<String, DataSource> dataSources = dataSourceMap.entrySet().stream().filter(dataSource -> !entry.getValue().getDisabledDataSourceNames().contains(dataSource.getKey()))
```
Comment (strongduanmu) [inline shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-core/src/main/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryRule.java:193]: Hi @challengeof, please don't modify DatabaseDiscoveryRule class in this pr.

File: shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java [hunk 4]
```diff
@@ -93,6 +92,7 @@ private void beforeBuildContextManager(final ModeConfiguration modeConfig, final
                                            final Properties props, final boolean isOverwrite, final Integer port, final String schemaName) throws SQLException {
         ClusterPersistRepository repository = createClusterPersistRepository((ClusterPersistRepositoryConfiguration) modeConfig.getRepository());
         registryCenter = new RegistryCenter(repository, port);
+        ModeScheduleContextFactory.getInstance().init(modeConfig);
```
Comment (strongduanmu) [inline shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java:95]: Same problem, please don't modify this file in this pr.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Comment by strongduanmu** [comment]
@

**Review by strongduanmu — APPROVED** [review]
