### PR TITLE
Fixes #15083, support more types in `getObject` method.

### LINKED ISSUE #15083: Cannot get result set with enum , shardingsphere and mybatis-plus conflict
```xml
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.0.0</version>
</dependency>

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.5.0</version>
</dependency>
```

```yml
# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-column-underline: true
      refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-enums-package: com.sanyicloud.**.enums

```

```java
@Data
class Device{
    @TableField(value = "device_type")
    private DeviceTypeEnum deviceType;
}

@Getter
@AllArgsConstructor
 enum DeviceTypeEnum implements IEnum<Short>{
    IOS((short) 1, "ios"),
    ANDROID((short) 2,"android"),
    OTHER((short) 3, "other"),;
    @EnumValue
    private final Short code;
    @JsonValue
    private final String desc;
    @Override
    public Short getValue() {
        return this.code;
    }
}
```
The above configuration can successfully insert data, but the data cannot be queried。

exception
```text
2022-01-26 14:08:52.064  INFO [account-service,,] 95936 --- [           main] ShardingSphere-SQL                       : Actual SQL: master ::: SELECT  id,account_id,device_num,device_type,create_time,update_time,promo_code  FROM sanyi_third_0

org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'device_type' from result set.  Cause: java.sql.SQLFeatureNotSupportedException: getObject with type
; getObject with type; nested exception is java.sql.SQLFeatureNotSupportedException: getObject with type

Caused by: java.sql.SQLFeatureNotSupportedException: getObject with type
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.getObject(ShardingSphereResultSet.java:373)
	at org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.getObject(ShardingSphereResultSet.java:378)
	at com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler.getNullableResult(MybatisEnumTypeHandler.java:118)
	at com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler.getNullableResult(MybatisEnumTypeHandler.java:49)
```

Underlying code
```java
ShardingSphereResultSet.class

    @Override
    public <T> T getObject(final int columnIndex, final Class<T> type) throws SQLException {
// columnIndex == 4 type == Short.class
        if (LocalDateTime.class.equals(type) || LocalDate.class.equals(type) || LocalTime.class.equals(type)) {
            return (T) ResultSetUtil.convertValue(mergeResultSet.getValue(columnIndex, Timestamp.class), type);
        }
        throw new SQLFeatureNotSupportedException("getObject with type");
    }
```
code
```java
@Test
public void test(){
    List<Device> list = thirdService.list();
}

```

How can I continue to use enumeration class object parameters

### PR DESCRIPTION
**Pull request by RaigorJiang**
Fixes #15083.

### MySQL
- mysql-connector-java:8.0
https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/result/ResultSetImpl.java

- mysql-connector-java:5.1
https://github.com/mysql/mysql-connector-j/blob/release/5.1/src/com/mysql/jdbc/ResultSetImpl.java

### Postgres
https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java

### CODE REVIEW

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSet.java [hunk 1]
```diff
@@ -367,8 +369,47 @@ public Object getObject(final String columnLabel) throws SQLException {
     @SuppressWarnings("unchecked")
     @Override
     public <T> T getObject(final int columnIndex, final Class<T> type) throws SQLException {
-        if (LocalDateTime.class.equals(type) || LocalDate.class.equals(type) || LocalTime.class.equals(type)) {
+        if (null == type) {
+            throw new SQLException("Type cannot be null");
+        }
+        if (String.class.equals(type)) {
```
Comment (strongduanmu) [inline shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSet.java:375]: @RaigorJiang Can we move this logic to ResultSetUtil#convertValue, it seems to be the utility class responsible for type conversion.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Review by strongduanmu — APPROVED** [review]
Thank you @RaigorJiang.

**Comment by RaigorJiang** [comment]
@strongduanmu 
Thanks for your review 🤠
