### PR TITLE
authority type DATABASE_PERMITTED not apply correctly for some account when there are multi accounts #21615

### LINKED ISSUE #21615: authority type DATABASE_PERMITTED not apply correctly for some account when there are multi accounts
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
v5.2.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
use authority type DATABASE_PERMITTED in ShardingSphere-Proxy 5.2.0, 
config two accounts  testacc_a，testacc_b
config account testacc_a to access logic db testdb_a,
 account testacc_b to access logic db testdb_b
expected that both two accounts can access ShardingSphere Proxy via mysql ui tools eg. workbench or navicat

### Actual behavior
only account testacc_a  access ShardingSphere Proxy via mysql ui tool successfully, 
the other account testacc_b  failed to access ShardingSphere Proxy via mysql ui tool

### Reason analyze (If you can)

when connect with account testacc_a, the sql only query logic db testdb_a

but when connect with account testacc_b , there would be one or more sql that would query  logic db testdb_a,
as testacc_b is configed to access logic db testdb_b, it cannot found db testdb_a
accss testdb_a will cause the unknow database error like below

in ShardingSphere Proxy log, connect use  testacc_b, error log like below:

in sharding proxy version 5.1, config use SCHEMA_PRIVILEGES_PERMITTED has no this issue

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

config rules in file server.yaml

rules:
  - !AUTHORITY
    users:
      - testacc_a@:123456
      - testacc_b@:123456
    provider:
      type: DATABASE_PERMITTED
      props:
        user-database-mappings: testacc_a@=testdb_a,testacc_b@=testdb_b

add config file config-sharding.yaml and config-testdb_a.yaml, 

config-testdb_a.yaml：
databaseName: testdb_a

config-testdb_a.yaml:
databaseName: testdb_b

add dataSources for the two files, the dataSources can be the same or different

### PR DESCRIPTION
**Pull request by wallacezhou**
Fixes #21615.

Changes proposed in this pull request:
  - choose only the privileges databases when a connect to proxy from a client tool

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `mvn clean install -B -T2C -DskipTests -Dmaven.javadoc.skip=true -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/data/impl/UnicastDatabaseBackendHandler.java [hunk 1]
```diff
@@ -84,7 +86,12 @@ private String getFirstDatabaseName() {
         if (databaseNames.isEmpty()) {
             throw new NoDatabaseSelectedException();
         }
-        Optional<String> result = databaseNames.stream().filter(each -> ProxyContext.getInstance().getDatabase(each).containsDataSource()).findFirst();
+        AuthorityRule authorityRule = ProxyContext.getInstance().getContextManager().getMetaDataContexts().getMetaData().getGlobalRuleMetaData().getSingleRule(
+                AuthorityRule.class);
+        Optional<ShardingSpherePrivileges> privileges = authorityRule.findPrivileges(connectionSession.getGrantee());
+        Optional<String> result = privileges.isPresent() ? databaseNames.stream().filter(each -> privileges.get().hasPrivileges(each)
```
Comment (RaigorJiang) [inline proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/data/impl/UnicastDatabaseBackendHandler.java:92]: Hi @wallacezhou ,
Welcome, your PR provides a working solution, but please don't do complicated logical operations in the ternary operator, can you extract the judgment condition as a variable?

Comment (wallacezhou) [reply proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/data/impl/UnicastDatabaseBackendHandler.java]: updated , please help to review it

**Comment by RaigorJiang** [comment]
@wallacezhou 
Thank you!
In this operation, stream is used more than before, which may bring performance problems, I will do some tests.

**Review by RaigorJiang — APPROVED** [review]
