### PR TITLE
fix issue 6909

### LINKED ISSUE #6909: Add more test cases for ShardingSpringNamespaceTest
Please finished todo in ShardingSpringNamespaceTest

- [ ] assertModStrategy
- [ ] assertComplexStrategy
- [ ] assertHintStrategy
- [ ] assertIncrementAlgorithm
- [ ] assertDefaultKeyGenerator
- [ ] assertOrderKeyGenerator
- [ ] assertSimpleRule
- [ ] assertComplexRule
- [ ] assertBindingRule
- [ ] assertBroadcastRule
- [ ] assertAutoRule

### PR DESCRIPTION
**Pull request by jacksparrow414**
Fixes #6909 .

Changes proposed in this pull request:
- Add more test cases for ShardingSpringNamespaceTest
- assertSimpleRule
- assertComplexRule
- assertBindingRule
- assertBroadcastRule
- assertAutoRule

### CODE REVIEW

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java [hunk 1]
```diff
@@ -163,26 +185,70 @@ public void assertOrderKeyGenerator() {
...
-        // TODO
+        Collection<ShardingTableRuleConfiguration> actualBroadcastTableConfigurations = broadcastRule.getTables();
+        assertFalse(actualBroadcastTableConfigurations.isEmpty());
+        assertThat(actualBroadcastTableConfigurations.size(), is(2));
+        Iterator<ShardingTableRuleConfiguration> actualIterator = actualBroadcastTableConfigurations.iterator();
+        assertThat(actualIterator.next().getLogicTable(), is("t_order"));
+        assertThat(actualIterator.next().getLogicTable(), is("t_order_item"));
+        Collection<String> broadcastTables = broadcastRule.getBroadcastTables();
+        assertFalse(broadcastTables.isEmpty());
+        assertThat(broadcastTables.size(), is(2));
```
Comment (terrymanu) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java:236]: It is unnecessary for assert both `broadcastTables.isEmpty()` and assert `size is 2`

**Review by terrymanu — CHANGES_REQUESTED** [review]

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java (hunk 1 above)
Comment (jacksparrow414) [reply shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java]: fixed

**Review by terrymanu — APPROVED** [review]
