### PR TITLE
For #12449: If a scaling job failed or stopped then it could not be started by DistSQL except restarting proxy

### LINKED ISSUE #12449: If a scaling job failed or stopped then it could not be started by DistSQL except restarting proxy
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Scaling, commit: 46aeeff1b2e837fe514df3097e4945057b911e7a

### Expected behavior
Job could be stopped when exception occur.

### Actual behavior
It need to stop job manually, else it couldn't be started again.

### Reason analyze (If you can)
In `ScalingJobExecutor.java`
```
    private void execute(final JobConfigurationPOJO jobConfigPOJO) {
        if (EXECUTING_JOBS.add(jobConfigPOJO.getJobName())) {
            new OneOffJobBootstrap(ScalingAPIFactory.getRegistryCenter(), new ScalingJob(), jobConfigPOJO.toJobConfiguration()).execute();
        }
    }
```
job name is still cached in `EXECUTING_JOBS`, since job is not stopped automatically.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Submit wrong srouce/target parameter in HTTP api `/scaling/job/start`.

### PR DESCRIPTION
**Pull request by ReyYang**
Fixes #12449.

Changes proposed in this pull request:
- Provides stopJob methods for RuleAlteredJob to use

### CODE REVIEW

File: shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/PipelineJobExecutor.java [hunk 1]
```diff
@@ -105,6 +103,16 @@ private void execute(final JobConfigurationPOJO jobConfigPOJO) {
...
     
+    /**
+     * stop job.
+     * @param jobId job id
+     */
+    public void stopJob(final String jobId) {
+        log.info("remove and stop {}", jobId);
+        EXECUTING_JOBS.remove(jobId);
+        RuleAlteredJobSchedulerCenter.stop(jobId);
+    }
```
Comment (sandynz) [inline shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/PipelineJobExecutor.java:114]: Looks `EXECUTING_JOBS` is not needed any more, could we just depend on `RuleAlteredJobSchedulerCenter.stop` and remove this new method.

File: shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJob.java [hunk 2]
```diff
@@ -53,7 +53,7 @@ public void execute(final ShardingContext shardingContext) {
         } catch (final RuntimeException ex) {
             // CHECKSTYLE:ON
             log.error("job prepare failed, {}-{}", shardingContext.getJobName(), shardingContext.getShardingItem());
-            jobContext.close();
+            RuleAlteredJobWorker.getPIPELINE_JOB_EXECUTOR().stopJob(shardingContext.getJobName());
```
Comment (sandynz) [inline shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJob.java:56]: If `jobContext.close();` removed, looks it might cause resource leak.

`RuleAlteredJobWorker.getPIPELINE_JOB_EXECUTOR().` could be replaced by `RuleAlteredJobSchedulerCenter.stop`.

File: shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobWorker.java [hunk 3]
```diff
@@ -86,6 +87,9 @@
     
     private static final AtomicBoolean WORKER_INITIALIZED = new AtomicBoolean(false);
     
+    @Getter
+    private static final PipelineJobExecutor PIPELINE_JOB_EXECUTOR = new PipelineJobExecutor();
+
```
Comment (sandynz) [inline shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobWorker.java:92]: It's not necessary to add `PIPELINE_JOB_EXECUTOR`.

File: shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/PipelineJobExecutor.java [hunk 4]
```diff
@@ -105,6 +103,16 @@ private void execute(final JobConfigurationPOJO jobConfigPOJO) {
         }
     }
     
+    /**
+     * stop job.
```
Comment (sandynz) [inline shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/PipelineJobExecutor.java:107]: Illegal javadoc format.

**Review by sandynz — CHANGES_REQUESTED** [review]

File: shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJob.java (hunk 2 above)
Comment (ReyYang) [reply shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJob.java]: RuleAlteredJobSchedulerCenter.stop method will close jobContext.close()

**Review by sandynz — APPROVED** [review]
