### PR TITLE
Fix drop streaming failed and improve CDC inventory task thread wait intervals

### LINKED ISSUE #29274: CdcClient. dropStreaming (cdcjob) method called failed.
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
```
/usr/bin/java
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.2-SNAPSHOT
Commit ID: dirty-dc9d8bef0e5696e38b9dec665fb4a39cd29c1062
Commit Message: Improve stop_time display at show streaming list of CDC (#29090)
Branch: master
Build time: 2022-12-12T03:18:10+0800
```

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
shardingsphere-data-pipeline-cdc-client-5.4.2-SNAPSHOT.jar

### Expected behavior
CdcClient. dropStreaming (cdcjob) method called success.

### Actual behavior
CdcClient. dropStreaming (cdcjob) method called failed.

**CDC server‘s log**
[ERROR] 2023-12-04 15:47:41.165 [epollEventLoopGroup-4-133] o.a.s.p.f.n.CDCChannelInboundHandler - caught CDC resolution error
java.lang.NullPointerException: null

**CDC client's log**
[INFO ] 2023-12-04 15:47:41.159 [main] Bootstrap_api - ==================step8:CDC client drop Streaming…….j0302p0000648d3ff178416cc9c8193bd216866e8d
[ERROR] 2023-12-04 15:47:41.166 [nioEventLoopGroup-2-1] Bootstrap_api - Receive server error: null
[INFO ] 2023-12-04 15:47:51.162 [main] Bootstrap_api - Get result timeout

### PR DESCRIPTION
**Pull request by azexcy**
Ref #22500
Fixes #29274.

Changes proposed in this pull request:
  - Fix drop streaming failed
  - Adjust CDC thread wait intervals
  - Fixes needSort flag may not equals

---

Before committing this PR, I'm sure that I have checked the following options:
- [ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java [hunk 1]
```diff
@@ -218,7 +218,8 @@ private void processStopStreamingRequest(final ChannelHandlerContext ctx, final
     private void processDropStreamingRequest(final ChannelHandlerContext ctx, final CDCRequest request, final CDCConnectionContext connectionContext) {
         DropStreamingRequestBody requestBody = request.getDropStreamingRequestBody();
         checkPrivileges(request.getRequestId(), connectionContext.getCurrentUser().getGrantee(), backendHandler.getDatabaseNameByJobId(requestBody.getStreamingId()));
-        backendHandler.dropStreaming(connectionContext.getJobId());
+        String streamingId = request.getDropStreamingRequestBody().getStreamingId();
+        backendHandler.dropStreaming(streamingId);
```
Comment (sandynz) [inline proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java:222]: 1, `request.getDropStreamingRequestBody()` could be replace with `requestBody`

2, Could we remove `jobId` in connectionContext?

**Review by sandynz — CHANGES_REQUESTED** [review]

File: proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java (hunk 1 above)
Comment (azexcy) [reply proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java]: 2. `jobId` will used at channal inactive, eg. client closed without execute `stop streaming`

**Review by sandynz — APPROVED** [review]
