### PR TITLE
Fix rename index name error

### LINKED ISSUE #24238: Rename index error in mysql
## Bug Report
Rename index error in mysql

### Which version of ShardingSphere did you use?
Master.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy.

### Expected behavior
Rename index success.

### Actual behavior
Rename index failed.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```yaml
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://x/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: x    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://x/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: x    
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    t_order_big:
      actualDataNodes: ds_${0..1}.t_order_big_${0..100}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_big_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_item_inline
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
  bindingTables:
    - t_order,t_order_item
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}
    t_order_big_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_big_${order_id % 100}
    t_order_item_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_item_${order_id % 2}

  keyGenerators:
    snowflake:
      type: SNOWFLAKE
```

```sql
CREATE TABLE t_order (order_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL, PRIMARY KEY (order_id));

mysql> ALTER TABLE t_order ADD INDEX idx_t_order_user_id(user_id);
Query OK, 0 rows affected (2.43 sec)

mysql> ALTER TABLE t_order RENAME INDEX idx_t_order_user_id TO idx_user_id;
ERROR 1176 (42000): Key 'idx_t_order_user_id' doesn't exist in table 't_order_0'
mysql> show create table t_order;
```

### PR DESCRIPTION
**Pull request by FlyingZC**
Fixes #24238.

Changes proposed in this pull request:
  - fix rename index name error

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by FlyingZC** [comment]
image

File: sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/AlterTableStatement.java [hunk 1]
```diff
@@ -67,6 +68,8 @@ public abstract class AlterTableStatement extends AbstractSQLStatement implement
     
     private final Collection<DropIndexDefinitionSegment> dropIndexDefinitions = new LinkedList<>();
     
+    private final Collection<RenameIndexDefinitionSegment> renameIndexDefinitions = new LinkedList<>();
```
Comment (strongduanmu) [inline sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/AlterTableStatement.java:71]: Please add sql parser test case for this pr.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/AlterTableStatement.java (hunk 1 above)
Comment (FlyingZC) [reply sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/AlterTableStatement.java:71]: [OK]

**Review by strongduanmu — APPROVED** [review]
