### PR TITLE
fix(charset): fix statement set names

### LINKED ISSUE #18852: Exception occurred when execute set name "utf8" in ShardingSphere-Proxy with MySQL client
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy + MySQL

### Expected behavior
`set names "utf8";` execute successfully

### Actual behavior

Exception occurred :

```
[ERROR] 2022-07-05 12:02:52.770 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.nio.charset.IllegalCharsetNameException: "utf8"
	at java.nio.charset.Charset.checkName(Charset.java:315)
	at java.nio.charset.Charset.lookup2(Charset.java:484)
	at java.nio.charset.Charset.lookup(Charset.java:464)
	at java.nio.charset.Charset.forName(Charset.java:528)
	at org.apache.shardingsphere.proxy.backend.text.admin.mysql.executor.MySQLSetCharsetExecutor.parseCharset(MySQLSetCharsetExecutor.java:63)
	at org.apache.shardingsphere.proxy.backend.text.admin.mysql.executor.MySQLSetCharsetExecutor.execute(MySQLSetCharsetExecutor.java:47)
	at org.apache.shardingsphere.proxy.backend.text.encoding.DatabaseSetCharsetBackendHandler.execute(DatabaseSetCharsetBackendHandler.java:43)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:99)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:108)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

execute `set names "utf8";` in ShardingSphere-Proxy

### PR DESCRIPTION
**Pull request by JiekerTime**
Fixes #18852

### CODE REVIEW

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/MySQLSetCharsetExecutor.java [hunk 1]
```diff
@@ -60,7 +61,13 @@ private Charset parseCharset(final String value) {
             case "utf8mb4":
                 return StandardCharsets.UTF_8;
             default:
-                return Charset.forName(value);
+                try {
+                    return Charset.forName(value);
+                    // CHECKSTYLE:OFF
+                } catch (Exception ex) {
```
Comment (TeslaCN) [inline shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/MySQLSetCharsetExecutor.java:67]: Why does it need the check?

Comment (JiekerTime) [reply shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/MySQLSetCharsetExecutor.java:67]: > 

Perhaps you could try executing the statement set names "'utf8'";
It may cause Charset.forName("\"'utf8'\"");

Comment (TeslaCN) [reply shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/MySQLSetCharsetExecutor.java:67]: But you have handled the quote.

Comment (TeslaCN) [reply shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/MySQLSetCharsetExecutor.java:67]: > Perhaps you could try executing the statement set name '"utf8"';
> It may cause Charset.forName(""utf8"");

I don't think MySQL will accept `set name '"utf8"'`, we just need to handle the `set name "utf8"` in this PR.

Comment (JiekerTime) [reply shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/MySQLSetCharsetExecutor.java:67]: > > Perhaps you could try executing the statement set name '"utf8"';
> > It may cause Charset.forName(""utf8"");
> 
> I don't think MySQL will accept `set name '"utf8"'`, we just need to handle the `set name "utf8"` in this PR.

I think if we don't handle this exception it could lead to a decrease in user-friendliness like the following.

image

I can remove this try-catch if this is not a good change.

**Review by TeslaCN — APPROVED** [review]
