### PR TITLE
Fixes #9991

### LINKED ISSUE #9991: The output is incorrect when add resource and database connection failed
Execute RDL `ADD RESOURCE` ，but the client outputs `Can not drop resources` : 

```
mysql> add resource ds_0(host=127.0.0.1,port=3306,db=test1, user=root, password=123456);
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1
Current database: db_1

ERROR 1104 (C1104): Can not drop resources, resources [ds_0] do not exist.
```

### PR DESCRIPTION
**Pull request by menghaoranss**
Fixes #9991 .

### CODE REVIEW

File: shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/datasource/DataSourceValidator.java [hunk 1]
```diff
@@ -30,23 +31,23 @@
     /**
      * Validate.
      *
-     * @param dataSources data sources.
-     * @return is valid or not
+     * @param dataSourceConfigurations map of data source configuration
+     * @return collection of invalid data sources
      */
-    public boolean validate(final Map<String, DataSourceConfiguration> dataSources) {
```
Comment (tristaZero) [inline shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/datasource/DataSourceValidator.java:36]: Do you think It is better to rename it as `getInvalidatedDataSources()`? Or maybe we can pass one `DataSourceConfiguration` for validation (my preference).
How do you think?

**Review by tristaZero — CHANGES_REQUESTED** [review]

**Review by tristaZero — APPROVED** [review]
