### PR TITLE
fix issue 6850

### LINKED ISSUE #6850: Add test case for EncryptTableRuleConfigurationYamlSwapper

### PR DESCRIPTION
**Pull request by jacksparrow414**
* add test case for EncryptTableRuleConfigurationYamlSwapper

Fixes #6850 .

Changes proposed in this pull request:

### CODE REVIEW

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-common/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/EncryptTableRuleConfigurationYamlSwapperTest.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+        encryptColumnRuleConfig.setEncryptorName("test_encryptor");
+        Map<String, YamlEncryptColumnRuleConfiguration> columns = new LinkedHashMap<>(1);
+        columns.put("test_column", encryptColumnRuleConfig);
+        YamlEncryptTableRuleConfiguration yamlEncryptTableRuleConfig = new YamlEncryptTableRuleConfiguration();
+        yamlEncryptTableRuleConfig.setName("test_table");
+        yamlEncryptTableRuleConfig.setColumns(columns);
+        EncryptTableRuleConfiguration actualEncryptTableRuleConfig = tableRuleConfigYamlSwapper.swapToObject(yamlEncryptTableRuleConfig);
+        assertNotNull(actualEncryptTableRuleConfig);
+        assertThat(actualEncryptTableRuleConfig.getName(), is("test_table"));
+        Collection<EncryptColumnRuleConfiguration> actualColumn = actualEncryptTableRuleConfig.getColumns();
```
Comment (terrymanu) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-common/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/EncryptTableRuleConfigurationYamlSwapperTest.java:70]: The variable should be `actualColumns`

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-common/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/EncryptTableRuleConfigurationYamlSwapperTest.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+            Lists.newArrayList(
+                new EncryptColumnRuleConfiguration("encrypt_column_1", "encrypt_cipher_1", "", "", "test_encrypto_1r"),
+                new EncryptColumnRuleConfiguration("encrypt_column_2", "encrypt_cipher_2", "", "", "test_encryptor_2"),
+                new EncryptColumnRuleConfiguration("encrypt_column_3", "encrypt_cipher_3", "", "", "test_encryptor_3")
+              );
+        EncryptTableRuleConfiguration encryptTableRuleConfig = new EncryptTableRuleConfiguration("test_table", encryptColumnRuleConfigCollection);
+        YamlEncryptTableRuleConfiguration actualYamlEncryptTableRuleConfig = tableRuleConfigYamlSwapper.swapToYamlConfiguration(encryptTableRuleConfig);
+        assertNotNull(actualYamlEncryptTableRuleConfig);
+        assertFalse(actualYamlEncryptTableRuleConfig.getColumns().isEmpty());
+        assertThat(actualYamlEncryptTableRuleConfig.getColumns().size(), is(3));
```
Comment (terrymanu) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-common/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/EncryptTableRuleConfigurationYamlSwapperTest.java:51]: Please add more assertions of columns content

Comment (jacksparrow414) [reply shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-common/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/EncryptTableRuleConfigurationYamlSwapperTest.java]: > Please add more assertions of columns content

ok, I will add more assertions of columns content
