### PR TITLE
fix-10965

### LINKED ISSUE #10965: Add unit test for shardingsphere-readwrite-splitting
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-readwrite-splitting project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes

Add unit test for classes to test its public functions.

- [ ] ReadwriteSplittingRuleStatementConverter

## Examples FYI
- YamlRootRuleConfigurationsForYamlReadwriteSplittingRuleConfigurationTest

### PR DESCRIPTION
**Pull request by sizzlecar**
Fixes #10965.

Changes proposed in this pull request:
- add unit test

### CODE REVIEW

File: shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleStatementConverterTest.java [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+    private void assertEmptyRuleSegmentConvertResult(final ReadwriteSplittingRuleConfiguration emptyRuleSegmentConvertResult) {
+        assertTrue(emptyRuleSegmentConvertResult.getDataSources().isEmpty());
+        assertTrue(emptyRuleSegmentConvertResult.getLoadBalancers().isEmpty());
+    }
+
+    private void assertSingleRuleSegmentConvertResult(final ReadwriteSplittingRuleSegment readwriteSplittingRuleSegment,
+                                                      final ReadwriteSplittingRuleConfiguration singleRuleSegmentConvertResult) {
+        Collection<ReadwriteSplittingDataSourceRuleConfiguration> singleRuleSegmentConvertResultDataSources = singleRuleSegmentConvertResult.getDataSources();
+        Map<String, ShardingSphereAlgorithmConfiguration> singleRuleSegmentConvertResultLoadBalancers = singleRuleSegmentConvertResult.getLoadBalancers();
+        assertEquals(1, singleRuleSegmentConvertResultDataSources.size());
```
Comment (menghaoranss) [inline shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleStatementConverterTest.java:83]: Please use `assertThat` to instead of `assertEquals`

**Comment by tristaZero** [comment]
Hi @sizzlecar welcome, this is the first-time to see you here.

**Comment by sizzlecar** [comment]
> Hi @sizzlecar welcome, this is the first-time to see you here.

The second time actually

File: shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleStatementConverterTest.java (hunk 1 above)
Comment (sizzlecar) [reply shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleStatementConverterTest.java]: ok, already edited

File: shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleStatementConverterTest.java [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+import java.util.Map;
+import java.util.Properties;
+import java.util.stream.Stream;
+
+import static org.junit.Assert.assertThat;
+
+public final class ReadwriteSplittingRuleStatementConverterTest {
+
+    @Test
+    public void convertTest() {
```
Comment (menghaoranss) [inline shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleStatementConverterTest.java:39]: I suggest splitting this method to 3 methods for reading more friendly, such as  `assertEmptyRuleSegmentConvertResult ` ,`assertSingleRuleSegmentConvertResult ` and `assertMultipleReadwriteSplittingRuleSegments `

Comment (sizzlecar) [reply shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleStatementConverterTest.java]: Ok

**Review by menghaoranss — APPROVED** [review]
