### PR TITLE
fix #7163 replace dot with hyphen in configuration keys

### LINKED ISSUE #7163: Bug: Property read with '.'
## Bug Report
`
Caused by: java.lang.IllegalArgumentException: aes.key.value can not be null.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-29.0-jre.jar:na]
	at org.apache.shardingsphere.encrypt.algorithm.AESEncryptAlgorithm.createSecretKey(AESEncryptAlgorithm.java:57) ~[shardingsphere-encrypt-common-5.0.0-RC1-SNAPSHOT.jar:5.0.0-RC1-SNAPSHOT]
	at org.apache.shardingsphere.encrypt.algorithm.AESEncryptAlgorithm.init(AESEncryptAlgorithm.java:53) ~[shardingsphere-encrypt-common-5.0.0-RC1-SNAPSHOT.jar:5.0.0-RC1-SNAPSHOT]
	at org.apache.shardingsphere.spring.boot.registry.AbstractAlgorithmProvidedBeanRegistry.postProcessAfterInitialization(AbstractAlgorithmProvidedBeanRegistry.java:84) ~[shardingsphere-jdbc-spring-boot-starter-infra-5.0.0-RC1-SNAPSHOT.jar:5.0.0-RC1-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:430) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1798) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 93 common frames omitted

`

### Which version of ShardingSphere did you use?

5.0.0-RC1

springboot version 2.3.3

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Project start init error

### Reason analyze (If you can)

`Map<String, Object> propsMap = PropertyUtil.handle(environment, preFix + key + ".props", Map.class);`
props all read as Map

image
Read it as string key, than get the following error

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Project init

### PR DESCRIPTION
**Pull request by 291277058**
Fixes #7163

### CODE REVIEW

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java [hunk 1]
```diff
@@ -105,141 +103,141 @@
...
         ShardingTableRuleConfiguration actualSimpleRuleConfiguration = actualSimpleRuleConfigurations.iterator().next();
-        assertThat(actualSimpleRuleConfiguration.getLogicTable(), is("t_order"));
+        Assert.assertThat(actualSimpleRuleConfiguration.getLogicTable(), CoreMatchers.is("t_order"));
     }
     
     @Test
     public void assertComplexRule() {
         Collection<ShardingTableRuleConfiguration> actualComplexRuleConfigurations = complexRule.getTables();
-        assertThat(actualComplexRuleConfigurations.size(), is(1));
+        Assert.assertThat(actualComplexRuleConfigurations.size(), CoreMatchers.is(1));
```
Comment (tristaZero) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java:194]: Please import `CoreMatchers`, so that we can change all the `CoreMatchers.is` as `is`.

**Review by tristaZero — CHANGES_REQUESTED** [review]

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-route/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/impl/ShardingUpdateStatementValidator.java [hunk 2]
```diff
@@ -67,7 +69,8 @@ public void preValidate(final ShardingRule shardingRule, final RouteContext rout
                 if (shardingColumnSetAssignmentValue.isPresent() && shardingValue.isPresent() && shardingColumnSetAssignmentValue.get().equals(shardingValue.get())) {
                     continue;
                 }
-                throw new ShardingSphereException("Can not update sharding key, logic table: [%s], column: [%s].", tableName, each);
+                log.warn("should not update sharding key, logic table: {}, column: {}", tableName, each);
+//                throw new ShardingSphereException("Can not update sharding key, logic table: [%s], column: [%s].", tableName, each);
```
Comment (tristaZero) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-route/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/impl/ShardingUpdateStatementValidator.java:73]: Please rollback this change to focus on `props` issue solely.

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-route/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/impl/ShardingUpdateStatementValidatorTest.java [hunk 3]
```diff
@@ -96,7 +96,7 @@ public void assertValidateUpdateWithShardingKeyAndShardingParameterEquals() {
         new ShardingUpdateStatementValidator().preValidate(shardingRule, routeContext, mock(ShardingSphereMetaData.class));
     }
     
-    @Test(expected = ShardingSphereException.class)
```
Comment (tristaZero) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-route/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/impl/ShardingUpdateStatementValidatorTest.java:99]: What changes did make `ShardingSphereException` removed?

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java [hunk 4]
```diff
@@ -9,18 +9,14 @@
  *     http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
- * distributed under the License is distributed on an "AS IS" BASIS,
+ * distributed under the LicenseCoreMatchers.is distributed on an "ASCoreMatchers.is" BASIS,
```
Comment (tristaZero) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java:12]: Unexpected keyword replacement.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-common/src/main/java/org/apache/shardingsphere/encrypt/algorithm/RC4EncryptAlgorithm.java [hunk 5]
```diff
@@ -34,7 +34,9 @@
  */
 public final class RC4EncryptAlgorithm implements EncryptAlgorithm {
     
-    private static final String RC4_KEY = "rc4.key.value";
+    private static final String RC4_KEY = "rc4-key-value";
+    
+    private static final String RC4_KEY_COMPATIBLE = "rc4-key-value";
```
Comment (tristaZero) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-common/src/main/java/org/apache/shardingsphere/encrypt/algorithm/RC4EncryptAlgorithm.java:39]: Here, we no longer need `RC4_KEY_COMPATIBLE`.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-common/src/main/java/org/apache/shardingsphere/encrypt/algorithm/RC4EncryptAlgorithm.java [hunk 6]
```diff
@@ -88,6 +94,7 @@ private void reset() {
     
     /**
      * Crypt given byte array. Be aware, that you must init key, before using.
+     *
```
Comment (tristaZero) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-common/src/main/java/org/apache/shardingsphere/encrypt/algorithm/RC4EncryptAlgorithm.java:97]: Why did you add a new blank line?

**Review by tristaZero — CHANGES_REQUESTED** [review]

**Comment by tristaZero** [comment]
Hi @291277058 
Your work is better than expected, actually, thanks for your effortful contribution! 

Some comments need your fixing, though, I supposed it would not take you much time.

BTW, another new PR is not necessary, just do modification in your local branch and push them to GitHub. Then, this PR will be updated accordingly.

I am expected to see this merged soon!

Trista

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java (hunk 1 above)
Comment (291277058) [reply shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/test/java/org/apache/shardingsphere/sharding/spring/namespace/ShardingSpringNamespaceTest.java:194]: It will cause code check error. I have be suggested to avoid startic import.

File: RELEASE-NOTES.md [hunk 7]
```diff
@@ -33,7 +33,7 @@
 
 1. Optimization for Sharing Parser with ANTLR Visitor improving the parsing performance of long SQL by 100%~1000%
 1. Use multiple threads to load metadata for different data sources
-1. Support `allow.range.query.with.inline.sharding` option
+1. Support `allow-range-query-with-inline-sharding` option
```
Comment (kimmking) [inline RELEASE-NOTES.md:36]: previous release notes should be reserved.

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java [hunk 8]
```diff
@@ -76,7 +76,7 @@ public String doSharding(final Collection<String> availableTargetNames, final Pr
         if (allowRangeQuery) {
             return availableTargetNames;
         }
-        throw new UnsupportedOperationException("Since the property of `allow.range.query.with.inline.sharding` is false, inline sharding algorithm can not tackle with range query.");
+        throw new UnsupportedOperationException("Since the property of `allow-range-query-with-inline-sharding` is false, inline sharding algorithm can not tackle with range query.");
```
Comment (kimmking) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java:79]: replace allow-range-query-with-inline-sharding with constant

**Review by kimmking — CHANGES_REQUESTED** [review]

File: RELEASE-NOTES.md (hunk 7 above)
Comment (291277058) [reply RELEASE-NOTES.md:36]: How should i deal witch it.

Comment (291277058) [reply RELEASE-NOTES.md]: All .md field keep previous code form?How about after 4.1.1. or rewrite doc as `Update to 4.*.* - 4.1.1`

Comment (kimmking) [reply RELEASE-NOTES.md]: release-note is a history. just keep it original.

Comment (291277058) [reply RELEASE-NOTES.md]: I mean doc like ` _index.cn.md`
```
1. Update to 4.0.1 above.
2. Configure`allow-range-query-with-inline-sharding` to `true` (Default value is `false`).
3. A tip here: then each range query will be broadcast to every sharding table.
```

**Review by tristaZero — APPROVED** [review]

**Review by kimmking — APPROVED** [review]
