### PR TITLE
modify decoding plugin to mppdb_decoding and repair actual table name

### LINKED ISSUE #12620: scaling error in openGauss not support test_decoding and throw error when in increament task
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
sharding-proxy
### Expected behavior
scaling success .
### Actual behavior
scaling with exception.
### Reason analyze (If you can)
1. openGauss support mppdb_decoding, not test_decoding.
2. openGauss can't have 2 replication client, if replication  slots already exist, I will skip it.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
no need.
### Example codes for reproduce this issue (such as a github link).
no need.

### PR DESCRIPTION
**Pull request by justbk2015**
… issue

Fixes #12620.

Changes proposed in this pull request:
- change decoding plugin from test_decoding to mppdb_decoding.
- skip drop replication slot if already exists.
- ignore exception in dump thread if slot already in use.
- skip recreate primary key exception.
- repair logical and actual table name incorrent get issue.
- remove with sql in create table.

### CODE REVIEW

File: shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java [hunk 1]
```diff
@@ -57,7 +60,14 @@ public void prepareTargetTables(final JobConfiguration jobConfig) {
              Connection targetConnection = targetDataSource.getConnection()) {
             for (Entry<String, Collection<String>> entry : createLogicTableSQLs.entrySet()) {
                 for (String each : entry.getValue()) {
-                    executeTargetTableSQL(targetConnection, each);
+                    try {
+                        executeTargetTableSQL(targetConnection, each);
+                    } catch (SQLException sqlExp) {
```
Comment (sandynz) [inline shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java:65]: Could be `final SQLException ex`.

File: shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java [hunk 2]
```diff
@@ -123,18 +133,51 @@ private String queryTableDefinition(final Connection sourceConnection, final int
...
-            }).collect(Collectors.toList());
+            }).filter(sql -> !"".equals(sql)).collect(Collectors.toList());
             result.put(each.getLogicTableName(), logicTableSQLs);
         }
         return result;
     }
+    
+    @Override
+    protected String replaceActualTableNameToLogicTableName(final String createOrAlterTableSQL, final String actualTableName, final String logicTableName) {
+        StringBuilder sb = new StringBuilder(createOrAlterTableSQL);
```
Comment (sandynz) [inline shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java:152]: `sb` could be meaningful variable name.

File: shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java [hunk 3]
```diff
@@ -123,18 +133,51 @@ private String queryTableDefinition(final Connection sourceConnection, final int
...
+            if (start <= 0) {
+                return sb.toString();
+            }
+            int end = start + actualTableName.length();
+            sb.replace(start, end, logicTableName);
+        }
+    }
+    
+    private String skipCreateTableExtendSet(final String createSql) {
+        String lowerCreateSql = createSql.toLowerCase();
```
Comment (sandynz) [inline shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java:164]: `Sql` could be `SQL`

File: shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java [hunk 4]
```diff
@@ -123,18 +133,51 @@ private String queryTableDefinition(final Connection sourceConnection, final int
...
+        String[] search = {WITH_OF_TABLE_EXTEND, ")"};
+        List<Integer> searchPos = new ArrayList<>(2);
+        int startPos = 0;
+        for (String str: search) {
```
Comment (sandynz) [inline shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java:168]: `String str` could be `String each`

File: shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java [hunk 5]
```diff
@@ -123,18 +133,51 @@ private String queryTableDefinition(final Connection sourceConnection, final int
...
+            int curSearch = lowerCreateSql.indexOf(str, startPos);
+            if (curSearch <= 0) {
+                break;
+            }
+            searchPos.add(curSearch);
+            startPos = curSearch;
+        }
+        // if not search with ( and ), nothing to do.
```
Comment (sandynz) [inline shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java:176]: Could be removed.
Code of conduct: Split codes that need to add notes with it into small methods, which are explained with method names.

File: shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java [hunk 6]
```diff
@@ -123,18 +133,51 @@ private String queryTableDefinition(final Connection sourceConnection, final int
...
+        if (searchPos.size() != 2) {
+            return createSql;
+        }
+
```
Comment (sandynz) [inline shardingsphere-scaling/shardingsphere-scaling-dialect/shardingsphere-scaling-opengauss/src/main/java/org/apache/shardingsphere/scaling/opengauss/component/checker/OpenGaussDataSourcePreparer.java:180]: Blank line could be removed.

**Review by sandynz — CHANGES_REQUESTED** [review]

**Review by sandynz — APPROVED** [review]
