### PR TITLE
Exception occurs when Changing /meta/scheamName/dataSources/ config in registry.

### LINKED ISSUE #13213: Exception occurs when Changing /meta/scheamName/dataSources/ config in registry.
Exception occurs when Changing /meta/scheamName/dataSources/ config in registry. 
SQL executing in progress  exception occurs, The reason is the eventbus consumes DataSourceChangedEvent closing changedDataSource.So proxy need have the ability to gracefully modify dataSource configurations. 

Welcome to discuss with me.

Exception below:
`[ERROR] 2021-10-22 09:51:28.610 [ShardingSphere-Command-2] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1192)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1187)
	at com.mysql.jdbc.ConnectionImpl.getMetaData(ConnectionImpl.java:2901)
	at com.mysql.jdbc.ConnectionImpl.getMetaData(ConnectionImpl.java:2896)
	at com.zaxxer.hikari.pool.ProxyConnection.getMetaData(ProxyConnection.java:359)
	at com.zaxxer.hikari.pool.HikariProxyConnection.getMetaData(HikariProxyConnection.java)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:80)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:64)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:101)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.parallelExecute(ExecutorEngine.java:97)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:82)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:65)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.ProxyJDBCExecutor.execute(ProxyJDBCExecutor.java:71)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.useDriverToExecute(ProxySQLExecutor.java:183)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:136)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:125)
	at org.apache.shardingsphere.proxy.backend.communication.ProxyLockEngine.doExecute(ProxyLockEngine.java:103)
	at org.apache.shardingsphere.proxy.backend.communication.ProxyLockEngine.execute(ProxyLockEngine.java:81)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.execute(DatabaseCommunicationEngine.java:126)
	at org.apache.shardingsphere.proxy.backend.text.data.impl.SchemaAssignedDatabaseBackendHandler.execute(SchemaAssignedDatabaseBackendHandler.java:55)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:57)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:99)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

### PR DESCRIPTION
**Pull request by lwclover**
Fixes #13213.
The solution is waiting all active connections return to datasource，then close the datasource.

### CODE REVIEW

**Review by menghaoranss — APPROVED** [review]

File: shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/datasource/killer/impl/DefaultDataSourceKiller.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+package org.apache.shardingsphere.infra.config.datasource.killer.impl;
+
+import java.sql.SQLException;
+
+import javax.sql.DataSource;
+
+import org.apache.shardingsphere.infra.config.datasource.killer.DataSourceKiller;
+
+/**
+ * Kill hikari data source.
```
Comment (TeslaCN) [inline shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/datasource/killer/impl/DefaultDataSourceKiller.java:27]: Could you please check the javadoc again?

**Review by TeslaCN — APPROVED** [review]

**Review by tristaZero — APPROVED** [review]

**Comment by tristaZero** [comment]
@lwclover @menghaoranss @TeslaCN Cool, guys.
