### PR TITLE
Automatically start a distributed transaction if needed(#20234)

### LINKED ISSUE #20234: xa does not guarantee transactionality
## Bug Report
When the xa switch is turned on, two pieces of data are inserted into two datasources when inserting, but transactionality cannot be guaranteed.

### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

image.

### PR DESCRIPTION
**Pull request by FlyingZC**
For #20234.

Changes proposed in this pull request:
  - Automatically start a xa transaction if needed in proxy adapter
---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `mvn clean install -B -T2C -DskipTests -Dmaven.javadoc.skip=true -e`.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutorFactory.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+        SQLStatement sqlStatement = executionContext.getSqlStatementContext().getSqlStatement();
+        IProxySQLExecutor proxySQLExecutor;
+        if (needAutoTransaction(executionContext, transactionStatus, sqlStatement)) {
+            proxySQLExecutor =
+                    new ProxySQLExecutorWrapper(databaseCommunicationEngine.getDriverType(), (JDBCBackendConnection) databaseCommunicationEngine.getBackendConnection(), databaseCommunicationEngine);
+        } else {
+            proxySQLExecutor =
+                    new ProxySQLExecutor(databaseCommunicationEngine.getDriverType(), (JDBCBackendConnection) databaseCommunicationEngine.getBackendConnection(), databaseCommunicationEngine);
+        }
+        return proxySQLExecutor;
```
Comment (strongduanmu) [inline proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutorFactory.java:52]: Please rename proxySQLExecutor to result.

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutorFactory.java [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+     * @param executionContext execution context
+     * @param databaseCommunicationEngine database communication engine
+     * @return Proxy SQL executor
+     */
+    public static IProxySQLExecutor newInstance(final ExecutionContext executionContext, final JDBCDatabaseCommunicationEngine databaseCommunicationEngine) {
+        TransactionStatus transactionStatus = databaseCommunicationEngine.getBackendConnection().getConnectionSession().getTransactionStatus();
+        SQLStatement sqlStatement = executionContext.getSqlStatementContext().getSqlStatement();
+        IProxySQLExecutor proxySQLExecutor;
+        if (needAutoTransaction(executionContext, transactionStatus, sqlStatement)) {
+            proxySQLExecutor =
```
Comment (strongduanmu) [inline proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutorFactory.java:46]: Can we cache the proxySQLExecutor to improve performance?

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/JDBCDatabaseCommunicationEngine.java [hunk 3]
```diff
@@ -127,6 +125,7 @@ public ResponseHeader execute() throws SQLException {
         if (executionContext.getExecutionUnits().isEmpty()) {
             return new UpdateResponseHeader(executionContext.getSqlStatementContext().getSqlStatement());
         }
+        IProxySQLExecutor proxySQLExecutor = ProxySQLExecutorFactory.newInstance(executionContext, this);
```
Comment (strongduanmu) [inline proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/JDBCDatabaseCommunicationEngine.java:128]: Can we consider jdbc adapter?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutorWrapper.java [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+import org.apache.shardingsphere.proxy.backend.communication.jdbc.connection.JDBCBackendConnection;
+import org.apache.shardingsphere.proxy.backend.communication.jdbc.transaction.JDBCBackendTransactionManager;
+
+import java.sql.SQLException;
+import java.util.List;
+
+/**
+ * Proxy SQL executor wrapper.
+ */
+public final class ProxySQLExecutorWrapper implements IProxySQLExecutor {
```
Comment (TeslaCN) [inline proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutorWrapper.java:32]: Why not just add these logics into `ProxySQLExecutor`? There are already some transaction logics in `ProxySQLExecutor`.

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java [hunk 5]
```diff
@@ -73,19 +75,12 @@ public final class ProxySQLExecutor {
     
     private final JDBCBackendConnection backendConnection;
     
-    private final ProxyJDBCExecutor jdbcExecutor;
-    
-    private final RawExecutor rawExecutor;
+    private final JDBCDatabaseCommunicationEngine databaseCommunicationEngine;
     
     public ProxySQLExecutor(final String type, final JDBCBackendConnection backendConnection, final JDBCDatabaseCommunicationEngine databaseCommunicationEngine) {
```
Comment (TeslaCN) [inline proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java:80]: Consider simplifying this with `RequiredArgsConstructor`

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java [hunk 6]
```diff
@@ -143,16 +134,40 @@ private boolean isPostgreSQLOrOpenGaussStatement(final SQLStatement sqlStatement
      * @throws SQLException SQL exception
      */
     public List<ExecuteResult> execute(final ExecutionContext executionContext) throws SQLException {
+        return needAutoTransaction(executionContext) ? doExecuteWithinTransaction(executionContext) : doExecute(executionContext);
+    }
+    
+    private boolean needAutoTransaction(final ExecutionContext executionContext) {
+        TransactionStatus transactionStatus = backendConnection.getConnectionSession().getTransactionStatus();
+        SQLStatement sqlStatement = executionContext.getSqlStatementContext().getSqlStatement();
+        return TransactionType.XA == transactionStatus.getTransactionType() && !transactionStatus.isInTransaction() && sqlStatement instanceof DMLStatement
```
Comment (strongduanmu) [inline proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java:143]: Do we need to add base transaction here?

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java [hunk 7]
```diff
@@ -143,16 +134,40 @@ private boolean isPostgreSQLOrOpenGaussStatement(final SQLStatement sqlStatement
...
+                && !(sqlStatement instanceof SelectStatement) && executionContext.getExecutionUnits().size() > 1;
+    }
+    
+    private List<ExecuteResult> doExecuteWithinTransaction(final ExecutionContext executionContext) throws SQLException {
+        List<ExecuteResult> result;
+        JDBCBackendTransactionManager transactionManager = new JDBCBackendTransactionManager(backendConnection);
```
Comment (strongduanmu) [inline proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java:149]: Is it possible to avoid creating the JDBCBackendTransactionManager object every time?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java (hunk 7 above)
Comment (FlyingZC) [reply proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java:149]: The `JDBCBackendTransactionManager` just only holds the `ShardingSphereTransactionManagerEngine` object, which has been created in the rule in advance.

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java [hunk 8]
```diff
@@ -143,16 +134,40 @@ private boolean isPostgreSQLOrOpenGaussStatement(final SQLStatement sqlStatement
      * @throws SQLException SQL exception
      */
     public List<ExecuteResult> execute(final ExecutionContext executionContext) throws SQLException {
+        return needAutoTransaction(executionContext) ? doExecuteWithinTransaction(executionContext) : doExecute(executionContext);
```
Comment (strongduanmu) [inline proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java:137]: Please rename needAutoTransaction to `isNeedImplictCommit` and rename doExecuteWithinTransaction to `doExecuteWithImplictCommit`.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java (hunk 8 above)
Comment (strongduanmu) [reply proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java:137]: Refer to mysql document——https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html, implicit commit should be a proper noun.

Comment (strongduanmu) [reply proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java:137]: In addition, can we investigate whether other databases also have implicit commit behavior?

Comment (FlyingZC) [reply proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java:148]: `implicit commit` is a proper noun.I will rename methods to` isNeedImplicitCommitTransaction` and `doExecuteWithImplicitCommitTransaction`.

**Review by strongduanmu — APPROVED** [review]
