### PR TITLE
Fixed not persist data-source-properties.

### LINKED ISSUE #14357: Persist data-source-properties to register configuration center.
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-JDBC`

### Expected behavior

Persist data-source-properties in zookeeper.

### Actual behavior

No persist.

### configuration

```
spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      ds-0:
        jdbc-url: jdbc:mysql://127.0.0.1:13306/demo_primary_ds?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        connectionTimeout: 5000
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 1000
          prepStmtCacheSqlLimit: 2048
      ds-1:
        jdbc-url: jdbc:mysql://127.0.0.1:13307/demo_primary_ds?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        minPoolSize: 1
        connectionTimeout: 5000
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 1000
          prepStmtCacheSqlLimit: 2048
      ds-2:
        jdbc-url: jdbc:mysql://127.0.0.1:13308/demo_primary_ds?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        connectionTimeout: 5000
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 1000
          prepStmtCacheSqlLimit: 2048
      names: ds-0, ds-1, ds-2
```

### PR DESCRIPTION
**Pull request by zjcnb**
Fixes #14357

### CODE REVIEW

File: shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/config/datasource/pool/creator/impl/HikariDataSourcePoolCreatorTest.java [hunk 1]
```diff
@@ -55,6 +56,10 @@ public void assertCreateDataSourceConfiguration() {
         assertThat(configuration.getProps().get("password"), is("root"));
         assertThat(configuration.getProps().get("maximumPoolSize"), is(10));
         assertThat(configuration.getProps().get("minimumIdle"), is(1));
+        Properties dataSourceProperties = (Properties) configuration.getProps().get("dataSourceProperties");
```
Comment (LeeGuoPing) [inline shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/config/datasource/pool/creator/impl/HikariDataSourcePoolCreatorTest.java:59]: I think it may better assert dataSourceProperties is not null, otherwise will throw NPE.

File: shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/config/datasource/pool/creator/impl/HikariDataSourcePoolCreatorTest.java [hunk 2]
```diff
@@ -29,8 +29,7 @@
 
 import static org.hamcrest.CoreMatchers.instanceOf;
 import static org.hamcrest.CoreMatchers.is;
-import static org.junit.Assert.assertFalse;
-import static org.junit.Assert.assertThat;
+import static org.junit.Assert.*;
```
Comment (LeeGuoPing) [inline shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/config/datasource/pool/creator/impl/HikariDataSourcePoolCreatorTest.java:32]: better use detail import, not use *

File: shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/config/datasource/pool/creator/impl/HikariDataSourcePoolCreatorTest.java [hunk 3]
```diff
@@ -56,10 +55,9 @@ public void assertCreateDataSourceConfiguration() {
         assertThat(configuration.getProps().get("password"), is("root"));
         assertThat(configuration.getProps().get("maximumPoolSize"), is(10));
         assertThat(configuration.getProps().get("minimumIdle"), is(1));
-        Properties dataSourceProperties = (Properties) configuration.getProps().get("dataSourceProperties");
-        assertThat(dataSourceProperties.get("prepStmtCacheSqlLimit"), is(1024));
-        assertThat(dataSourceProperties.get("cachePrepStmts"), is(true));
-        assertThat(dataSourceProperties.get("prepStmtCacheSize"), is(1000));
+        assertNotNull(configuration.getProps());
```
Comment (LeeGuoPing) [inline shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/config/datasource/pool/creator/impl/HikariDataSourcePoolCreatorTest.java]: assert it before use

**Review by menghaoranss — APPROVED** [review]
