### PR TITLE
Fix 9892 : RegisterCenter.renew(DataSourceAddedEvent e) throw UnsupportedOperationException when RDL add resource

### LINKED ISSUE #9892: RegisterCenter.renew(DataSourceAddedEvent e) throw UnsupportedOperationException when RDL add resource
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
No exception thrown

### Actual behavior
Exception:
```
Exception thrown by subscriber method renew(org.apache.shardingsphere.governance.core.event.model.datasource.DataSourceAddedEvent) on subscriber org.apache.shardingsphere.governance.core.registry.RegistryCenter@4e3958e7 when dispatching event: org.apache.shardingsphere.governance.core.event.model.datasource.DataSourceAddedEvent@246a4a
java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209)
	at java.util.AbstractMap.putAll(AbstractMap.java:281)
	at org.apache.shardingsphere.governance.core.registry.RegistryCenter.addDataSourceConfigurations(RegistryCenter.java:151)
	at org.apache.shardingsphere.governance.core.registry.RegistryCenter.renew(RegistryCenter.java:369)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.impl.AddResourceBackendHandler.post(AddResourceBackendHandler.java:62)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rdl.impl.AddResourceBackendHandler.execute(AddResourceBackendHandler.java:56)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:57)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:93)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Reason analyze (If you can)
guava Maps.transformValues returned map haven't implemented put method

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
proxy client command line, run RDL SQL:
```
add resource (res1 = localhost:3306:demo_ds_0:root:root);
```

### PR DESCRIPTION
**Pull request by sandynz**
Fixes #9892.

Changes proposed in this pull request:
- re-implement `YamlConfigurationConverter.convertDataSourceConfigurations` to support `Map.put`

### CODE REVIEW

File: shardingsphere-governance/shardingsphere-governance-core/src/main/java/org/apache/shardingsphere/governance/core/registry/RegistryCenter.java [hunk 1]
```diff
@@ -148,6 +148,7 @@ public void persistDataSourceConfigurations(final String schemaName, final Map<S
     
     private void addDataSourceConfigurations(final String schemaName, final Map<String, DataSourceConfiguration> dataSourceConfigurations) {
         Map<String, DataSourceConfiguration> dataSourceConfigurationMap = loadDataSourceConfigurations(schemaName);
+        dataSourceConfigurationMap = new LinkedHashMap<>(dataSourceConfigurationMap);
```
Comment (tristaZero) [inline shardingsphere-governance/shardingsphere-governance-core/src/main/java/org/apache/shardingsphere/governance/core/registry/RegistryCenter.java:151]: How about we fix this issue in `convertDataSourceConfigurations()` of `YamlConfigurationConverter`? It looks a little puzzled that `new LinkedHashMap<>(dataSourceConfigurationMap)`.

**Review by tristaZero — CHANGES_REQUESTED** [review]
Hi @sandynz , Appreciated your work to find the cause and fix it.

File: shardingsphere-governance/shardingsphere-governance-core/src/main/java/org/apache/shardingsphere/governance/core/registry/RegistryCenter.java (hunk 1 above)
Comment (sandynz) [reply shardingsphere-governance/shardingsphere-governance-core/src/main/java/org/apache/shardingsphere/governance/core/registry/RegistryCenter.java:151]: That's ok.

**Review by tristaZero — APPROVED** [review]
