### PR TITLE
fix 18904(#18904)

### LINKED ISSUE #18904: transaction,AUTO_INCREMENT,useGeneratedKeys,insert null returns the same id
first,when using <b>AUTO_INCREMENT,useGeneratedKeys,insert null </b>will cause the exception `ResultSet should call next or has no more data.`,it seems to this issue  #18212  （[here](https://github.com/apache/shardingsphere/issues/18212)） ,it has been resolved to  #18224. （[here](https://github.com/apache/shardingsphere/pull/18224)）

now i use @Transactional,insert for many times,it returns the first one's id.

### Which version of ShardingSphere did you use?
5.1.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
the newest id
### Actual behavior
the first id
### Reason analyze (If you can)
the first insert,set the right id
image

the second insert,generatedValues not clear
image

then the ResultSet returns the first value
image

it's why this bug appears
image
image

### Example codes for reproduce this issue (such as a github link).
```
    @Transactional
    @Override
    public void idList() {
        for (int i = 0; i < 5; i++) {
            Tree tree = new Tree();
            tree.setId(null);
            tree.setPid(i);
            mapper.insertTree(tree);
            int x = 1;
        }
    }

<insert id="insertTree" useGeneratedKeys="true" keyProperty="id">
    INSERT INTO tree(id,pid) VALUES (#{id},#{pid})
</insert>
```

### PR DESCRIPTION
**Pull request by yunmengmeng**
Fixes #18904

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Can you fix the CI?

**Comment by yunmengmeng** [comment]
> Can you fix the CI?

ok , i change the code and pull the request again

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java [hunk 1]
```diff
@@ -30,30 +31,31 @@
 import static org.junit.Assert.assertNotNull;
 import static org.junit.Assert.assertThat;
 import static org.junit.Assert.assertTrue;
+import static org.junit.Assert.assertNotEquals;
 
 public final class ReadwriteSplittingPreparedStatementTest extends AbstractShardingSphereDataSourceForReadwriteSplittingTest {
-
```
Comment (strongduanmu) [inline shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java:35]: Please execute `mvn spotless:apply` to format code on your local machine.

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java [hunk 2]
```diff
@@ -92,4 +94,31 @@ public void assertGetGeneratedKeysWithPrimaryKeyIsNull() throws SQLException {
...
+            Object lastIdObject = null;
+            Object idObject = null;
+            for (int i = 1; i <= 3; i++) {
+                preparedStatement.setObject(1, null);
+                preparedStatement.setString(2, "OK");
+                preparedStatement.executeUpdate();
+                ResultSet generatedKeys = preparedStatement.getGeneratedKeys();
+                assertTrue(generatedKeys.next());
+                int columnCount = generatedKeys.getMetaData().getColumnCount();
+                for (int index = 0; index < columnCount; index++) {
```
Comment (strongduanmu) [inline shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java:114]: Can you remove this loop logic? Just call `generatedKeys.getObject(1)` once.

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java [hunk 3]
```diff
@@ -92,4 +94,31 @@ public void assertGetGeneratedKeysWithPrimaryKeyIsNull() throws SQLException {
...
     }
+
+    @Test
+    public void assertGetGeneratedKeysWithPrimaryKeyIsNullInTransactional() throws SQLException {
+        try (
+                Connection connection = getReadwriteSplittingDataSource()
+                        .getConnection();
+                PreparedStatement preparedStatement = connection.prepareStatement("INSERT INTO t_config(id, status) VALUES(?, ?);", Statement.RETURN_GENERATED_KEYS)) {
+            connection.setAutoCommit(false);
+            Object lastIdObject = null;
```
Comment (strongduanmu) [inline shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java:105]: Do you think `lastGeneratedId` and `generatedId` is better?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @rfscholte, I just spent some time evaluating the impact of this bug, and I found that it is a general problem. When we reuse PreparedStatement, features such as Sharding, ReadWriteSplitting, and Encrypt will have the problem of duplicate generated ids. So consider adding more unit tests for Sharding and Encrypt?

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java (hunk 2 above)
Comment (yunmengmeng) [reply shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java]: > Can you remove this loop logic? Just call `generatedKeys.getObject(1)` once.

I saw the previous test case and imitated it.I have changed them now.

**Comment by rfscholte** [comment]
@strongduanmu hi me?

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java [hunk 4]
```diff
@@ -92,4 +94,28 @@ public void assertGetGeneratedKeysWithPrimaryKeyIsNull() throws SQLException {
...
+            Object lastGeneratedId = null;
+            Object generatedId = null;
+            for (int i = 1; i <= 3; i++) {
+                preparedStatement.setObject(1, null);
+                preparedStatement.setString(2, "OK");
+                preparedStatement.executeUpdate();
+                ResultSet generatedKeys = preparedStatement.getGeneratedKeys();
+                assertTrue(generatedKeys.next());
+                generatedId = generatedKeys.getObject(1);
+                assertNotEquals(lastGeneratedId, generatedId);
```
Comment (strongduanmu) [inline shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java:114]: Please use assertThat instead of assertNotEquals.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java (hunk 4 above)
Comment (yunmengmeng) [reply shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java]: ok

Comment (yunmengmeng) [reply shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java]: > Please use assertThat instead of assertNotEquals.

ok

**Comment by strongduanmu** [comment]
Hi @yunmengmeng, can you sync the latest master branch code?

**Comment by yunmengmeng** [comment]
> Hi @yunmengmeng, can you sync the latest master branch code?

It seems that it created one more single_table. When executing sql "SHOW SINGLE TABLES",it's expected 3 and returned 4.I don't kown whether it is related to my change code ?

**Review by strongduanmu — APPROVED** [review]
LGTM

**Review by terrymanu — APPROVED** [review]
