### PR TITLE
ShardingSphere-Proxy MySQL supports executing multi update/delete statements

### LINKED ISSUE #16124: ShardingSphere-Proxy MySQL throws Unsupported command: [COM_SET_OPTION]
### Which version of ShardingSphere did you use?
master - b31a5439e0c608ee9a735aadb426ed03b1e98a42

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy MySQL

### Expected behavior

Batched update succeed.

### Actual behavior

```
Exception in thread "main" java.sql.SQLException: Unsupported command: [COM_SET_OPTION]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.disableMultiQueries(MysqlIO.java:3670)
	at com.mysql.jdbc.PreparedStatement.executePreparedBatchAsMultiStatement(PreparedStatement.java:1492)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1303)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
	at icu.wwj.MySQLBatchedUpdate.main(MySQLBatchedUpdate.java:18)
```

### Reason analyze (If you can)

MySQL JDBC driver enable `rewriteBatchedStatements=true`.

### Example codes for reproduce this issue (such as a github link).

```java
try (Connection connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:13306/sbtest?useSSL=false&rewriteBatchedStatements=true", "root", "root")) {
    connection.setAutoCommit(false);
    try (PreparedStatement preparedStatement = connection.prepareStatement("update sbtest2 set k=k+1 where id = ?")) {
        for (int i = 0; i < 10; i++) {
            preparedStatement.setInt(1, i + 1);
            preparedStatement.addBatch();
        }
        preparedStatement.executeBatch();
    }
    connection.rollback();
}

```

### How

- [x] Supports COM_SET_OPTION.
- [ ] Handle multi-statements update in COM_QUERY executor.

### PR DESCRIPTION
**Pull request by TeslaCN**
Fixes #16124.

### CODE REVIEW

**Comment by TeslaCN** [comment]
I found a critical problem https://github.com/apache/shardingsphere/issues/16294. We have to fix it before merging this PR.

File: shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java [hunk 1]
```diff
@@ -0,0 +1,198 @@
...
+        }
+    }
+    
+    private ShardingSphereSQLParserEngine getSQLParserEngine() {
+        MetaDataContexts metaDataContexts = ProxyContext.getInstance().getContextManager().getMetaDataContexts();
+        return new ShardingSphereSQLParserEngine(DatabaseTypeRegistry.getTrunkDatabaseTypeName(metaDataContexts.getMetaData(connectionSession.getSchemaName()).getResource().getDatabaseType()),
+                metaDataContexts.getGlobalRuleMetaData().findSingleRule(SQLParserRule.class).orElse(null));
+    }
+    
+    private List<String> extractMultiStatements(final Pattern pattern, final String sql) {
```
Comment (userkdg) [inline shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java:116]: #14636 jdbc still no supports executing multi statement.

File: shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java [hunk 2]
```diff
@@ -0,0 +1,198 @@
...
+    }
+    
+    private void prepareBatchedStatement(final JDBCExecutionUnit each) throws SQLException {
+        Statement statement = each.getStorageResource();
+        for (ExecutionUnit eachExecutionUnit : dataSourcesToExecutionUnits.get(each.getExecutionUnit().getDataSourceName())) {
+            statement.addBatch(eachExecutionUnit.getSqlUnit().getSql());
+        }
+    }
+    
+    private UpdateResponseHeader executeBatchedStatements(final ExecutionGroupContext<JDBCExecutionUnit> executionGroupContext) throws SQLException {
```
Comment (userkdg) [inline shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java:163]: directly in the proxy-front module,   compared to the behavior consistency of non-multi statement is "run in the opposite direction "

File: shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java (hunk 1 above)
Comment (TeslaCN) [reply shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java:116]: If you connect Proxy via MySQL JDBC Driver, consider setting rewriteBatchedStatements=true and use the JDBC addBatch & executeBatch, the Driver will handle the SQL concat stuff.
Or consider setting allowMultiQueries=true if you are trying to send multi statements to MySQL.

File: shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java (hunk 2 above)
Comment (TeslaCN) [reply shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java:163]: Sorry, I dont understand. Could you please clarify?

File: shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java (hunk 1 above)
Comment (userkdg) [reply shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java:116]: yes, connect url must add allowMultiQueries=true | rewriteBatchedStatements=true
However, what I want to say is that this problem will still exist in shardingsphere-jdbc, we should support this feature by sql parser or satisfies both proxy and jdbc on basic module.

File: shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java (hunk 2 above)
Comment (userkdg) [reply shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java:163]: > Sorry, I dont understand. Could you please clarify?

pass.

File: shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java (hunk 1 above)
Comment (TeslaCN) [reply shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java:116]: This PR is just doing some trick to avoid error occurs in Proxy before the SQL parser supports multi statements. We may following the feature request after 5.1.1 released.

Comment (TeslaCN) [reply shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java:116]: > #14636 jdbc still no supports executing multi statement.

Hi @userkdg The exception in this issue may be thrown by JDBC Driver instead of ShardingSphere.

**Review by terrymanu — APPROVED** [review]

**Comment by userkdg** [comment]
你好，很高兴收到您的邮件，谢谢。
