### PR TITLE
Fix the ExecutorService does not shutdown when loading table meta data failed.

### LINKED ISSUE #11468: ExecutorService does not shutdown when loading table meta data failed.
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
ExecutorService is supposed to shutdown for process to exit when loading table meta data failed.

### Actual behavior
ExecutorService does not shutdown when loading table meta data failed, that causes the process to not exit correctly.

### Reason analyze (If you can)
image
When a task calling loadTableByDataNode failed, the exception will be thrown resulting in ExecutorService cannot shutdown.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Set the property check-table-metadata-enabled to true
2. Create scenarios where calling loadTableByDataNode failed.

### PR DESCRIPTION
**Pull request by sccc803**
Fixes #11468.

Changes proposed in this pull request:
- Shutdown the ExecutorService in catch code block.

### CODE REVIEW

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/metadata/ShardingTableMetaDataBuilder.java [hunk 1]
```diff
@@ -98,6 +98,7 @@
             try {
                 getTableMetaData(value).ifPresent(tableMetaData -> result.put(key, tableMetaData));
             } catch (final InterruptedException | ExecutionException | TimeoutException ex) {
+                executorService.shutdownNow();
```
Comment (RaigorJiang) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/metadata/ShardingTableMetaDataBuilder.java:101]: Why not close the resource in the finally block？

**Review by tristaZero — APPROVED** [review]
@sccc803 Hey, thanks for your kind tweak.
