### PR TITLE
Fix mysql cast function parsing error (#24637)

### LINKED ISSUE #24637: The unit test for Mysql parsing fails
#24532  Branches added to **BaseRule.g4/castFunction** may crash in a null pointer. because **ctx.dataType()**  my not exist.
```java 
 @Override
    public final ASTNode visitCastFunction(final CastFunctionContext ctx) {
        calculateParameterCount(ctx.expr());
        FunctionSegment result = new FunctionSegment(ctx.getStart().getStartIndex(), ctx.getStop().getStopIndex(), ctx.CAST().getText(), getOriginalText(ctx));
        for (ExprContext each : ctx.expr()) {
            ASTNode expr = visit(each);
            if (expr instanceof ColumnSegment) {
                result.getParameters().add((ColumnSegment) expr);
            } else if (expr instanceof LiteralExpressionSegment) {
                result.getParameters().add((LiteralExpressionSegment) expr);
            }
        }
        result.getParameters().add((DataTypeSegment) visit(ctx.dataType()));
        return result;
    }
```

image

### PR DESCRIPTION
**Pull request by jiangtao69039**
Fixes #24637

### CODE REVIEW

File: sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java [hunk 1]
```diff
@@ -907,7 +908,19 @@ public final ASTNode visitCastFunction(final CastFunctionContext ctx) {
                 result.getParameters().add((LiteralExpressionSegment) expr);
             }
         }
-        result.getParameters().add((DataTypeSegment) visit(ctx.dataType()));
+        if (ctx.dataType() != null) {
```
Comment (RaigorJiang) [inline sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java:911]: Please put `null` to the left of the equals sign, thank you!

File: sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java [hunk 2]
```diff
@@ -907,7 +908,19 @@ public final ASTNode visitCastFunction(final CastFunctionContext ctx) {
...
-        result.getParameters().add((DataTypeSegment) visit(ctx.dataType()));
+        if (null != ctx.dataType()) {
+            result.getParameters().add((DataTypeSegment) visit(ctx.dataType()));
+        }
+        if (null != ctx.DATETIME()) {
+            DataTypeSegment dataType = new DataTypeSegment();
+            dataType.setDataTypeName(ctx.DATETIME().getText());
+            dataType.setStartIndex(ctx.DATETIME().getSymbol().getStartIndex());
+            dataType.setStopIndex(ctx.DATETIME().getSymbol().getStopIndex());
+            if (ctx.typeDatetimePrecision() != null) {
```
Comment (RaigorJiang) [inline sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java:919]: Same problem here.

**Review by RaigorJiang — APPROVED** [review]

**Comment by RaigorJiang** [comment]
@jiangtao69039 Merged, thank you~
