### PR TITLE
Condition value support is null

### LINKED ISSUE #27411: Unable to get null value in custom sharding algorithm
### Which version of ShardingSphere did you use?
Master.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy.

### Expected behavior
Can get null value and process it in custom sharding algorithm.

### Actual behavior
Can't.

### Reason analyze (If you can)
The route logic does not handle the `is null` condition, ignoring the condition.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```sql
-- Querying through the is null condition will result in full dataSource routing
select * from t_order where order_id is null;
```

### PR DESCRIPTION
**Pull request by FlyingZC**
Fixes #27411.
Changes proposed in this pull request:
  - Condition value support is null

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueCompareOperatorGenerator.java [hunk 1]
```diff
@@ -53,7 +53,9 @@ public final class ConditionValueCompareOperatorGenerator implements ConditionVa
     
     private static final String AT_LEAST = ">=";
     
-    private static final Collection<String> OPERATORS = new HashSet<>(Arrays.asList(EQUAL, GREATER_THAN, LESS_THAN, AT_LEAST, AT_MOST));
+    private static final String IS = "IS";
```
Comment (strongduanmu) [inline features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueCompareOperatorGenerator.java:56]: If user use `is`, can we support?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Comment by FlyingZC** [comment]
image

**Comment by FlyingZC** [comment]
image

**Review by strongduanmu — APPROVED** [review]
