### PR TITLE
checked binding table rule

### LINKED ISSUE #10417: Check whether the dropped table rules exist in the binding table rule in DropShardingTableRuleBackendHandler
Refer #9964

Just search `// TODO issue#10417` in class `DropShardingTableRuleBackendHandler .java`.

```
 1. get binding tables by getBindingTables()
 2. Check whether the dropped table rules exist in the binding table rule
 3. throw ShardingTableRulesInUsedException if exist
 4. refactor check() method to return void
 5. add UT  in DropShardingTableRuleBackendHandlerTest.java
```

### PR DESCRIPTION
**Pull request by totalo**
Fixes #10417.

### CODE REVIEW

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/rdl/impl/DropShardingTableRuleBackendHandler.java [hunk 1]
```diff
@@ -49,24 +49,23 @@ public DropShardingTableRuleBackendHandler(final DropShardingTableRuleStatement
...
+    private void check(final String schemaName, final Optional<ShardingRuleConfiguration> shardingRuleConfiguration, final Collection<String> tableNames) {
         if (!shardingRuleConfiguration.isPresent()) {
             throw new ShardingTableRuleNotExistedException(schemaName, tableNames);
         }
         Collection<String> shardingTableNames = getShardingTables(shardingRuleConfiguration.get());
-        Collection<String> notExistedTableNames = tableNames.stream().filter(each -> !shardingTableNames.contains(each)).collect(Collectors.toList());
-        if (!notExistedTableNames.isEmpty()) {
-            throw new ShardingTableRuleNotExistedException(schemaName, notExistedTableNames);
+        Collection<String> bindingTables = getBindingTables(shardingRuleConfiguration.get());
+        Collection<String> notSatisfiedTableNames = tableNames.stream().filter(each -> !shardingTableNames.contains(each) || bindingTables.contains(each)).collect(Collectors.toList());
```
Comment (menghaoranss) [inline shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/rdl/impl/DropShardingTableRuleBackendHandler.java:65]: 2. Check whether the dropped table rules exist in the binding table rule
 3. throw ShardingTableRulesInUsedException if exist

please check.

**Review by menghaoranss — CHANGES_REQUESTED** [review]

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/rdl/impl/DropShardingTableRuleBackendHandler.java (hunk 1 above)
Comment (totalo) [reply shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/rdl/impl/DropShardingTableRuleBackendHandler.java:65]: Sorry, my negligence, I misunderstood the exception name.i will fix it!

**Review by menghaoranss — APPROVED** [review]
