### PR TITLE
FIX issue #12077

### LINKED ISSUE #12077: Add test case for ContextManagerBuilderFactory

### PR DESCRIPTION
**Pull request by hoorf**
Fixes #12077

just unit test

### CODE REVIEW

File: shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerBuilderFactoryTest.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+import org.junit.runner.RunWith;
+import org.mockito.junit.MockitoJUnitRunner;
+
+import static org.hamcrest.CoreMatchers.instanceOf;
+import static org.junit.Assert.assertThat;
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.when;
+
+@RunWith(MockitoJUnitRunner.class)
+public class ContextManagerBuilderFactoryTest {
```
Comment (menghaoranss) [inline shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerBuilderFactoryTest.java:33]: Please keep all test classes as final.

**Review by menghaoranss — CHANGES_REQUESTED** [review]

**Review by menghaoranss — APPROVED** [review]
