### PR TITLE
Removes use of JAXB API via jackson-dataformat-xml

### LINKED ISSUE #26896: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
## Bug Report

```java  
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at org.apache.shardingsphere.mode.repository.standalone.jdbc.sql.JDBCRepositorySQLLoader.loadFromJar(JDBCRepositorySQLLoader.java:114)
	at org.apache.shardingsphere.mode.repository.standalone.jdbc.sql.JDBCRepositorySQLLoader.load(JDBCRepositorySQLLoader.java:72)
	at org.apache.shardingsphere.mode.repository.standalone.jdbc.JDBCRepository.init(JDBCRepository.java:59)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.findService(TypedSPILoader.java:86)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.findService(TypedSPILoader.java:70)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.getService(TypedSPILoader.java:127) 

Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

```

### Which version of ShardingSphere did you use?
ShardingSphere 5.4.0 + JDK 17

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### PR DESCRIPTION
**Pull request by linghengqian**
For #26041.

Changes proposed in this pull request:
  - Removes use of JAXB API via jackson-dataformat-xml. Reference https://github.com/apache/shardingsphere/issues/26041#issuecomment-1815891001 .
  - Getting rid of the JAXB API will make ShardingSphere JDBC Core work out of the box under Spring Boot OSS 3/Quarkus 3/Micronaut Framework 4/Helidon 3 with Jakarta EE 9+. The only limitation is XA distributed transactions. This will completely resolve #26896. Fixes #26896 .
  - I know there are quite a few breaking changes on Jackson 3.0. But the problems caused by https://github.com/FasterXML/jackson/wiki/Jackson-Release-3.0 appear to be much smaller than those caused by Jakarta EE 9. And Jackson 3.0 hasn't been released yet.
  - Revisiting #16863. I verified on OpenJDK 17.0.9 that `shardingsphere-transaction-xa-narayana` does not require JAXB at all.
  - Removes GraalVM Reachability Metadata for `org.glassfish.jaxb:jaxb-runtime:2.3.1` which is no longer needed. Passed the test of `./mvnw -PnativeTestInShardingSphere -T1C -e clean test`.
  - The reason I don't use xstream is because it requires a lot of json entries for the GraalVM Reachability Metadata.  Reference https://github.com/oracle/graalvm-reachability-metadata/issues/232.
  - Explicitly introduce `com.fasterxml.jackson.datatype:jackson-datatype-jdk8` to adapt to Jackson 2.16.0. Otherwise an error is thrown.
```shell
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.954 s <<< FAILURE! -- in org.apache.shardingsphere.data.pipeline.core.job.PipelineJobIdUtilsTest
[ERROR] org.apache.shardingsphere.data.pipeline.core.job.PipelineJobIdUtilsTest.assertParse -- Time elapsed: 0.869 s <<< ERROR!
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 optional type `java.util.Optional<java.lang.String>` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jdk8" to enable handling (through reference chain: org.apache.shardingsphere.data.pipeline.scenario.migration.MigrationJobId["jobType"]->org.apache.shardingsphere.data.pipeline.scenario.migration.MigrationJobType["toBeStartDisabledNextJobType"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1330)
        at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4793)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4038)
        at org.apache.shardingsphere.infra.util.json.JsonUtils.toJsonString(JsonUtils.java:61)
        at org.apache.shardingsphere.data.pipeline.core.job.id.PipelineJobId.marshalSuffix(PipelineJobId.java:54)
        at org.apache.shardingsphere.data.pipeline.core.job.id.PipelineJobIdUtils.marshal(PipelineJobIdUtils.java:52)
        at org.apache.shardingsphere.data.pipeline.core.job.PipelineJobIdUtilsTest.assertParse0(PipelineJobIdUtilsTest.java:44)
        at org.apache.shardingsphere.data.pipeline.core.job.PipelineJobIdUtilsTest.assertParse(PipelineJobIdUtilsTest.java:38)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [x] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQL.java [hunk 1]
```diff
@@ -17,43 +17,41 @@
...
 /**
  * JDBC repository SQL.
  */
-@XmlRootElement(name = "sql")
+@JacksonXmlRootElement(localName = "sql")
 @Getter
 public final class JDBCRepositorySQL {
     
-    @XmlAttribute(required = true)
+    @JacksonXmlProperty(isAttribute = true)
```
Comment (zhfeng) [inline mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQL.java:31]: We lost `required` here? Is there no such property with `JacksonXmlProperty`?

Comment (linghengqian) [reply mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQL.java:31]: - There is no direct equivalent.

 > Unfortunately XML is special: due to structure being what it is, empty Element looks either as "Object with no properties" or "empty String".

 - In https://github.com/FasterXML/jackson-dataformat-xml/issues/538, the Jaxkson maintainer has a different opinion on `required` than the JAXB API.  Should I use `@JsonProperty` to mark `required` and then set it as follows?
 ```java
 final XmlMapper xmlMapper = new XmlMapper();

 xmlMapper.configure(DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES, true);
 ```

**Review by terrymanu — APPROVED** [review]

File: mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQL.java (hunk 1 above)
Comment (linghengqian) [reply mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQL.java:31]: - I'm not sure how the JAXB API handles the `required` attribute. 

- In my local unit test, `jaxb-runtime` does not throw an exception for empty elements, but gets null values normally like `jackson-dataformat-xml`. `required` seems to be just for IDE censorship.

Comment (zhfeng) [reply mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQL.java:31]: OK, I see. It could be better to open an issue since we need more investigation.

Comment (linghengqian) [reply mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQL.java:31]: > OK, I see. It could be better to open an issue since we need more investigation.

- I opened https://github.com/FasterXML/jackson-dataformat-xml/issues/625 . 
- A PR for testing is at #29577 .
