### PR TITLE
Fix #6408 :  Cannot find JDBC type '2003' in PostgreSQL column type

### LINKED ISSUE #6408: Cannot find JDBC type '2003' in PostgreSQL column type
SELECT d.oid, d.datname AS databasename, d.datacl, pg_get_userbyid(d.datdba) AS databaseowner, d.datcollate, d.datctype, shobj_description(d.oid, 'pg_database') AS description, d.datconnlimit, t.spcname, d.encoding, pg_encoding_to_char(d.encoding) AS encodingname FROM pg_database d LEFT JOIN pg_tablespace t ON d.dattablespace = t.oid ::: DataSources: initds_master
[ERROR] 02:51:14.421 [pool-4-thread-1] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.IllegalArgumentException: Cannot find JDBC type '2003' in PostgreSQL column type

### PR DESCRIPTION
**Pull request by sandynz**
Fixes #6408.

Changes proposed in this pull request:
- ShardingSphere-Proxy querying support PostgreSQL array type

### CODE REVIEW

**Comment by tristaZero** [comment]
@sandynz Thanks for your PR, @tuohai666 will give it a review soon!

File: shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLColumnTypeNameOidMappings.java [hunk 1]
```diff
@@ -0,0 +1,475 @@
...
+            + "user_mapping_options\t13298\n"
+            + "user_mappings\t13302\n"
+            + "array_tc_0\t16426\n"
+            + "_array_tc_0\t16425\n"
+            + "pg_toast_16424\t16428\n"
+            + "array_tc_1\t16434\n"
+            + "_array_tc_1\t16433\n"
+            + "pg_toast_16432\t16436";
+
+    private static final Map<String, Integer> COLUMN_TYPE_NAME_OID_MAP;
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLColumnTypeNameOidMappings.java:449]: COLUMN_TYPE_NAME_OID_MAP can be assigned here. And the loadFactor 1 is enough.

File: shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLColumnTypeNameOidMappings.java [hunk 2]
```diff
@@ -0,0 +1,475 @@
...
+
+    /**
+     * Get type oid by database-specific column type name.
+     *
+     * @param columnTypeName PostgreSQL column type name, e.g. <code>int4</code>
+     * @return type oid, e.g. <code>23</code> for <code>int4</code>
+     * @throws IllegalArgumentException if no type oid could be found
+     */
+    public static int getTypeOidByColumnTypeName(final String columnTypeName) throws IllegalArgumentException {
+        Integer oid = COLUMN_TYPE_NAME_OID_MAP.get(columnTypeName);
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLColumnTypeNameOidMappings.java:468]: Please reference codes:
```
    public static PostgreSQLColumnType valueOfJDBCType(final int jdbcType) {
        if (JDBC_TYPE_AND_COLUMN_TYPE_MAP.containsKey(jdbcType)) {
            return JDBC_TYPE_AND_COLUMN_TYPE_MAP.get(jdbcType);
        }
        throw new IllegalArgumentException(String.format("Cannot find JDBC type '%s' in PostgreSQL column type", jdbcType));
    }
```

File: shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java [hunk 3]
```diff
@@ -40,10 +47,22 @@
     
     private final int dataFormat = 0;
     
-    public PostgreSQLColumnDescription(final String columnName, final int columnIndex, final int columnType, final int columnLength) {
+    public PostgreSQLColumnDescription(final String columnName, final int columnIndex, final int columnType, final int columnLength, final ResultSetMetaData resultSetMetaData) {
         this.columnName = columnName;
         this.columnIndex = columnIndex;
-        this.typeOID = PostgreSQLColumnType.valueOfJDBCType(columnType).getValue();
+        if (Types.ARRAY == columnType && resultSetMetaData != null) {
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java:53]: null != resultSetMetaData

File: shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java [hunk 4]
```diff
@@ -40,10 +47,22 @@
...
+            String columnTypeName = null;
+            try {
+                columnTypeName = resultSetMetaData.getColumnTypeName(columnIndex);
+            } catch (SQLException e) {
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java:57]: **final** Exception **ex**

File: shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java [hunk 5]
```diff
@@ -40,10 +47,22 @@
...
+                if (ThreadLocalRandom.current().nextInt(10) == 6) {
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java:58]: What is this for?

File: shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/QueryResult.java [hunk 6]
```diff
@@ -18,14 +18,22 @@
...
 /**
  * Query result form SQL.
  */
 public interface QueryResult {
-    
+
+    /**
+     * Get JDBC ResultSetMetaData.
+     *
+     * @return {@linkplain ResultSetMetaData}
```
Comment (tuohai666) [inline shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/QueryResult.java:33]: return a plain String

File: shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLColumnTypeNameOidMappingsTest.java [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+import org.junit.Test;
+
+import static org.junit.Assert.assertEquals;
+
+public class PostgreSQLColumnTypeNameOidMappingsTest {
+    
+    @Test
+    public void assertIntegerArrayGot() {
+        int columnTypeName = PostgreSQLColumnTypeNameOidMappings.getTypeOidByColumnTypeName("_int4");
+        assertEquals(1007, columnTypeName);
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLColumnTypeNameOidMappingsTest.java:29]: For single parameter asserts, assertTrue, assertFalse, assertNull and assertNotNull should be used.
For multiple parameter asserts, assertThat should be used.

File: shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescriptionTest.java [hunk 8]
```diff
@@ -0,0 +1,43 @@
...
+import org.junit.Assert;
+import org.junit.Test;
+import org.mockito.Mockito;
+
+public class PostgreSQLColumnDescriptionTest {
+    
+    @Test
+    public void assertIntegerTypeOid() {
+        PostgreSQLColumnDescription description = new PostgreSQLColumnDescription("age", 1, Types.INTEGER, 4, null);
+        Assert.assertEquals(23, description.getTypeOID());
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescriptionTest.java:32]: Don't use Assert.

For single parameter asserts, assertTrue, assertFalse, assertNull and assertNotNull should be used.
For multiple parameter asserts, assertThat should be used.

File: shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescriptionTest.java [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+    }
+    
+    @Test
+    public void assertIntegerArrayTypeOid() throws SQLException {
+        ResultSetMetaData resultSetMetaData = Mockito.mock(ResultSetMetaData.class);
+        Mockito.when(resultSetMetaData.getColumnTypeName(2)).thenReturn("_int4");
+        PostgreSQLColumnDescription description = new PostgreSQLColumnDescription("ages", 2, Types.ARRAY, 12, resultSetMetaData);
+        Assert.assertEquals(1007, description.getTypeOID());
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescriptionTest.java:40]: For single parameter asserts, assertTrue, assertFalse, assertNull and assertNotNull should be used.
For multiple parameter asserts, assertThat should be used.

File: shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java (hunk 5 above)
Comment (sandynz) [reply shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java:58]: Reduce log if exception thrown always. It will be removed, it should not occur.
