### PR TITLE
Fix federated query LocalDateTime conversion

### LINKED ISSUE #30764: MySQL max() in nested subquery fails
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

Tested in v5.41 and v5.4.2-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Expected to return a list of recent chat_messages 
### Actual behavior

In 5.41: `General error: 30000 Unknown exception: Cannot convert 2022-09-14T18:25:06 to long`
In 5.4.2-SNAPSHOT: `SQL federation doesn't support SQL`

### Reason analyze (If you can)

It looks like the MAX(created_at) isn't working correctly, and instead of showing the max DATETIME, it's trying to convert it to LONG.

One thing to note is that if I run the subquery by itself, it works fine.. it's only with it in the subquery that seems to be a problem:

```
SELECT
    ->     MAX(id) max_id,
    ->     chat_id,
    ->     MAX(created_at) created_at
    ->   FROM chats_messages
    ->   GROUP BY chat_id;
+--------+---------+---------------------+
| max_id | chat_id | created_at          |
+--------+---------+---------------------+
|      1 |       1 | 2022-09-14 18:25:06 |
|      2 |       2 | 2022-09-15 21:37:17 |
|     32 |       3 | 2022-10-26 09:06:24 |
|     34 |       4 | 2022-10-26 14:41:22 |
|      9 |       5 | 2022-09-16 19:18:45 |
|     11 |       6 | 2022-09-26 09:11:29 |
|     12 |       7 | 2022-09-30 19:05:20 |
|     13 |       8 | 2022-10-07 16:40:07 |
```

this works fine

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

This is the query:
```
SELECT
  members.chat_id,
  mess_max.created_at message_sent
FROM chats_members members 
JOIN (
  SELECT
    MAX(id) max_id,
    chat_id,
    MAX(created_at) created_at
  FROM chats_messages
  GROUP BY chat_id
) mess_max on mess_max.chat_id = members.chat_id
LEFT JOIN chats_messages_read_by_recipient is_read
  ON mess_max.max_id = is_read.chat_message_id AND is_read.created_by = 5094
WHERE (members.user_id = 5094 OR members.group_id IN('13'))
  AND is_read.id IS NULL;
```

### PR DESCRIPTION
**Pull request by zihaoAK47**
Fixes #30764.

Changes proposed in this pull request:
  - Fix federated query LocalDateTime conversion

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerator/JDBCRowEnumerator.java [hunk 1]
```diff
@@ -64,11 +67,16 @@ private boolean moveNext0() throws SQLException {
     private void setCurrentRow() throws SQLException {
         Object[] rowValues = new Object[metaData.getColumnCount()];
         for (int i = 0; i < metaData.getColumnCount(); i++) {
-            rowValues[i] = queryResult.getValue(i + 1, Object.class);
+            rowValues[i] = getValue(i);
         }
         this.currentRow = 1 == metaData.getColumnCount() ? rowValues[0] : rowValues;
     }
     
+    private Object getValue(final int index) throws SQLException {
```
Comment (strongduanmu) [inline kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerator/JDBCRowEnumerator.java:75]: Can you add e2e test for this convert logic?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerator/JDBCRowEnumerator.java (hunk 1 above)
Comment (zihaoAK47) [reply kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerator/JDBCRowEnumerator.java:75]: Hi mentor, there is no field related to `datetime` in the e2e standard table.

Comment (strongduanmu) [reply kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerator/JDBCRowEnumerator.java:75]: Thank you for your feedback, we could consider add a e2e test table which contains all data type.

**Review by strongduanmu — APPROVED** [review]
