### PR TITLE
convert object to string  before set properties to SPI instance

### LINKED ISSUE #8204: Properties with integer can't affect in yaml config
1. docker image use docker hub tag latest,  MAINTAINER apache
2. add config-sharding.yaml  and server.yaml to /opt/sharding-proxy/conf
3. docker run  and throw an error 
Exception in thread "main" java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.apache.shardingsphere.sharding.algorithm.sharding.mod.HashModShardingAlgorithm.getShardingCount(HashModShardingAlgorithm.java:52)
	at org.apache.shardingsphere.sharding.algorithm.sharding.mod.HashModShardingAlgorithm.init(HashModShardingAlgorithm.java:47)
	at org.apache.shardingsphere.infra.config.algorithm.ShardingSphereAlgorithmFactory.createAlgorithm(ShardingSphereAlgorithmFactory.java:43)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.lambda$new$0(ShardingRule.java:89)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.apache.shardingsphere.sharding.rule.ShardingRule.<init>(ShardingRule.java:89)
	at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:34)
	at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:30)
	at org.apache.shardingsphere.infra.rule.ShardingSphereRulesBuilder.lambda$build$0(ShardingSphereRulesBuilder.java:49)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.shardingsphere.infra.rule.ShardingSphereRulesBuilder.build(ShardingSphereRulesBuilder.java:49)
	at org.apache.shardingsphere.infra.context.schema.SchemaContextsBuilder.createSchema(SchemaContextsBuilder.java:101)
	at org.apache.shardingsphere.infra.context.schema.SchemaContextsBuilder.build(SchemaContextsBuilder.java:93)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.createSchemaContexts(AbstractBootstrapInitializer.java:75)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:63)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:48)

### PR DESCRIPTION
**Pull request by kimmking**
Fixes #8204.

Changes proposed in this pull request:
- convert object to string  before set properties to SPI instance

### CODE REVIEW

File: shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/spi/typed/TypedSPIRegistry.java [hunk 1]
```diff
@@ -64,4 +64,12 @@
         }
         throw new ServiceProviderNotFoundException(typedSPIClass);
     }
+    
+    private static <T extends TypedSPI> void convertPropertiesValueType(final Properties props, final T result) {
```
Comment (terrymanu) [inline shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/spi/typed/TypedSPIRegistry.java:68]: input param should not name as `result`

**Review by terrymanu — CHANGES_REQUESTED** [review]

**Review by terrymanu — APPROVED** [review]
