### PR TITLE
Shardingsphere-proxy fails to establish a connection when it proxies multiple versions of mysql databases

### LINKED ISSUE #16735: Shardingsphere-proxy fails to establish a connection when it proxies multiple versions of mysql databases
Shardingsphere proxy version 5.0.0.

Shardingsphere-proxy proxies 2 mysql servers, mysql 5.6 and 5.7.

The mysql driver version used by the application is  8.0.13,Now select version() result is 5.7.34-log-ShardingSphere-Proxy 5.

The application fails to establish a connection, Exception is:
```
java.sql.SQLException: Could not map transaction isolation '1' to a valid JDBC level.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ConnectionImpl.getTransactionIsolation(ConnectionImpl.java:1229)
	at com.zaxxer.hikari.pool.PoolBase.checkDefaultIsolation(PoolBase.java:479)
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:442)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:410)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at com.lixiang.proxy.test.ProxyJDBCTest.main(ProxyJDBCTest.java:28)
```

The reason is that mysql needs to query the isolation level of the database after establishing a connection, Mysql5.6 does not support transaction_isolation syntax。

[`transaction_isolation was added in MySQL 5.7.20 as an alias for tx_isolation, which is now deprecated and is removed in MySQL 8.0. Applications should be adjusted to use transaction_isolation in preference to tx_isolation.`](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_tx_isolation)

I think the correct way is to return the corresponding mysql version。

I'm fixing this problem and need a little help。

### PR DESCRIPTION
**Pull request by lwclover**
Fixes #16735.

### CODE REVIEW

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java [hunk 1]
```diff
@@ -34,27 +38,38 @@ public final class MySQLServerInfo {
...
      * Set server version.
-     *
+     * 
+     * @param schemaName schema name
      * @param serverVersion server version
      */
-    public static synchronized void setServerVersion(final String serverVersion) {
-        MySQLServerInfo.serverVersion = null == serverVersion ? null : String.format(SERVER_VERSION_PATTERN, serverVersion, CommonConstants.PROXY_VERSION.get());
+    public static void setServerVersion(final String schemaName, final String serverVersion) {
+        serverVersions.put(schemaName, String.format(SERVER_VERSION_PATTERN, serverVersion, CommonConstants.PROXY_VERSION.get()));
```
Comment (TeslaCN) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:54]: A connection may have no schema name before client executing `use database`, this may cause NPE.

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java [hunk 2]
```diff
@@ -34,27 +38,38 @@ public final class MySQLServerInfo {
     
     public static final MySQLCharacterSet DEFAULT_CHARSET = MySQLCharacterSet.UTF8MB4_GENERAL_CI;
     
-    private static final String DEFAULT_MYSQL_VERSION = "5.7.22";
+    private static final String DEFAULT_MYSQL_VERSION = "5.6.23";
     
     private static final String SERVER_VERSION_PATTERN = "%s-ShardingSphere-Proxy %s";
     
-    private static volatile String serverVersion;
+    private static Map<String, String> serverVersions = new ConcurrentHashMap<>();
```
Comment (TeslaCN) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:45]: Consider making this final.

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java [hunk 3]
```diff
@@ -28,9 +28,9 @@
 public enum TransactionIsolationLevel {
 
     NONE("NONE"),
-    READ_UNCOMMITTED("READ_UNCOMMITTED"),
```
Comment (TeslaCN) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java:31]: Are these changes related to the issue?

**Review by TeslaCN — CHANGES_REQUESTED** [review]

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java (hunk 3 above)
Comment (lwclover) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java:31]: Keep it the same as the real database value

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java [hunk 4]
```diff
@@ -34,27 +38,38 @@ public final class MySQLServerInfo {
     
     public static final MySQLCharacterSet DEFAULT_CHARSET = MySQLCharacterSet.UTF8MB4_GENERAL_CI;
     
-    private static final String DEFAULT_MYSQL_VERSION = "5.7.22";
+    private static final String DEFAULT_MYSQL_VERSION = "5.6.23";
```
[the remark this answers is not in the document]
Comment (lwclover) [reply shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:41]: Add a proxy prop to solve it.

**Review by TeslaCN — APPROVED** [review]
LGTM

**Comment by lwclover** [comment]
> I understand the proposal of this PR. It is a good idea for keep different logic schema with different database versions, but it is best not change the default value.
> 
> My suggestion:
> 
> 1. It is correct if the configured data sources already existed in ShardingSphere, whatever the default version;
> 2. It is incorrect for empty ShardingSphere, and add data source with MySQL 5.6.x in runtime.
> 
> So, how about refresh the database version after the first data source added?

I will add a proxy props.

**Review by strongduanmu — APPROVED** [review]

**Review by terrymanu — APPROVED** [review]
