### PR TITLE
fix bug for ClassCastException when execute range query with different numeric type

### LINKED ISSUE #5544: Range from 0 to more than Integer.MAX_VALUE occur exception
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-proxy
### Expected behavior
query success
### Actual behavior
throw exception
image
image

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
query data range from 0 to 3147483647 （more than Integer.MAX_VALUE）
#### config-xxx.yaml
```yaml
schemaName: databasemanager

dataSources:
  ds_0:
    url: jdbc:mysql://192.168.137.102:3306/databasemanager?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://192.168.137.102:3307/databasemanager?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    t_cluster:
      actualDataNodes: ds_${0..1}.t_cluster
      tableStrategy:
        none:
      databaseStrategy:
        complex:
          shardingColumns: clusterId
          algorithmClassName: org.apache.shardingsphere.shardingproxy.algorithm.complex.AutoPartitionByLong
    t_cluster_instance:
      actualDataNodes: ds_${0..1}.t_cluster_instance
      tableStrategy:
        none:
      databaseStrategy:
        inline:
          shardingColumn: clusterId
          algorithmExpression: ds_${clusterId.hashCode().abs() % 2}
  bindingTables:
    - t_cluster,t_cluster_instance
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:


```

#### table
```sql
create table `t_cluster` (
	`clusterId` bigint (20),
	`clusterName` varchar (384),
	`projectId` varchar (192),
	`createTime` datetime ,
	`updateTime` datetime 
); 
```

#### execute sql
```sql
select * from t_cluster t where  t.clusterId > 3 and t.clusterId < 3147483647
```

### PR DESCRIPTION
**Pull request by strongduanmu**
Fixes #5544 .

Changes proposed in this pull request:
- fix ClassCastException when execute range query with different numeric type like `t.clusterId > 3 and t.clusterId < 3147483647 and t.clusterId in (1, 2, 4)`
- fix ClassCastException when execute range query with different numeric type like `t.clusterId between 3 and 3147483647`

### CODE REVIEW

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/util/SafeRangeOperationUtils.java [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+ */
+@AllArgsConstructor(access = AccessLevel.PRIVATE)
+public final class SafeRangeOperationUtils {
+
+    /**
+     * Execute intersection method by safe mode.
+     *
+     * @param range          range
+     * @param connectedRange connected range
+     * @return the intersection result of two ranges
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/util/SafeRangeOperationUtils.java:45]: Please do not format java doc, just keep one space with `@aparam` and `@return`

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/util/SafeRangeOperationUtils.java [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+ * Safe range operation utility class.
+ */
+@AllArgsConstructor(access = AccessLevel.PRIVATE)
+public final class SafeRangeOperationUtils {
+
+    /**
+     * Execute intersection method by safe mode.
+     *
+     * @param range          range
+     * @param connectedRange connected range
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/util/SafeRangeOperationUtils.java:44]: What's mean of variable name `connectedRange`?

Comment (strongduanmu) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/util/SafeRangeOperationUtils.java:44]: > What's mean of variable name `connectedRange`?

In order to consistent with the intersection method in Guava Range. The following is the definition of the intersection method:

```java
/**
* Returns the maximal range {@linkplain #encloses enclosed} by both this range and {@code
* connectedRange}, if such a range exists.
*
* <p>For example, the intersection of {@code [1..5]} and {@code (3..7)} is {@code (3..5]}. The
* resulting range may be empty; for example, {@code [1..5)} intersected with {@code [5..7)}
* yields the empty range {@code [5..5)}.
*
* <p>The intersection exists if and only if the two ranges are {@linkplain #isConnected
* connected}.
*
* <p>The intersection operation is commutative, associative and idempotent, and its identity
* element is {@link Range#all}).
*
* @throws IllegalArgumentException if {@code isConnected(connectedRange)} is {@code false}
*/
public Range<C> intersection(Range<C> connectedRange) {
    int lowerCmp = lowerBound.compareTo(connectedRange.lowerBound);
    int upperCmp = upperBound.compareTo(connectedRange.upperBound);
    if (lowerCmp >= 0 && upperCmp <= 0) {
        return this;
    } else if (lowerCmp <= 0 && upperCmp >= 0) {
        return connectedRange;
    } else {
        Cut<C> newLower = (lowerCmp >= 0) ? lowerBound : connectedRange.lowerBound;
        Cut<C> newUpper = (upperCmp <= 0) ? upperBound : connectedRange.upperBound;
        return create(newLower, newUpper);
    }
}
```

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/util/SafeRangeOperationUtils.java (hunk 1 above)
Comment (strongduanmu) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/util/SafeRangeOperationUtils.java:45]: > Please do not format java doc, just keep one space with `@aparam` and `@return`

Thank you! I got it, and I will modify it. 😀

**Comment by tristaZero** [comment]
Hi @strongduanmu 

I reviewed your PR, whose core logic is spotless, and tests are enough. I believe you worked hard for it. But I also wonder what you said here.

> BTW, I also tried the first solution, and all returned BigInteger types, which would cause many existing unit tests to report errors, so I still prefer the second method.

Could you post the exception here? Therefore we can judge whether the fist solution is practical or not. 

Currently, your PR provides a great implementation of the second one. But actually, the reason why the first solution draws my attention is that it looks so simple and free from any other utils (Not sure).  :)

**Comment by strongduanmu** [comment]
Hi, @tristaZero , the following is the error that appears when I execute the `mvn clean install -Prelease` command: 
```
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatementTest
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.23 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatementTest
[ERROR] assertQueryWithEmptyString(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatementTest)  Time elapsed: 0.06 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertExecuteUpdateGetResultSet(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatementTest)  Time elapsed: 0.008 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetGeneratedKeys(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatementTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertExecuteGetResultSet(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatementTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertQueryWithNull(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatementTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest
[ERROR] Tests run: 14, Failures: 0, Errors: 12, Skipped: 2, Time elapsed: 0.2 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest
[ERROR] assertClearBatch(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertQueryWithEmptyString(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.014 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertAddBatch(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertInitPreparedStatementExecutorWithReplayMethod(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertAddBatchWithGenerateKeyColumn(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertAddBatchWithoutGenerateKeyColumn(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.008 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertExecuteUpdateGetResultSet(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.008 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertExecuteGetResultSet(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertQueryWithNull(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetParameterMetaData(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertUpdateBatch(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.008 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertAddOnDuplicateKey(org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatementTest)  Time elapsed: 0.008 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.MasterSlavePreparedStatementTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.085 s - in org.apache.shardingsphere.driver.jdbc.core.statement.MasterSlavePreparedStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ShadowStatementTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.188 s - in org.apache.shardingsphere.driver.jdbc.core.statement.ShadowStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.EncryptStatementTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.272 s - in org.apache.shardingsphere.driver.jdbc.core.statement.EncryptStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.core.statement.ShadowPreparedStatementTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.129 s - in org.apache.shardingsphere.driver.jdbc.core.statement.ShadowPreparedStatementTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationDataSourceTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.063 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationDataSourceTest
[ERROR] assertGetLoginTimeout(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationDataSourceTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetLoginTimeout(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationDataSourceTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest
[ERROR] Tests run: 10, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 0.1 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest
[ERROR] assertSetNString(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetMetaData(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetRef(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetNCharacterStreamWithLength(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetNCharacterStream(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetArray(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetNClob(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetRowId(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetNClobForReader(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetNClobForReaderAndLength(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationPreparedStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest
[ERROR] Tests run: 8, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.089 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest
[ERROR] assertSetFetchDirection(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertClearBatch(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertAddBatch(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertIsCloseOnCompletion(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertCloseOnCompletion(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetFetchDirection(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertExecuteBatch(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetCursorName(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationStatementTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnSupportedDatabaseMetaDataResultSetTest
[INFO] Tests run: 33, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnSupportedDatabaseMetaDataResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest
[ERROR] Tests run: 8, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.089 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest
[ERROR] assertGetParameterClassName(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertIsSigned(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetPrecision(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertIsNullable(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetParameterTypeName(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetScale(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetParameterMode(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetParameterType(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationParameterMetaTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest
[ERROR] Tests run: 28, Failures: 0, Errors: 28, Skipped: 0, Time elapsed: 0.162 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest
[ERROR] assertCreateSQLXML(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertCreateStruct(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetCatalog(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetClientInfoWithName(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetSavepoint(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertReleaseSavepoint(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetClientInfoWithProperties(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetTypeMap(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertRollback(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertNativeSQL(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertIsValid(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertCreateBlob(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertCreateClob(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertAbort(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetCatalog(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertPrepareCall(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetNetworkTimeout(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetClientInfo(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetTypeMap(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertPrepareCallWithResultSetTypeAndResultSetConcurrencyAndResultSetHoldability(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetSchema(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetSchema(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetSavepointWithName(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertCreateNClob(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertCreateArrayOf(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertSetClientInfo(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetNetworkTimeout(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertPrepareCallWithResultSetTypeAndResultSetConcurrency(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedGeneratedKeysResultSetTest
[INFO] Tests run: 38, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedGeneratedKeysResultSetTest
[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest
[ERROR] Tests run: 40, Failures: 0, Errors: 40, Skipped: 0, Time elapsed: 0.178 s <<< FAILURE! - in org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest
[ERROR] assertPrevious(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertRefreshRow(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertUpdateRow(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertObjectForColumnLabelWithType(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertRowInserted(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetRow(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertIsLast(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertRelative(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertRowDeleted(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetRowIdForColumnIndex(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetRowIdForColumnLabel(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetCursorName(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertIsAfterLast(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertMoveToInsertRow(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetRefForColumnIndex(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetRefForColumnLabel(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertIsFirst(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertInsertRow(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertDeleteRow(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertFirst(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetNClobForColumnIndex(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetNClobForColumnLabel(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertBeforeFirst(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertMoveToCurrentRow(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] getNStringForColumnIndex(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] getNStringForColumnLabel(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] getNCharacterStreamForColumnIndex(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] getNCharacterStreamForColumnLabel(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertObjectForColumnLabelWithMap(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertCancelRowUpdates(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertAbsolute(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetHoldability(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertAfterLast(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertIsBeforeFirst(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertObjectForColumnIndexWithType(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertRowUpdated(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetArrayForColumnIndex(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertGetArrayForColumnLabel(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertLast(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[ERROR] assertObjectForColumnIndexWithMap(org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedOperationResultSetTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer

[INFO] Running org.apache.shardingsphere.driver.jdbc.unsupported.UnsupportedUpdateOperationResultSetTest
```
The above error message is that BigInteger cannot be converted to Long or Integer type, because the Long or Integer type supports mod operation(%). the following is a typical error scenario, `shardingValue.getValue()` will always return BigInteger type value:
```java
@Override
public String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Integer> shardingValue) {
    for (String each : availableTargetNames) {
        if (each.endsWith(String.valueOf(shardingValue.getValue() % 2))) {
            return each;
        }
    }
    return null;
}
```

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-route/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueBetweenOperatorGeneratorTest.java [hunk 3]
```diff
@@ -36,11 +37,11 @@
 import static org.junit.Assert.assertTrue;
 
 public final class ConditionValueBetweenOperatorGeneratorTest {
-    
+
```
Comment (tristaZero) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-route/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueBetweenOperatorGeneratorTest.java:40]: A newline is supposed to start with 4 blank spaces. Just a little issue of check style. Apart from that, I approved. Thanks for the clean coding!

**Comment by tristaZero** [comment]
Hi @strongduanmu 
Sorry for the late response. Some of the meetings blocked me.
Anyway, I appreciated your initiative to solve the issue from the community! 
Looking forward to your standout in the community. :-)

**Comment by strongduanmu** [comment]
@tristaZero Thanks for your encouragement, I will continue to work hard to participate in the community. 😀
