### PR TITLE
fix #8696 and adjust 'set' grammar

### LINKED ISSUE #8696: SQL Format error
## Bug Report
```
SELECT @@SESSION.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
```
this sql format error.
### Which version of ShardingSphere did you use?

master branch

### Expected behavior

```
SELECT @@SESSION.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, 
	@@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, 
	@@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, 
	@@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, 
	@@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, 
	@@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, 
	@@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
```

### Actual behavior

```
SELECT @ @ SESSION . auto_increment_increment AS auto_increment_increment, @ @ character_set_client AS character_set_client, @ @ character_set_connection AS character_set_connection, 
	@ @ character_set_results AS character_set_results, @ @ character_set_server AS character_set_server, @ @ collation_server AS collation_server, 
	@ @ collation_connection AS collation_connection, @ @ init_connect AS init_connect, @ @ interactive_timeout AS interactive_timeout, 
	@ @ license AS license, @ @ lower_case_table_names AS lower_case_table_names, @ @ max_allowed_packet AS max_allowed_packet, 
	@ @ net_buffer_length AS net_buffer_length, @ @ net_write_timeout AS net_write_timeout, @ @ query_cache_size AS query_cache_size, 
	@ @ query_cache_type AS query_cache_type, @ @ sql_mode AS sql_mode, @ @ system_time_zone AS system_time_zone, 
	@ @ time_zone AS time_zone, @ @ tx_isolation AS transaction_isolation, @ @ wait_timeout AS wait_timeout
```

### PR DESCRIPTION
**Pull request by jingshanglu**
Fixes #8696 .

Changes proposed in this pull request:
- fix format for variable.
- adjust set grammar.

### CODE REVIEW

File: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLTCLStatementSQLVisitor.java [hunk 1]
```diff
@@ -55,40 +53,30 @@ public MySQLTCLStatementSQLVisitor(final Properties props) {
...
-    @Override
-    public ASTNode visitAutoCommitValue(final AutoCommitValueContext ctx) {
+
+    private AutoCommitSegment generateAutoCommitSegment(final Token ctx) {
         boolean autoCommit = "1".equals(ctx.getText()) || "ON".equals(ctx.getText());
-        return new AutoCommitSegment(ctx.getStart().getStartIndex(), ctx.getStop().getStopIndex(), autoCommit);
+        return new AutoCommitSegment(ctx.getStartIndex(), ctx.getStopIndex(), autoCommit);
     }
-    
+
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLTCLStatementSQLVisitor.java:79]: Please do not change original indent

**Review by terrymanu — CHANGES_REQUESTED** [review]

File: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLTCLStatementSQLVisitor.java (hunk 1 above)
Comment (jingshanglu) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLTCLStatementSQLVisitor.java]: OK

**Review by terrymanu — APPROVED** [review]
