### PR TITLE
replacing the TreeMap with CaseInsensitiveMap.(#28602)

### LINKED ISSUE #28602: Consider replacing the low-performance TreeMap with a more efficient data structure that supports case-insensitive ordering.
Based on the JMH test, the CaseInsensitiveMap in Apache Commons Collections demonstrates higher performance.
## JMH test code
```java
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Warmup(iterations = 5, time = 1)
@Measurement(iterations = 5, time = 1)
@Fork(3)
@State(Scope.Benchmark)
public class CaseInsensitiveMapBenchmarkRunner {
    public static void main(String[] args) throws IOException {
        org.openjdk.jmh.Main.main(args);
    }
    
    private Map<String, String> hashmap;
    private Map<String, String> caseInsensitiveMap;
    private Map<String, String> treeMap;
    private Collection<String> params;
    @Param({"10","100","1000","10000","100000"})
    private int size;
    
    @Setup(Level.Trial)
    public void setUp() {
        hashmap = new HashMap<>();
        caseInsensitiveMap = new CaseInsensitiveMap<>();
        treeMap = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        params = new ArrayList<>();
        Instancio.of(String.class).stream().limit(size).forEach(s -> {
            hashmap.put(s.toLowerCase(), s);
            caseInsensitiveMap.put(s, s);
            treeMap.put(s, s);
            params.add(s);
        });
    }
    
    @Benchmark
    public void hashmap(Blackhole blackhole) {
        params.forEach(s -> blackhole.consume(hashmap.get(s.toLowerCase())));
    }
    
    @Benchmark
    public void caseInsensitiveMap(Blackhole blackhole) {
        params.forEach(s -> blackhole.consume(caseInsensitiveMap.get(s)));
    }
    
    @Benchmark
    public void treemap(Blackhole blackhole) {
        params.forEach(s -> blackhole.consume(treeMap.get(s)));
    }
    
}
``` 
image

### PR DESCRIPTION
**Pull request by iamhucong**
Fixes #28602.

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java [hunk 1]
```diff
@@ -56,6 +56,13 @@ public final class TablesContext {
     
     private final Collection<SimpleTableSegment> simpleTableSegments = new LinkedList<>();
     
+    /**
+     * -- GETTER --
```
Comment (strongduanmu) [inline infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java:60]: Please remove this comment——`-- GETTER --`.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Review by strongduanmu — APPROVED** [review]
