### PR TITLE
Fix the sharding table skip OnDuplicatedKeyUpdate

### LINKED ISSUE #17198: In the case of sub-tables, if the sql contains on duplicate key update, it will cause an error in the actually generated sql
**Bug Report**
Which version of ShardingSphere did you use?
5.0.0

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
[insert into t_pipeline_info (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info.PIPELINE_DESC = ?]
can be converted into
[insert into t_pipeline_info_0 (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info_0.PIPELINE_DESC = ?]

Actual behavior
converted to [insert into **t_pipeline_info_0** (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update **t_pipeline_info**.PIPELINE_DESC = ?]

**The error message is as follows:**
2022-04-29 11:45:55.634|biz-6f32770874f04555a58353f335304281||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] Logic SQL: insert into t_pipeline_info (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info.PIPELINE_DESC = ?
2022-04-29 11:45:55.634|biz-6f32770874f04555a58353f335304281||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] SQLStatement: MySQLInsertStatement(setAssignment=Optional.empty, onDuplicateKeyColumns=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.column.OnDuplicateKeyColumnsSegment@4e2038b4])
2022-04-29 11:45:55.634|biz-6f32770874f04555a58353f335304281||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] Actual SQL: ds_0 ::: insert into t_pipeline_info_0 (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info.PIPELINE_DESC = ? ::: [p-17bd8ac017dsfsd1f, devops0, bnmvvv123dsfdf, 232323yui, 232323yui]
2022-04-29 11:45:55.669|biz-6f32770874f04555a58353f335304281||RuntimeExceptionMapper.kt|47|ERROR||||||[XNIO-1 task-1] Failed with runtime exception org.jooq.exception.DataAccessException: SQL [insert into t_pipeline_info (PIPELINE_ID, PROJECT_ID, PIPELINE_NAME, PIPELINE_DESC) values (?, ?, ?, ?) on duplicate key update t_pipeline_info.PIPELINE_DESC = ?]; Unknown column 't_pipeline_info.PIPELINE_DESC' in 'field list'
at org.jooq_3.14.7.MYSQL.debug(Unknown Source)
at org.jooq.impl.Tools.translate(Tools.java:2880)

### PR DESCRIPTION
**Pull request by cheese8**
Fixes #17198.

Changes proposed in this pull request:

### CODE REVIEW

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java [hunk 1]
```diff
@@ -217,11 +219,23 @@ public void extractTablesFromInsert(final InsertStatement insertStatement) {
                 extractTablesFromExpression(each);
             }
         }
+        if (insertStatement instanceof MySQLInsertStatement) {
```
Comment (strongduanmu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java:222]: @cheese8 Please use InsertStatementHandler to handle this logic.

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java [hunk 2]
```diff
@@ -217,11 +219,23 @@ public void extractTablesFromInsert(final InsertStatement insertStatement) {
...
+            ((MySQLInsertStatement) insertStatement).getOnDuplicateKeyColumns().ifPresent(each -> extractTablesFromAssignmentItems(each.getColumns()));
+        }
         if (insertStatement.getInsertSelect().isPresent()) {
             extractTablesFromSelect(insertStatement.getInsertSelect().get().getSelect());
         }
     }
     
+    private void extractTablesFromAssignmentItems(final Collection<AssignmentSegment> assignmentItems) {
+        assignmentItems.stream().flatMap(each -> each.getColumns().stream()).forEach(each -> {
```
Comment (strongduanmu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java:231]: Please use foreach instead of stream api.

**Review by strongduanmu — CHANGES_REQUESTED** [review]
@cheese8 Please add rewrite test case for this logic.

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Please add some rewrite test case for this logic.

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java [hunk 3]
```diff
@@ -217,11 +219,25 @@ public void extractTablesFromInsert(final InsertStatement insertStatement) {
...
             }
         }
+        InsertStatementHandler.getOnDuplicateKeyColumnsSegment(insertStatement).ifPresent(each -> extractTablesFromAssignmentItems(each.getColumns()));
         if (insertStatement.getInsertSelect().isPresent()) {
             extractTablesFromSelect(insertStatement.getInsertSelect().get().getSelect());
         }
     }
     
+    private void extractTablesFromAssignmentItems(final Collection<AssignmentSegment> assignmentItems) {
+        assignmentItems.stream().forEach(each -> extractTablesFromColumnSegments(each.getColumns()));
```
Comment (strongduanmu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java:229]: Please remove stream api here, it has performance lost.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Review by strongduanmu — APPROVED** [review]
