### PR TITLE
Use ConnectionPropertiesParser spi to parse jdbcUrl to solve oracle url parse error

### LINKED ISSUE #31743: UnrecognizedDatabaseURLException: The URL jdbc:oracle:thin:@localhost:52238:XE` is not recognize occurs when startup with Oracle datasource
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC and ShardingSphere-Proxy

### Expected behavior

startup with Oracle datasource successfully

### Actual behavior

img_v3_02bv_fc3ab747-88c6-4029-84aa-ca75a04dc93g

### Reason analyze (If you can)

- [ ] StorageNodeAggregator.java
- [ ] StorageUnit.java
- [ ] StorageUnitNodeMapCreator.java

### PR DESCRIPTION
**Pull request by strongduanmu**
Fixes #31743.

Changes proposed in this pull request:
  - Use ConnectionPropertiesParser spi to parse jdbcUrl to solve oracle url parse error

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by strongduanmu** [comment]
image

**Review by zhaojinchao95 — APPROVED** [review]

**Review by FlyingZC — APPROVED** [review]

File: infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/unit/StorageUnit.java [hunk 1]
```diff
@@ -54,9 +53,10 @@ public StorageUnit(final StorageNode storageNode, final DataSourcePoolProperties
         this.storageNode = storageNode;
         Map<String, Object> standardProps = dataSourcePoolProps.getConnectionPropertySynonyms().getStandardProperties();
         String url = standardProps.get("url").toString();
+        String username = standardProps.get("username").toString();
         storageType = DatabaseTypeFactory.get(url);
-        boolean isInstanceConnectionAvailable = new DatabaseTypeRegistry(DatabaseTypeFactory.get(url)).getDialectDatabaseMetaData().isInstanceConnectionAvailable();
-        catalog = isInstanceConnectionAvailable ? new StandardJdbcUrlParser().parse(url).getDatabase() : null;
+        boolean isInstanceConnectionAvailable = new DatabaseTypeRegistry(storageType).getDialectDatabaseMetaData().isInstanceConnectionAvailable();
+        catalog = isInstanceConnectionAvailable ? DatabaseTypedSPILoader.getService(ConnectionPropertiesParser.class, storageType).parse(url, username, null).getCatalog() : null;
```
Comment (linghengqian) [inline infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/unit/StorageUnit.java:59]: - Why is it necessary to obtain the username? This conflicts with the testcontainers-java scenario because testcontainers-java does not require a username.
```yaml
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbcUrl: jdbc:tc:postgresql:16.3-bookworm://test-native-databases-postgres/demo_ds_0
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbcUrl: jdbc:tc:postgresql:16.3-bookworm://test-native-databases-postgres/demo_ds_1
  ds_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbcUrl: jdbc:tc:postgresql:16.3-bookworm://test-native-databases-postgres/demo_ds_2
```
