### PR TITLE
Fixed In one config, can config two - !SHARDING bug

### LINKED ISSUE #18755: In one config, can config two - !SHARDING bug
### Which version of ShardingSphere did you use?

ShardingSphere-Proxy?

I add two '! Sharding', proxy can start. I think this situation should not allow startup.
企业微信截图_19b36e3f-39c9-4ecf-9313-a8dc9b5170a7

image

### PR DESCRIPTION
**Pull request by LeeGuoPing**
Fixes #18755 .

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoader.java [hunk 1]
```diff
@@ -105,9 +111,31 @@ private static Optional<YamlProxyDatabaseConfiguration> loadDatabaseConfiguratio
...
         Preconditions.checkNotNull(result.getDatabaseName(), "Property `databaseName` in file `%s` is required.", yamlFile.getName());
+        checkDuplicateRule(result.getRules(), yamlFile);
         return Optional.of(result);
     }
     
+    private static void checkDuplicateRule(final Collection<YamlRuleConfiguration> ruleConfigurations, final File yamlFile) {
+        if (ruleConfigurations.isEmpty()) {
+            return;
+        }
+        Multiset<Class<? extends RuleConfiguration>> multiset = HashMultiset.create();
```
Comment (strongduanmu) [inline shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoader.java:122]: Can we remove guava set here?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoader.java (hunk 1 above)
Comment (LeeGuoPing) [reply shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoader.java]: removed

**Review by strongduanmu — APPROVED** [review]
