### PR TITLE
fix: fix create table with foreign key error.

### LINKED ISSUE #15873: create table with foregin key error
### Which version of ShardingSphere did you use?

- 5.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

- ShardingSphere-Proxy

### Expected behavior

image

Successfully created a table .

### Actual behavior

image

Create a table failed.

### Reason analyze (If you can)

The foreign key in a database in mysql cannot be repeated, When generating SQL execution statements, there is not rewrite foreign key name.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1. add rules
```yaml
  ds_0:
    url: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: servyou
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  ds_1:
    url: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: servyou
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
```

```yaml
- !SHARDING
  bindingTables:
  - t_order,t_order_item
  defaultDatabaseStrategy:
    standard:
      shardingAlgorithmName: database_inline
      shardingColumn: user_id
  defaultTableStrategy:
    none: ''
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
  shardingAlgorithms:
    database_inline:
      props:
        algorithm-expression: ds_${user_id % 2}
      type: INLINE
    t_order_inline:
      props:
        algorithm-expression: t_order_${order_id % 2}
      type: INLINE
    t_order_item_inline:
      props:
        algorithm-expression: t_order_item_${order_id % 2}
      type: INLINE
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
      logicTable: t_order
      tableStrategy:
        standard:
          shardingAlgorithmName: t_order_inline
          shardingColumn: order_id
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
      logicTable: t_order_item
      tableStrategy:
        standard:
          shardingAlgorithmName: t_order_item_inline
          shardingColumn: order_id
```
2. create table `t_order_item`
```java
CREATE TABLE `t_order_item` (
  `order_id` bigint(32) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `order_item_id` bigint(32) DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_order_id` FOREIGN KEY (`order_id`) REFERENCES `t_order` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

### PR DESCRIPTION
**Pull request by ICannerxy**
Fixes #15873

Changes proposed in this pull request:
- CreateTableStatementContext implements ConstraintAvailable

### CODE REVIEW

File: shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/ddl/CreateTableStatementContext.java [hunk 1]
```diff
@@ -67,4 +70,13 @@ public CreateTableStatementContext(final CreateTableStatement sqlStatement) {
         }
         return result;
     }
+
+    @Override
+    public Collection<ConstraintSegment> getConstraints() {
+        List<ConstraintSegment> result = new LinkedList<>();
```
Comment (strongduanmu) [inline shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/ddl/CreateTableStatementContext.java:76]: @ICannerxy Replace List with Collection may be better.

**Review by strongduanmu — APPROVED** [review]
@ICannerxy Good job, thank you.
