### PR TITLE
fix issue#9764

### LINKED ISSUE #9764: Refactor PrivilegeMerger
### Intro
Currently, `merge()` of `PrivilegeMerger` just checks the privileges. But we still need to merge all privileges on `actual tables` and `actual schemas` into the privileges on `logic tables` and `logic schemas` truly.
Please pay attention to `SchemaPrivilege`.

### PR DESCRIPTION
**Pull request by jingshanglu**
Fixes #9764 .

### CODE REVIEW

**Review by tristaZero — CHANGES_REQUESTED** [review]

File: shardingsphere-features/shardingsphere-authority/shardingsphere-authority-common/src/main/java/org/apache/shardingsphere/authority/loader/storage/impl/StoragePrivilegeMerger.java [hunk 1]
```diff
@@ -45,15 +49,16 @@
      * @return privileges
      */
     public static Map<ShardingSphereUser, ShardingSpherePrivileges> merge(final Map<ShardingSphereUser, Collection<ShardingSpherePrivileges>> authentication,
```
Comment (tristaZero) [inline shardingsphere-features/shardingsphere-authority/shardingsphere-authority-common/src/main/java/org/apache/shardingsphere/authority/loader/storage/impl/StoragePrivilegeMerger.java:51]: Please rename `authentication` to `privileges`

**Review by tristaZero — CHANGES_REQUESTED** [review]

**Review by tristaZero — APPROVED** [review]
