### PR TITLE
Clean unused code in AbstractDataSourcePreparer and fix ci

### LINKED ISSUE #19430: Clean unused code in AbstractDataSourcePreparer
After DataSourcePreparer implementations use PipelineDDLGenerator, some utility methods are not used any more, they could be removed.

List:
- getTableDefinitionSQLType
- replaceActualTableNameToLogicTableName

Double check list:
- addIfNotExistsForCreateTableSQL, looks it's still referenced in MySQLDataSourcePreparer, is it necessary?

### PR DESCRIPTION
**Pull request by azexcy**
Fixes #19430.

Changes proposed in this pull request:
- Clean unused code in AbstractDataSourcePreparer
- Improve opengauss create table

### CODE REVIEW

File: shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/AbstractDataSourcePreparerTest.java [hunk 1]
```diff
@@ -39,36 +38,18 @@ public void prepareTargetTables(final PrepareTargetTablesParameter parameter) {
...
-            String sql = preparer.addIfNotExistsForCreateTableSQL(each);
-            assertTrue(PATTERN_CREATE_TABLE_IF_NOT_EXISTS.matcher(sql).find());
+            String actual = preparer.addIfNotExistsForCreateTableSQL(each);
+            assertTrue(PATTERN_CREATE_TABLE_IF_NOT_EXISTS.matcher(actual).find());
+        }
+        Collection<String> mismatchedSQLs = Arrays.asList("SET search_path = public", "UPDATE t_order SET id = 1");
+        for (String each : mismatchedSQLs) {
+            String actual = preparer.addIfNotExistsForCreateTableSQL(each);
+            assertThat(actual, is(actual));
         }
```
Comment (sandynz) [inline shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/AbstractDataSourcePreparerTest.java:53]: `assertThat(actual, is(actual))`, it's strange, the second `acual` might be `each`.

**Review by sandynz — CHANGES_REQUESTED** [review]

**Review by sandynz — APPROVED** [review]
