### PR TITLE
Fix failed to compile a single module (#17030)

### LINKED ISSUE #17030: Cannot compile a single module
`master branch`

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.16
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 16
[INFO] os.detected.classifier: osx-x86_64
[INFO]
[INFO] --< org.apache.shardingsphere:shardingsphere-readwrite-splitting-core >--
[INFO] Building shardingsphere-readwrite-splitting-core 5.1.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ shardingsphere-readwrite-splitting-core ---
[INFO] Deleting /Users/zhaojinchao/Documents/ss-workspace/shardingsphere/shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/target
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0:enforce (enforce-maven-version) @ shardingsphere-readwrite-splitting-core ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0:enforce (enforce-banned-dependencies) @ shardingsphere-readwrite-splitting-core ---
[INFO]
[INFO] --- maven-checkstyle-plugin:3.1.0:check (validate) @ shardingsphere-readwrite-splitting-core ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.7:prepare-agent (default) @ shardingsphere-readwrite-splitting-core ---
[INFO] argLine set to -javaagent:/Users/zhaojinchao/Documents/ss-repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/Users/zhaojinchao/Documents/ss-workspace/shardingsphere/shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/target/jacoco.exec
[INFO]
[INFO] --- maven-remote-resources-plugin:1.5:process (process-resource-bundles) @ shardingsphere-readwrite-splitting-core ---
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ shardingsphere-readwrite-splitting-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ shardingsphere-readwrite-splitting-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 21 source files to /Users/zhaojinchao/Documents/ss-workspace/shardingsphere/shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/target/classes
[INFO]
[INFO] --- spotless-maven-plugin:2.22.1:apply (default) @ shardingsphere-readwrite-splitting-core ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.513 s
[INFO] Finished at: 2022-04-23T16:38:33+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.22.1:apply (default) on project shardingsphere-readwrite-splitting-core: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.22.1:apply failed: Unable to locate file with path: src/resources/shardingsphere_eclipse_formatter.xml: Could not find resource 'src/resources/shardingsphere_eclipse_formatter.xml'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

### PR DESCRIPTION
**Pull request by longtai-cn**
Fixes #17030.

Changes proposed in this pull request:
- Fix failed to compile a single module.

### CODE REVIEW

File: shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-opengauss/src/main/java/org/apache/shardingsphere/dbdiscovery/opengauss/OpenGaussDatabaseDiscoveryType.java [hunk 1]
```diff
@@ -53,9 +53,10 @@ public final class OpenGaussDatabaseDiscoveryType implements DatabaseDiscoveryTy
     
     @Override
     public OpenGaussHighlyAvailableStatus loadHighlyAvailableStatus(final DataSource dataSource) throws SQLException {
-        try (Connection connection = dataSource.getConnection();
-             Statement statement = connection.createStatement();
-             ResultSet resultSet = statement.executeQuery(DB_ROLE)) {
+        try (
```
Comment (zjcnb) [inline shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-opengauss/src/main/java/org/apache/shardingsphere/dbdiscovery/opengauss/OpenGaussDatabaseDiscoveryType.java:56]: @longtai-cn Thank you for your pull request. I already fixed it. You can re-merge master branch.

**Review by zjcnb — APPROVED** [review]

File: shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-opengauss/src/main/java/org/apache/shardingsphere/dbdiscovery/opengauss/OpenGaussDatabaseDiscoveryType.java (hunk 1 above)
Comment (longtai-cn) [reply shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-opengauss/src/main/java/org/apache/shardingsphere/dbdiscovery/opengauss/OpenGaussDatabaseDiscoveryType.java]: @zjcnb Received, consolidated.

**Review by sandynz — APPROVED** [review]
