### PR TITLE
fix encrypt on duplicate key update

### LINKED ISSUE #9446: Encrypt on duplicate key update name=VALUES(name) will throws ExpressionProjectionSegment canot be cast to LiteralExpressionSegment
Caused by: java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.ExpressionProjectionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.simple.LiteralExpressionSegment
at org.apache.shardingsphere.infra.binder.segment.insert.values.OnDuplicateUpdateContext.getValue(OnDuplicateUpdateContext.java:87) ~[shardingsphere-infra-binder-5.0.0-alpha.jar:5.0.0-alpha]
at org.apache.shardingsphere.encrypt.rewrite.parameter.impl.EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.lambda$rewrite$0(EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java:59) ~[shardingsphere-encrypt-rewrite-5.0.0-alpha.jar:5.0.0-alpha]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_73]
at org.apache.shardingsphere.encrypt.rewrite.parameter.impl.EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.rewrite(EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java:58) ~[shardingsphere-encrypt-rewrite-5.0.0-alpha.jar:5.0.0-alpha]
at

### Which version of ShardingSphere did you use?
shardingsphere-jdbc:5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Actual behavior
Caused by: java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.common.segment.dml.item.ExpressionProjectionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.simple.LiteralExpressionSegment
### Reason analyze (If you can)
1. as follows sql, when i config 'name' use ENCRYPT, my sql like 'ON DUPLICATE KEY UPDATE name=VALUES(name)' will throw As above exception, but i change the sql like this 'ON DUPLICATE KEY UPDATE name=?', ENCRYPT is work good.
2. i trace the code, find ENCRYPT field will use OnDuplicateUpdateContext 
    public Object getValue(final int index) {
        ExpressionSegment valueExpression = valueExpressions.get(index);
        return valueExpression instanceof ParameterMarkerExpressionSegment ? parameters.get(getParameterIndex(valueExpression)) : ((LiteralExpressionSegment) valueExpression).getLiterals();
    }
3. when name=VALUES(name) valueExpression will is ExpressionProjectionSegment,  is not LiteralExpressionSegment so will throw as above exception.
4. when name=? valueExpression will is ParameterMarkerExpressionSegment ,  is work good.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
INSERT INTO anchor_info (id, source, anchorId, name, avatar, status, createTime, updateTime) VALUES
(#{id,jdbcType=BIGINT}, #{source,jdbcType=VARCHAR}, #{anchorId,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR},
#{avatar,jdbcType=VARCHAR},#{status,jdbcType=TINYINT}, #{createTime,jdbcType=BIGINT}, #{updateTime,jdbcType=BIGINT})
ON DUPLICATE KEY UPDATE name=VALUES(name),
updateTime=VALUES(updateTime);

rules:

!ENCRYPT
tables:
anchor_info:
columns:
name:
cipherColumn: name
encryptorName: aes
encryptors:
aes:
type: AES
props:
aes-key-value: abcdisjckel14003c2f8ea32cc1d59e5

### PR DESCRIPTION
**Pull request by cheese8**
Ref #9446.

Changes proposed in this pull request:
- rewrite on duplicate key update token
- parameter rewrite
- ut

### CODE REVIEW

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/impl/EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java [hunk 1]
```diff
@@ -59,6 +59,9 @@ public void rewrite(final ParameterBuilder parameterBuilder, final InsertStateme
             Optional<EncryptAlgorithm> encryptor = getEncryptRule().findEncryptor(schemaName, tableName, encryptLogicColumnName);
             encryptor.ifPresent(optional -> {
                 Object plainColumnValue = onDuplicateKeyUpdateValueContext.getValue(columnIndex);
+                if (plainColumnValue == null) {
```
Comment (strongduanmu) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/impl/EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java:62]: Hi @cheese8, please put `null` on the left.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java [hunk 2]
```diff
@@ -72,6 +74,12 @@ protected boolean isGenerateSQLTokenForEncrypt(final SQLStatementContext sqlStat
         if (assignmentSegment.getValue() instanceof ParameterMarkerExpressionSegment) {
             return Optional.of(generateParameterSQLToken(tableName, assignmentSegment));
         }
+        if (assignmentSegment.getValue() instanceof FunctionSegment) {
+            FunctionSegment functionSegment = (FunctionSegment) assignmentSegment.getValue();
+            if ("VALUES".equals(functionSegment.getFunctionName()) && functionSegment.getParameters().size() == 0) {
```
Comment (strongduanmu) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java:79]: @cheese8 `0 == functionSegment.getParameters().size()` may be better.

File: shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/insert/values/OnDuplicateUpdateContext.java [hunk 3]
```diff
@@ -79,8 +80,16 @@ public OnDuplicateUpdateContext(final Collection<AssignmentSegment> assignments,
      */
     public Object getValue(final int index) {
         ExpressionSegment valueExpression = valueExpressions.get(index);
-        return valueExpression instanceof ParameterMarkerExpressionSegment 
-                ? parameters.get(getParameterIndex((ParameterMarkerExpressionSegment) valueExpression)) : ((LiteralExpressionSegment) valueExpression).getLiterals();
+        if (valueExpression instanceof ParameterMarkerExpressionSegment) {
+            return parameters.get(getParameterIndex((ParameterMarkerExpressionSegment) valueExpression));
+        }
+        if (valueExpression instanceof FunctionSegment && ((FunctionSegment) valueExpression).getParameters().size() == 0) {
```
Comment (strongduanmu) [inline shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/insert/values/OnDuplicateUpdateContext.java:86]: Same problem.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptLiteralAssignmentToken.java [hunk 4]
```diff
@@ -56,8 +57,13 @@ public String toString() {
         
         private final Object value;
         
+        private final boolean exceptional;
+        
         @Override
         public String toString() {
+            if (exceptional) {
+                return String.format("%s = VALUES(%s)", columnName, value);
```
Comment (strongduanmu) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptLiteralAssignmentToken.java:65]: It seems that hard-writing like this can't solve the internal rewriting problem of other functions.

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Comment by menghaoranss** [comment]
@cheese8 please fix requested changes from @strongduanmu to ensure that your commits will be included in the new version we release this week.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java [hunk 5]
```diff
@@ -72,6 +74,12 @@ protected boolean isGenerateSQLTokenForEncrypt(final SQLStatementContext sqlStat
         if (assignmentSegment.getValue() instanceof ParameterMarkerExpressionSegment) {
             return Optional.of(generateParameterSQLToken(tableName, assignmentSegment));
         }
+        if (assignmentSegment.getValue() instanceof FunctionSegment) {
+            FunctionSegment functionSegment = (FunctionSegment) assignmentSegment.getValue();
+            if ("VALUES".equals(functionSegment.getFunctionName()) && 0 == functionSegment.getParameters().size()) {
```
Comment (strongduanmu) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java:79]: @cheese8 Why need `0 == functionSegment.getParameters().size()` here?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java [hunk 6]
```diff
@@ -95,6 +108,46 @@ private EncryptAssignmentToken generateLiteralSQLToken(final String schemaName,
...
+        EncryptLiteralAssignmentToken result = new EncryptLiteralAssignmentToken(columnSegment.getStartIndex(), assignmentSegment.getStopIndex());
+        
+        boolean cipherColumnPresent = getEncryptRule().findEncryptor(schemaName, tableName, column).isPresent();
+        boolean cipherValueColumnPresent = getEncryptRule().findEncryptor(schemaName, tableName, valueColumn).isPresent();
+        if (cipherColumnPresent && cipherValueColumnPresent) {
+            String cipherColumn = getEncryptRule().getCipherColumn(tableName, column);
+            String cipherValueColumn = getEncryptRule().getCipherColumn(tableName, valueColumn);
+            result.addAssignment(cipherColumn, String.format("VALUES(%s)", cipherValueColumn), false);
+        } else if (cipherColumnPresent != cipherValueColumnPresent) {
+            throw new ShardingSphereException("The SQL clause `%s` is unsupported in encrypt rule.", String.format("%s=VALUES(%s)", column, valueColumn));
```
Comment (tuichenchuxin) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java:126]: I think it is possible if column and value is different column

Comment (cheese8) [reply shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java:126]: Yes, I also think so and did it.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/impl/EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java [hunk 7]
```diff
@@ -59,6 +59,9 @@ public void rewrite(final ParameterBuilder parameterBuilder, final InsertStateme
             Optional<EncryptAlgorithm> encryptor = getEncryptRule().findEncryptor(schemaName, tableName, encryptLogicColumnName);
             encryptor.ifPresent(optional -> {
                 Object plainColumnValue = onDuplicateKeyUpdateValueContext.getValue(columnIndex);
+                if (null == plainColumnValue) {
```
Comment (tuichenchuxin) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/impl/EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java:62]: Better get functionSegment then judge.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java [hunk 8]
```diff
@@ -61,7 +64,14 @@ protected boolean isGenerateSQLTokenForEncrypt(final SQLStatementContext sqlStat
         }
         String schemaName = insertStatementContext.getSchemaName();
         for (AssignmentSegment each : onDuplicateKeyColumnsSegments) {
-            if (getEncryptRule().findEncryptor(schemaName, tableName, each.getColumns().get(0).getIdentifier().getValue()).isPresent()) {
+            if (each.getValue() instanceof FunctionSegment && "VALUES".equalsIgnoreCase(((FunctionSegment) each.getValue()).getFunctionName())) {
+                boolean leftEncryptorPresent = getEncryptRule().findEncryptor(schemaName, tableName, each.getColumns().get(0).getIdentifier().getValue()).isPresent();
+                ColumnSegment rightColumn = (ColumnSegment) ((FunctionSegment) each.getValue()).getParameters().stream().findFirst().get();
+                boolean rightEncryptorPresent = getEncryptRule().findEncryptor(schemaName, tableName, rightColumn.getIdentifier().getValue()).isPresent();
+                if (leftEncryptorPresent || rightEncryptorPresent) {
+                    generateSQLToken(schemaName, tableName, each).ifPresent(result::add);
```
Comment (tuichenchuxin) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java:72]: Is same with line 75. Combine them may be better

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java (hunk 6 above)
Comment (tuichenchuxin) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java:126]: Why can't support ? If cipherColumn is present, but value is not, we need to support this case.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptLiteralAssignmentToken.java [hunk 9]
```diff
@@ -56,13 +65,15 @@ public String toString() {
...
+        private final boolean withQuotes;
+        
         @Override
         public String toString() {
             return String.format("%s = %s", columnName, toString(value));
         }
     
         private String toString(final Object value) {
-            return String.class == value.getClass() ? String.format("'%s'", value) : value.toString();
+            return (String.class == value.getClass() && withQuotes) ? String.format("'%s'", value) : value.toString();
```
Comment (tuichenchuxin) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptLiteralAssignmentToken.java:76]: Maybe define a new class to handle this.

File: shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/insert/values/OnDuplicateUpdateContext.java [hunk 10]
```diff
@@ -79,8 +80,13 @@ public OnDuplicateUpdateContext(final Collection<AssignmentSegment> assignments,
      */
     public Object getValue(final int index) {
         ExpressionSegment valueExpression = valueExpressions.get(index);
-        return valueExpression instanceof ParameterMarkerExpressionSegment 
-                ? parameters.get(getParameterIndex((ParameterMarkerExpressionSegment) valueExpression)) : ((LiteralExpressionSegment) valueExpression).getLiterals();
+        if (valueExpression instanceof ParameterMarkerExpressionSegment) {
+            return parameters.get(getParameterIndex((ParameterMarkerExpressionSegment) valueExpression));
+        }
+        if (valueExpression instanceof FunctionSegment && "VALUES".equalsIgnoreCase(((FunctionSegment) valueExpression).getFunctionName())) {
+            return null;
```
Comment (tuichenchuxin) [inline shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/insert/values/OnDuplicateUpdateContext.java:87]: Maybe just return the functionSegment, Then judge in the use place.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java [hunk 11]
```diff
@@ -61,9 +65,15 @@ protected boolean isGenerateSQLTokenForEncrypt(final SQLStatementContext sqlStat
...
-            }
+            if (each.getValue() instanceof FunctionSegment && "VALUES".equalsIgnoreCase(((FunctionSegment) each.getValue()).getFunctionName())) {
+                boolean leftEncryptorPresent = getEncryptRule().findEncryptor(schemaName, tableName, each.getColumns().get(0).getIdentifier().getValue()).isPresent();
+                ColumnSegment rightColumn = (ColumnSegment) ((FunctionSegment) each.getValue()).getParameters().stream().findFirst().get();
+                boolean rightEncryptorPresent = getEncryptRule().findEncryptor(schemaName, tableName, rightColumn.getIdentifier().getValue()).isPresent();
+                if (!leftEncryptorPresent && !rightEncryptorPresent) {
+                    continue;
+                }
+            } 
+            generateSQLToken(schemaName, tableName, each).ifPresent(result::add);
```
Comment (tuichenchuxin) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java:76]: This function logic may be not right. Without encrypt check?

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptFunctionAssignmentToken.java [hunk 12]
```diff
@@ -0,0 +1,76 @@
...
+        return assignments;
+    }
+    
+    @Override
+    public String toString() {
+        return Joiner.on(", ").join(assignments);
+    }
+    
+    @RequiredArgsConstructor
+    private static final class LiteralAssignment {
```
[the remark this answers is not in the document]
Comment (cheese8) [reply shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptFunctionAssignmentToken.java:61]: It's not the same on toString method, `String.format("'%s'", value)`

[the remark this answers is not in the document]
Comment (cheese8) [reply shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptFunctionAssignmentToken.java:61]: Only without quotes.

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java (hunk 11 above)
Comment (cheese8) [reply shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptInsertOnUpdateTokenGenerator.java:76]: The guard clause check is above. `continue` block processed.

**Review by tuichenchuxin — APPROVED** [review]

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @cheese8, can you take a look at ci error?

**Comment by cheese8** [comment]
> Hi @cheese8, can you take a look at ci error?

done.

**Review by strongduanmu — APPROVED** [review]
