### PR TITLE
fix set session transaction read only

### LINKED ISSUE #14541: on proxy, in release application, do update, delete, add transaction  sql operation will throw read only  Exception.
### Which version of ShardingSphere did you use?
5.1.0-GA

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy

### Expected behavior
update, delete, add sql will throw read only Exception.

### Actual behavior
from application log: 
image

from proxy log:

remark:  two case are transaction issues.

### Reason analyze (If you can)
In the application connection agent, if transaction operations are performed, such as (batch) new addition, (batch) modification, (batch) deletion, exceptions will occur
feature:
- Occasionally
- Prone to happen under multithreading
- Transactional

remark: Personal level is limited, unable to locate specific code issues for transaction issues, But this is more important for application . 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
single transaction sql
application env:
- druid pool (default transaction config)
- spring transaction 
proxy env:
 ``` - !TRANSACTION
  defaultType: XA | LOCAL
  providerType: Atomikos | null ```

### PR DESCRIPTION
**Pull request by jingshanglu**
Fixes #14541 .

[design detail](https://u01f1kqxrl.feishu.cn/docs/doccnbmEnjFvc3JtbzfoASSaRpf#)

Changes proposed in this pull request:
-  add handler for `set session transaction...`
-  when come `set session transaction...`, just set some flag on `ConnectionSession`
-  when get connection to DB，set transaction properties on the connection
-  when release connection to DB, reset transaction properties on the connection

### Test
[ test case](https://github.com/SphereEx/auto-test/pull/1)

### CODE REVIEW

**Comment by terrymanu** [comment]
Please resolve conflict

**Comment by jingshanglu** [comment]
> Please resolve conflict

ok

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/Scope.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.apache.shardingsphere.sql.parser.sql.common.constant;
+
+/**
+ * Scope enum.
+ */
+public enum Scope {
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/Scope.java:23]: The class name `Scope` is too broad. Could you rename it as a better name? for example: ConnectionScope, 
 OperationScope or TransactionScope?

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionAccessType.java [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+ */
+public enum TransactionAccessType {
+    READ_ONLY("READ_ONLY"),
+    READ_WRITE("READ_WRITE");
+
+    private final String accessType;
+
+    TransactionAccessType(final String accessType) {
+        this.accessType = accessType;
+    }
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionAccessType.java:31]: Please use `@RequiredArgsConstructor`

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionAccessType.java [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+
+    /**
+     * Get transaction access type.
+     *
+     * @return transaction access type
+     */
+    public String getAccessType() {
+        return accessType;
+    }
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionAccessType.java:40]: Please use `@Getter`

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+    }
+
+    /**
+     * Get transaction isolation level.
+     *
+     * @return transaction isolation level
+     */
+    public String getIsolationLevel() {
+        return isolationLevel;
+    }
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java:43]: Please use `@Getter`

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/Scope.java [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+    GLOBAL("GLOBAL"),
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/Scope.java:24]: Please keep a blank line between class definition and first variable declaration.

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionAccessType.java [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+ * limitations under the License.
+ */
+
+package org.apache.shardingsphere.sql.parser.sql.common.constant;
+
+/**
+ * Transaction access type enum.
+ */
+public enum TransactionAccessType {
+    READ_ONLY("READ_ONLY"),
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionAccessType.java:24]: Please keep a blank line between class definition and first variable declaration.

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+ * limitations under the License.
+ */
+
+package org.apache.shardingsphere.sql.parser.sql.common.constant;
+
+/**
+ * Transaction isolation level enum.
+ */
+public enum TransactionIsolationLevel {
+    NONE("NONE"),
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java:24]: Please keep a blank line between class definition and first variable declaration.

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+    REPEATABLE_READ("REPEATABLE READ"),
+    READ_UNCOMMITTED("READ UNCOMMITTED"),
+    SERIALIZABLE("SERIALIZABLE"),
+    READ_COMMITTED("READ COMMITTED");
+
+    private final String isolationLevel;
+
+    TransactionIsolationLevel(final String isolationLevel) {
+        this.isolationLevel = isolationLevel;
+    }
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java:34]: Please use `@RequiredArgsConstructor`

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+
+/**
+ * Transaction isolation level enum.
+ */
+public enum TransactionIsolationLevel {
+    NONE("NONE"),
+    REPEATABLE_READ("REPEATABLE READ"),
+    READ_UNCOMMITTED("READ UNCOMMITTED"),
+    SERIALIZABLE("SERIALIZABLE"),
+    READ_COMMITTED("READ COMMITTED");
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java:28]: Please adjust the sequence of the enums to `READ_UNCOMMITTED`, `READ_COMMITTED`, `REPEATABLE_READ` and `SERIALIZABLE`

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/tcl/SetTransactionStatement.java [hunk 10]
```diff
@@ -17,10 +17,25 @@
...
+import org.apache.shardingsphere.sql.parser.sql.common.constant.Scope;
+import org.apache.shardingsphere.sql.parser.sql.common.constant.TransactionAccessType;
+import org.apache.shardingsphere.sql.parser.sql.common.constant.TransactionIsolationLevel;
 import org.apache.shardingsphere.sql.parser.sql.common.statement.AbstractSQLStatement;
 
 /**
  * Set transaction statement.
  */
+@Getter
+@Setter
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/tcl/SetTransactionStatement.java:32]: Is it possible to use final and @RequiredArgsConstructor to instead of getter and setter?

**Review by terrymanu — CHANGES_REQUESTED** [review]

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/tcl/SetTransactionStatement.java (hunk 10 above)
Comment (jingshanglu) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/tcl/SetTransactionStatement.java:31]: > Is it possible to use final and @RequiredArgsConstructor to instead of getter and setter?

I think we can use `setter`, `getter`, because those properties are not required, maybe only part of them.

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java [hunk 11]
```diff
@@ -54,7 +55,13 @@
     
     @Getter(AccessLevel.NONE)
     private final AtomicBoolean autoCommit = new AtomicBoolean(true);
-    
+
+    private boolean readOnly;
```
Comment (terrymanu) [inline shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java:59]: Should `readOnly` keep consist with autoCommit, just use AtomicBoolean?

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/util/TransactionUtil.java [hunk 12]
```diff
@@ -0,0 +1,73 @@
...
+                return Connection.TRANSACTION_SERIALIZABLE;
+            default:
+                return Connection.TRANSACTION_NONE;
+        }
+    }
+
+    /**
+     * Get the value of type TransactionIsolationLevel according to int.
+     *
+     * @param isolationLevel int type
```
Comment (terrymanu) [inline shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/util/TransactionUtil.java:56]: The `int type` of java doc is incorrect.

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/util/TransactionUtil.java [hunk 13]
```diff
@@ -0,0 +1,73 @@
...
+     * @return isolationLevel
```
Comment (terrymanu) [inline shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/util/TransactionUtil.java:57]: `isolationLevel` are 2 words, please do not use camel case

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/util/TransactionUtil.java [hunk 14]
```diff
@@ -0,0 +1,73 @@
...
+                return Connection.TRANSACTION_REPEATABLE_READ;
+            case SERIALIZABLE:
+                return Connection.TRANSACTION_SERIALIZABLE;
+            default:
+                return Connection.TRANSACTION_NONE;
+        }
+    }
+
+    /**
+     * Get the value of type TransactionIsolationLevel according to int.
```
Comment (terrymanu) [inline shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/util/TransactionUtil.java:54]: `TransactionIsolationLevel` are 3 words, please split them

File: shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java [hunk 15]
```diff
@@ -0,0 +1,37 @@
...
+ */
+@RequiredArgsConstructor
+@Getter
+public enum TransactionIsolationLevel {
+
+    NONE("NONE"),
+    REPEATABLE_READ("REPEATABLE_READ"),
+    READ_UNCOMMITTED("READ_UNCOMMITTED"),
+    SERIALIZABLE("SERIALIZABLE"),
+    READ_COMMITTED("READ_COMMITTED");
```
Comment (terrymanu) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/constant/TransactionIsolationLevel.java:34]: Please change the sequence to READ_UNCOMMITTED, READ_COMMITTED, REPEATABLE_READ, SERIALIZABLE

**Review by terrymanu — CHANGES_REQUESTED** [review]

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/util/TransactionUtil.java (hunk 14 above)
Comment (jingshanglu) [reply shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/util/TransactionUtil.java:54]: `TransactionIsolationLevel` represents the type of value,  maybe it‘s better.

**Review by terrymanu — APPROVED** [review]
