### PR TITLE
fix calcite exception when user execute sql with lowercase

### LINKED ISSUE #11946: when I use two oracle datasource, Calcite upper case table name ,then cannot find table in logicTables
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
Executing SQL normally

### Actual behavior
calcite will upper case sql whitout quoted, but  shardingSphere  lower case logicTable , then it can't find the table.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
configuration:
`spring.shardingsphere.datasource.names=db2,db3

spring.shardingsphere.datasource.db2.type=org.apache.commons.dbcp2.BasicDataSource
spring.shardingsphere.datasource.db2.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.shardingsphere.datasource.db2.url=jdbc:oracle:thin:@127.0.0.1:1521/db
spring.shardingsphere.datasource.db2.username=test1
spring.shardingsphere.datasource.db2.password=test1

spring.shardingsphere.datasource.db3.type=org.apache.commons.dbcp2.BasicDataSource
spring.shardingsphere.datasource.db3.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.shardingsphere.datasource.db3.url=jdbc:oracle:thin:@127.0.0.1:1521/db
spring.shardingsphere.datasource.db3.username=test2
spring.shardingsphere.datasource.db3.password=test2

spring.shardingsphere.rules.sharding.tables.t_order.logic-table=t_order
spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes=db$->{2..3}.t_order_$->{0..1}
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-column=order_id
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-algorithm-name=t_order_sharding
spring.shardingsphere.rules.sharding.tables.t_order.database-strategy.standard.sharding-column=order_id
spring.shardingsphere.rules.sharding.tables.t_order.database-strategy.standard.sharding-algorithm-name=db_sharding

spring.shardingsphere.rules.sharding.tables.t_order_detail_.logic-table=t_order_detail_
spring.shardingsphere.rules.sharding.tables.t_order_detail_.actual-data-nodes=db$->{2..3}.t_order_detail_$->{0..1}
spring.shardingsphere.rules.sharding.tables.t_order_detail_.table-strategy.standard.sharding-column=order_id
spring.shardingsphere.rules.sharding.tables.t_order_detail_.database-strategy.standard.sharding-column=order_id
spring.shardingsphere.rules.sharding.tables.t_order_detail_.table-strategy.standard.sharding-algorithm-name=t_order_sharding
spring.shardingsphere.rules.sharding.tables.t_order_detail_.database-strategy.standard.sharding-algorithm-name=db_sharding`

sql:
`        SELECT row_.*, rownum rownum_ FROM
        (
        SELECT t.order_id, order_type, order_price, oper,order_time, order_detail_1, order_detail_2 FROM
         t_order t JOIN t_order_detail_ i
        ON t.order_id = i.order_id order by order_id) row_
        WHERE rownum <= 10 and rownum > 0 order by order_id`

### PR DESCRIPTION
**Pull request by strongduanmu**
Fixes #11946.

Changes proposed in this pull request:
- fix calcite exception when oracle federate metadata lowercase
- add test case for sharding metadata loader

### CODE REVIEW

File: shardingsphere-infra/shardingsphere-infra-optimize/src/main/java/org/apache/shardingsphere/infra/optimize/core/metadata/FederateSchemaMetadata.java [hunk 1]
```diff
@@ -46,20 +46,22 @@ public FederateSchemaMetadata(final String name, final Map<String, TableMetaData
...
     /**
      * Remove.
+     * 
      * @param tableName table name
      */
     @Synchronized
     public void remove(final String tableName) {
-        tables.remove(tableName);
+        tables.remove(tableName.toLowerCase());
     }
```
Comment (tristaZero) [inline shardingsphere-infra/shardingsphere-infra-optimize/src/main/java/org/apache/shardingsphere/infra/optimize/core/metadata/FederateSchemaMetadata.java:66]: Do we have to fix this issue by this one?

**Review by tristaZero — CHANGES_REQUESTED** [review]

File: shardingsphere-infra/shardingsphere-infra-optimize/src/main/java/org/apache/shardingsphere/infra/optimize/core/metadata/FederateSchemaMetadata.java (hunk 1 above)
Comment (strongduanmu) [reply shardingsphere-infra/shardingsphere-infra-optimize/src/main/java/org/apache/shardingsphere/infra/optimize/core/metadata/FederateSchemaMetadata.java:66]: > Do we have to fix this issue by this one?

@tristaZero This modification is not necessary to fix this issue, just to keep the same with the initial metadata processing way.

```java
@Getter
public final class FederateSchemaMetadatas {
    
    private final Map<String, FederateSchemaMetadata> schemas = new LinkedMap<>();
    
    public FederateSchemaMetadatas(final Map<String, ShardingSphereMetaData> metaDataMap) {
        for (Entry<String, ShardingSphereMetaData> each : metaDataMap.entrySet()) {
            schemas.put(each.getKey(), new FederateSchemaMetadata(each.getKey(), each.getValue().getSchema().getTables()));
        }
    }
...
}
```

When initializing FederateSchemaMetadata, the parameter `each.getValue().getSchema().getTables()` is a member variable of `ShardingSphereSchema`, and its key is uniformly processed to lowercase. If other methods are not processed to lowercase, use the case-insensitive dialects will occur wrong result when updating FederateSchemaMetadata.

**Review by tristaZero — APPROVED** [review]
