### PR TITLE
Add testcase for MySQLPrivilageLoader & fix bug

### LINKED ISSUE #9852: Add unit test for `MySQLPrivilegeLoader`
Hi,

### Intro
`MySQLPrivilegeLoader` is to load privileges from MySQL databases using specific SQLs. Please add a test class to test this `MySQLPrivilegeLoader` function. I assume `MySQLTableMetaDataLoaderTest` will give you some hints.

Any questions, please contact me here. :)

### PR DESCRIPTION
**Pull request by zhujunxxxxx**
Fixes #9852.

Changes proposed in this pull request:
- add testcase for MySQLPrivilageLoader
- fix MySQLPrivilageLoader load problem

### CODE REVIEW

File: shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/auth/builder/loader/dialect/MySQLPrivilegeLoader.java [hunk 1]
```diff
@@ -52,6 +52,7 @@
     @Override
     public Map<ShardingSphereUser, ShardingSpherePrivilege> load(final Collection<ShardingSphereUser> users, final DataSource dataSource) throws SQLException {
         Map<ShardingSphereUser, ShardingSpherePrivilege> result = new LinkedHashMap<>();
+        users.forEach(user -> result.put(user, new ShardingSpherePrivilege()));
```
Comment (tristaZero) [inline shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/auth/builder/loader/dialect/MySQLPrivilegeLoader.java:55]: Does that means this user has no privileges in databases, right?

File: shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/metadata/auth/builder/loader/dialect/MySQLPrivilegeLoaderTest.java [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+
+import static org.hamcrest.CoreMatchers.is;
+import static org.junit.Assert.assertThat;
+import static org.junit.Assert.assertEquals;
+import static org.mockito.Mockito.when;
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.RETURNS_DEEP_STUBS;
+
+@RunWith(MockitoJUnitRunner.class)
+public class MySQLPrivilegeLoaderTest {
```
Comment (tristaZero) [inline shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/metadata/auth/builder/loader/dialect/MySQLPrivilegeLoaderTest.java:48]: Hi Please define it as a final class.

**Review by tristaZero — CHANGES_REQUESTED** [review]
Hi, Looks great.

File: shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/auth/builder/loader/dialect/MySQLPrivilegeLoader.java (hunk 1 above)
Comment (zhujunxxxxx) [reply shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/auth/builder/loader/dialect/MySQLPrivilegeLoader.java:55]:
```
private void fillGlobalPrivilege(final Map<ShardingSphereUser, ShardingSpherePrivilege> privileges, final ResultSet resultSet) throws SQLException {
        Optional<ShardingSphereUser> user = getShardingSphereUser(privileges, resultSet);
        if (user.isPresent()) {
            privileges.get(user.get()).getAdministrativePrivilege().getPrivileges().addAll(loadAdministrativePrivileges(resultSet));
            privileges.get(user.get()).getDatabasePrivilege().getGlobalPrivileges().addAll(loadDatabaseGlobalPrivileges(resultSet));
        }
    }
```
We analyzed this code will find in `getShardingSphereUser` method, if parameter `privileges` is empty it will returns empty, so `user.isPresent()` always false. `fillGlobalPrivilege` can't add any elements to `privileges`.The same problem in `fillSchemaPrivilege` and `fillTablePrivilege`.  but the parameter `privileges` is empty at first.

so I add the below code in the first to avoid this problem.
```
users.forEach(user -> result.put(user, new ShardingSpherePrivilege()));
```
@tristaZero Can you help me see if this is right？

Comment (zhujunxxxxx) [reply shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/auth/builder/loader/dialect/MySQLPrivilegeLoader.java:55]: @tristaZero  It simply initializes an empty container to hold the data. I discovered this problem through test cases

**Review by tristaZero — APPROVED** [review]
Hi @zhujunxxxxx 
What you mentioned is possible.

**Review by tristaZero — CHANGES_REQUESTED** [review]
But could you look at the CI test? They failed.

**Review by tristaZero — APPROVED** [review]
