### PR TITLE
fix file not found in windows os: config path with blank character re…

### LINKED ISSUE #13833: file not found when path with blank under windows os environment
ShardingSphere 5.0

ShardingSphere-Proxy

unzip and run shardingsphere normally, console output 'ShardingSphere-Proxy start success'

### Actual behavior
Exception in thread "main" java.io.FileNotFoundException: D:\Program%20Files\apache-shardingsphere-5.0.0-shardingsphere-proxy-bin\conf\server.yaml (系统找不到指定的路径。)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at org.apache.shardingsphere.infra.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:53)
        at org.apache.shardingsphere.proxy.config.ProxyConfigurationLoader.loadServerConfiguration(ProxyConfigurationLoader.java:71)
        at org.apache.shardingsphere.proxy.config.ProxyConfigurationLoader.load(ProxyConfigurationLoader.java:58)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:46)

### Reason analyze (If you can)

sharding-proxy distribution was under path "Program Files", when use Class.getResource, blank character was replaced by '%20', then file not found.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Windows OS, place sharding-proxy binary to path with blank, like 'C:\Program Files\', then run start.bat

### PR DESCRIPTION
**Pull request by iMinusMinus**
Fixes #13833.

Changes proposed in this pull request:
- change 'org.apache.shardingsphere.proxy.config.ProxyConfigurationLoader', replace 'url.getFile()' with 'url.toURI().getPath()', change method signature as throws URISyntaxException
- change 'org.apache.shardingsphere.proxy.Bootstrap', change 'main' method signature as throws URISyntaxException
- change 'org.apache.shardingsphere.proxy.config.ProxyConfigurationLoaderTest', change 'assertLoad' method signature as throws URISyntaxException

### CODE REVIEW

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/config/ProxyConfigurationLoader.java [hunk 1]
```diff
@@ -53,18 +54,19 @@
...
+    public static YamlProxyConfiguration load(final String path) throws IOException, URISyntaxException {
         YamlProxyServerConfiguration serverConfig = loadServerConfiguration(getResourceFile(String.join("/", path, SERVER_CONFIG_FILE)));
         File configPath = getResourceFile(path);
         Collection<YamlProxyRuleConfiguration> ruleConfigs = loadRuleConfigurations(configPath);
         return new YamlProxyConfiguration(serverConfig, ruleConfigs.stream().collect(Collectors.toMap(
                 YamlProxyRuleConfiguration::getSchemaName, each -> each, (oldValue, currentValue) -> oldValue, LinkedHashMap::new)));
     }
     
-    private static File getResourceFile(final String path) {
+    private static File getResourceFile(final String path) throws URISyntaxException {
```
Comment (TeslaCN) [inline shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/config/ProxyConfigurationLoader.java:67]: I prefer using `@SneakyThrow(URISyntaxException.class)` here.

Comment (iMinusMinus) [reply shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/config/ProxyConfigurationLoader.java]: agreed

**Review by TeslaCN — APPROVED** [review]
@iMinusMinus Thank you!
