### PR TITLE
Check sharding algorithm for create & alter sharding table rule

### LINKED ISSUE #10688: Distsql metadata wrong when execute create sharding table rule with an invalid type
### Which version of ShardingSphere did you use?

master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy & governance

### Expected behavior

throw exception when execute create sharding table rule with an invalid type

### Actual behavior

no exception and store wrong metadata

image

### PR DESCRIPTION
**Pull request by menghaoranss**
Fixes #10688 .

### CODE REVIEW

File: shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/rdl/impl/AlterShardingTableRuleBackendHandler.java [hunk 1]
```diff
@@ -19,28 +19,37 @@
...
+import java.util.Properties;
 import java.util.stream.Collectors;
 
 /**
  * Alter sharding table rule backend handler.
  */
 public final class AlterShardingTableRuleBackendHandler extends RDLBackendHandler<AlterShardingTableRuleStatement> {
     
+    static {
+        ShardingSphereServiceLoader.register(ShardingAlgorithm.class);
```
Comment (terrymanu) [inline shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/rdl/impl/AlterShardingTableRuleBackendHandler.java:50]: Why register twice, ShardingAlgorithm has already register in ShardingRule

**Review by TeslaCN — APPROVED** [review]
