### PR TITLE
For #14281: Fix the problem that the replication stream slot of incremental tasks in PostgreSQL is occupied in the case of multiple data sources.

### LINKED ISSUE #14281: Modify the slot occupation exception caused by PostgreSQL in multiple data sources
### Which version of ShardingSphere did you use?
Version 5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
PostgreSQL successfully migrated during data migration of multiple data sources

### Actual behavior
PostgreSQL has an exception of slot occupancy during data migration of multiple data sources

### Reason analyze (If you can)
It may be that multiple data sources have created two replication streams, but because replication_slot is bound to PID, an exception is thrown during the second creation

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1、Use shardingsphere-proxy to add resources
2、Create migration task
3、
```java
org.apache.shardingsphere.data.pipeline.core.ingest.exception.IngestException: org.postgresql.util.PSQLException: ERROR: replication slot "sharding_scaling" is active for PID 36827
    at org.apache.shardingsphere.data.pipeline.postgresql.ingest.PostgreSQLWalDumper.dump(PostgreSQLWalDumper.java:98)
    at org.apache.shardingsphere.data.pipeline.postgresql.ingest.PostgreSQLWalDumper.start(PostgreSQLWalDumper.java:76)
    at org.apache.shardingsphere.data.pipeline.core.task.IncrementalTask.start(IncrementalTask.java:86)
    at org.apache.shardingsphere.data.pipeline.api.executor.AbstractLifecycleExecutor.run(AbstractLifecycleExecutor.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: replication slot "sharding_scaling" is active for PID 36827
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
    at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1116)
    at org.postgresql.core.v3.QueryExecutorImpl.startCopy(QueryExecutorImpl.java:842)
    at org.postgresql.core.v3.replication.V3ReplicationProtocol.initializeReplication(V3ReplicationProtocol.java:58)
    at org.postgresql.core.v3.replication.V3ReplicationProtocol.startLogical(V3ReplicationProtocol.java:42)
    at org.postgresql.replication.fluent.ReplicationStreamBuilder$1.start(ReplicationStreamBuilder.java:38)
    at org.postgresql.replication.fluent.logical.LogicalStreamBuilder.start(LogicalStreamBuilder.java:37)
    at org.apache.shardingsphere.data.pipeline.postgresql.ingest.wal.LogicalReplication.createReplicationStream(LogicalReplication.java:75)
    at org.apache.shardingsphere.data.pipeline.postgresql.ingest.PostgreSQLWalDumper.dump(PostgreSQLWalDumper.java:81)
    ... 10 common frames omitted
```

### PR DESCRIPTION
**Pull request by ReyYang**
Fixes #14281 .

Changes proposed in this pull request:
- Fix the problem that the replication stream slot of incremental tasks in PostgreSQL is occupied in the case of multiple data sources.
- Modify PostgreSQLPositionInitializerTest and PostgreSQLWalDumperTest

### CODE REVIEW

File: shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLPositionInitializerTest.java [hunk 1]
```diff
@@ -128,4 +130,15 @@ public void assertDestroyWhenSlotExists() throws SQLException {
...
+    /**
+     * Get the unique slot name by connection.
+     *
+     * @param conn the connection
+     * @return the unique name by connection
+     * @throws SQLException failed when getCatalog
+     */
+    public static String getUniqueSlotName(final Connection conn) throws SQLException {
+        return String.format("%s_%s", "sharding_scaling", conn.getCatalog());
+    }
```
Comment (sandynz) [inline shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLPositionInitializerTest.java:143]: Looks it's the same code as `PostgreSQLPositionInitializer.getUniqueSlotName`

File: shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLPositionInitializer.java [hunk 2]
```diff
@@ -113,8 +113,19 @@ private void dropSlotIfExists(final Connection connection) throws SQLException {
...
     }
+    
+    /**
+     * Get the unique slot name by connection.
+     *
+     * @param conn the connection
+     * @return the unique name by connection
+     * @throws SQLException failed when getCatalog
+     */
+    public static String getUniqueSlotName(final Connection conn) throws SQLException {
```
Comment (sandynz) [inline shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLPositionInitializer.java:128]: Use `connection` instead of `conn` could be better, keep consistent variable naming.

**Review by sandynz — APPROVED** [review]

**Review by sandynz — APPROVED** [review]
