### PR TITLE
Fix create table if not exists pre validation error

### LINKED ISSUE #7323: CREATE TABLE IF NOT EXISTS  execute fail
## Bug Report
```
### SQL: CREATE TABLE IF NOT EXISTS t_order (order_id BIGINT AUTO_INCREMENT, user_id INT NOT NULL, address_id BIGINT NOT NULL, status VARCHAR(50), PRIMARY KEY (order_id));
### Cause: org.apache.shardingsphere.sharding.route.engine.exception.TableExistsException: Table 't_order' already exists.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 17 more
Caused by: org.apache.shardingsphere.sharding.route.engine.exception.TableExistsException: Table 't_order' already exists.
	at org.apache.shardingsphere.sharding.route.engine.validator.impl.ShardingCreateTableStatementValidator.preValidate(ShardingCreateTableStatementValidator.java:40)
	at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.lambda$decorate$0(ShardingRouteDecorator.java:66)
```

**For English only**, other languages will not accept.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
run and finish successfully 
### Actual behavior
throws an exception 

### Reason analyze (If you can)
The logic is in ShardingCreateTableStatementValidator.preValidate.  I think for it should not check if the create table contains   IF NOT EXISTS statement 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Run any the example module , with pre created table

### PR DESCRIPTION
**Pull request by xbkaishui**
Fixes #7323 

Changes proposed in this pull request:
-  Fix create table if not exists pre validation error. ignore validation when use this

### CODE REVIEW

File: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/impl/MySQLDDLVisitor.java [hunk 1]
```diff
@@ -166,7 +166,7 @@ public ASTNode visitRenameTableSpecification(final RenameTableSpecificationConte
     @SuppressWarnings("unchecked")
     @Override
     public ASTNode visitCreateTable(final CreateTableContext ctx) {
-        CreateTableStatement result = new CreateTableStatement((SimpleTableSegment) visit(ctx.tableName()));
+        CreateTableStatement result = new CreateTableStatement((SimpleTableSegment) visit(ctx.tableName()), null != ctx.notExistClause_().EXISTS());
```
Comment (tristaZero) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/impl/MySQLDDLVisitor.java:169]: Do you think `null != ctx.notExistClause_()` is enough?

File: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/impl/PostgreSQLDDLVisitor.java [hunk 2]
```diff
@@ -96,7 +96,7 @@
     @SuppressWarnings("unchecked")
     @Override
     public ASTNode visitCreateTable(final CreateTableContext ctx) {
-        CreateTableStatement result = new CreateTableStatement((SimpleTableSegment) visit(ctx.tableName()));
+        CreateTableStatement result = new CreateTableStatement((SimpleTableSegment) visit(ctx.tableName()), false);
```
Comment (tristaZero) [inline shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/impl/PostgreSQLDDLVisitor.java:99]: `PostgreSQL` has the similar SQL as well.

**Review by tristaZero — CHANGES_REQUESTED** [review]
Hi @xbkaishui, The basic process is correct. Please look at my comments. Also, there are some conflicts needing deal with.

File: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/impl/MySQLDDLVisitor.java (hunk 1 above)
Comment (xbkaishui) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/impl/MySQLDDLVisitor.java:169]: No,  it will return an Empty notExistClause*Context, it's EXISTS() method will return null

**Comment by tristaZero** [comment]
@strongduanmu Please give your attention to `CreateTableStatement`, since `notExisted` segment does not apply to all the databases. As a result, `notExisted` is supposed to appear in the `CreateTableStatement` child class.

File: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/impl/PostgreSQLDDLVisitor.java (hunk 2 above)
Comment (xbkaishui) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/impl/PostgreSQLDDLVisitor.java:99]: ok will check

**Comment by strongduanmu** [comment]
> @strongduanmu Please give your attention to `CreateTableStatement`, since `notExisted` segment does not apply to all the databases. As a result, `notExisted` is supposed to appear in the `CreateTableStatement` child class.

@tristaZero Thank you for your reminder, I will pay attention to this detail in the DDL statement refactor.

File: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/impl/PostgreSQLDDLVisitor.java (hunk 2 above)
Comment (xbkaishui) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/impl/PostgreSQLDDLVisitor.java]: done

File: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/impl/MySQLDDLVisitor.java (hunk 1 above)
Comment (tristaZero) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/impl/MySQLDDLVisitor.java:169]: Have you ever gave it a try? Since the following `null != ctx.createDefinitionClause()` uses the same method. Is there any difference?

**Review by tristaZero — CHANGES_REQUESTED** [review]

File: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/impl/MySQLDDLVisitor.java (hunk 1 above)
Comment (xbkaishui) [reply shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/impl/MySQLDDLVisitor.java:169]: Yes, I tested and debug it in my local env.

**Comment by xbkaishui** [comment]
I think the difference is notExistClause_ is not marked as optional
 
   : CREATE TEMPORARY? TABLE notExistClause_ tableName (createDefinitionClause? tableOptions_? partitionClause? duplicateAsQueryExpression? | createLikeClause)

**Comment by tristaZero** [comment]
@jingshanglu Please give a look at the definition of `createTable`. `notExistClause_` is optional, right? 
> createTable
    : CREATE TEMPORARY? TABLE notExistClause_ tableName (createDefinitionClause? tableOptions_? partitionClause? duplicateAsQueryExpression? | createLikeClause)
    ;


> I think the difference is notExistClause_ is not marked as optional
> 
> : CREATE TEMPORARY? TABLE notExistClause_ tableName (createDefinitionClause? tableOptions_? partitionClause? duplicateAsQueryExpression? | createLikeClause)

**Comment by tristaZero** [comment]
@xbkaishui Hi There are a bit improper definitions for `notExistClause_` and `existClause_` (below `notExistClause_`). Could you improve this point？
The concrete action is to move `?` from `notExistClause_` and `existClause_` to the position where they are used. Plus, to remove the redundant `()` from them is required.

> createTable
    : CREATE TEMPORARY? TABLE notExistClause_ tableName (createDefinitionClause? tableOptions_? partitionClause? duplicateAsQueryExpression? | createLikeClause)
    ;

**Comment by xbkaishui** [comment]
@tristaZero  finished refactor  notExistClause_ and existClause_

**Review by tristaZero — APPROVED** [review]
I appreciate your speedy improvement!
