### PR TITLE
[ISSUE #21668] Fix nullPointer when encrypt value is null

### LINKED ISSUE #21668: encrypt  insert field cannot be null!
image
in this method ,field value cannot be null or throw NullPointException,but null value could be handle in EncryptAlgorithm!

### PR DESCRIPTION
**Pull request by zzzwjZhang**
Fixes #21668.

Changes proposed in this pull request:
  - Fix NullPointerException when insert encrypt value is null

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `mvn clean install -B -T2C -DskipTests -Dmaven.javadoc.skip=true -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

File: features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java [hunk 1]
```diff
@@ -84,7 +84,7 @@ private void encryptInsertValues(final GroupedParameterBuilder parameterBuilder,
                 ExpressionSegment expressionSegment = insertStatementContext.getInsertValueContexts().get(count).getValueExpressions().get(columnIndex);
                 if (expressionSegment instanceof ParameterMarkerExpressionSegment) {
                     Object literalValue = insertStatementContext.getInsertValueContexts().get(count).getLiteralValue(columnIndex)
-                            .orElseThrow(() -> new UnsupportedEncryptInsertValueException(columnIndex));
```
Comment (strongduanmu) [inline features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java:87]: Can you add some integration test case for this logic?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

**Review by strongduanmu — APPROVED** [review]
@zzzwjZhang Good job, merged.
