### PR TITLE
Fix InsertValueContext.getValue cast exception

### LINKED ISSUE #15334: Enum type function not supported by PostgreSQL
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

version：master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

```sql
CREATE TYPE season AS ENUM ('spring', 'summer', 'autumn', 'winter');

CREATE TABLE t_order (
	order_id BIGINT NOT NULL,
	type_enum season DEFAULT NULL
PRIMARY KEY ( order_id )); 
```

```sql
INSERT INTO t_order (order_id, type_enum) VALUES (?, CAST( ? AS season ));
```

Expected execution succeed 

### Actual behavior

ClassCastException
```java
java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.FunctionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.simple.LiteralExpressionSegment
```

image

proxy

image

### Example codes for reproduce this issue (such as a github link).

JDBC performs operations insert operations can be reproduced

```java

private static void executeUpdate(final Connection connection) throws Exception {
        List<SQLValue> values = createValues(26);
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            for (SQLValue each : values) {
                preparedStatement.setObject(each.getIndex(), each.getValue());
            }
            int rows = preparedStatement.executeUpdate();
        }
    }
```

### PR DESCRIPTION
**Pull request by tuichenchuxin**
Fixes #15334.

Changes proposed in this pull request:
- Fix InsertValueContext.getValue cast exception

### CODE REVIEW

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java [hunk 1]
```diff
@@ -82,7 +83,8 @@ private void encryptInsertValues(final GroupedParameterBuilder parameterBuilder,
                 ExpressionSegment expressionSegment = insertStatementContext.getInsertValueContexts().get(count).getValueExpressions().get(columnIndex);
                 if (expressionSegment instanceof ParameterMarkerExpressionSegment) {
                     encryptInsertValue(
-                            encryptAlgorithm, parameterIndex, insertStatementContext.getInsertValueContexts().get(count).getValue(columnIndex),
+                            encryptAlgorithm, parameterIndex, insertStatementContext.getInsertValueContexts().get(count).getValue(columnIndex)
```
Comment (strongduanmu) [inline shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java:86]: @tuichenchuxin Why throw exception here?

**Review by strongduanmu — CHANGES_REQUESTED** [review]

File: shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java (hunk 1 above)
Comment (tuichenchuxin) [reply shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java:86]: @strongduanmu Because It's for function encrypt，can not support yet.

**Review by strongduanmu — APPROVED** [review]
