### PR TITLE
Fix 6239

### LINKED ISSUE #6239: Make the version of ShardingProxy and DB cluster consistent
**usage:** sqoop-1.4.6-cdh5.16.2 +sharding-proxy-4.1.1 + mysql 5.6

**====
sqoop script：**
sqoop import \
--hive-drop-import-delims \
--connect "jdbc:mysql://xxx:3307/sharding_db?useSSL=false" \
--username root \
--password 'root' \
--split-by id \
--boundary-query "select min(id),max(id) from answer_report" \
--hive-import \
--hive-table tmp.test_sharding_proxy \
--query "select id,table_index,report_id,paper_id,paper_title from answer_report where "'$CONDITIONS' \
--fields-terminated-by '\001' \
--target-dir /tmp/sqoop_test_sharding_proxy_`date +%s` \
--hive-partition-key day \
--hive-partition-value ${bizdate}

**===
sqoop error info:**

ERROR manager.SqlManager: Error executing statement: java.sql.SQLException: Unknown system variable 'transaction_isolation'
java.sql.SQLException: Unknown system variable 'transaction_isolation'
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
......

**===
sharding-proxy log:**

[INFO ] 17:46:19.896 [ShardingSphere-Command-4] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, **@@transaction_isolation** AS transaction_isolation, @@wait_timeout AS wait_timeout

**=====
error analysis**
sharding-proxy are trying to find the variable ‘’transaction_isolation‘’，but mysql 5.6 don't have the variable 'transaction_isolation'  instead of 'tx_isolation'。

**then I test another version ：sharding-proxy-4.0.1。**

**====
sqoop error info：**
20/07/02 18:28:13 ERROR manager.SqlManager: Error executing statement: java.sql.SQLException: 2Unknown exception: [Failed to switch schema, please terminate current transaction.]
java.sql.SQLException: 2Unknown exception: [Failed to switch schema, please terminate current transaction.]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)

**===sharding-proxy info：**
[INFO ] 18:28:12.417 [ShardingSphere-Command-6] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, **@@tx_isolation** AS transaction_isolation, @@wait_timeout AS wait_timeout
......
[ERROR] 18:28:13.467 [ShardingSphere-Command-2] o.a.s.s.f.c.CommandExecutorTask - Exception occur:
org.apache.shardingsphere.core.exception.ShardingException: Failed to switch schema, please terminate current transaction.
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.setCurrentSchema(BackendConnection.java:116)
        at org.apache.shardingsphere.shardingproxy.backend.text.admin.BroadcastBackendHandler.execute(BroadcastBackendHandler.java:53)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:92)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

===
the sharding-proxy-4.0.1  correctly identified parameter ‘tx_isolation’, but have the error  [Failed to switch schema, please terminate current transaction.] ;
the sharding-proxy-4.0.1  did not recognize parameter  ‘tx_isolation’,

### PR DESCRIPTION
**Pull request by xbkaishui**
For #6239 

Changes proposed in this pull request:
- make the version of sharding-proxy and db cluster consistent, update server info version when proxy startup

### CODE REVIEW

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java [hunk 1]
```diff
@@ -31,13 +31,33 @@
...
+    
     /**
      * Server version.
      */
-    public static final String SERVER_VERSION = "8.0.20-ShardingSphere-Proxy 5.0.0-RC1";
+    private static String serverVersion = DEFAULT_SERVER_VERSION;
     
     /**
-     * Charset code 0x21 is utf8_general_ci.
+     *  set server version.
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:47]: set should be capitalized.

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java [hunk 2]
```diff
@@ -31,13 +31,33 @@
...
+     * @param version version
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:48]: server version

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java [hunk 3]
```diff
@@ -31,13 +31,33 @@
...
      */
-    public static final int CHARSET = 0x21;
+    public static void setServerVersion(final String version) {
+        if (version != null) {
+            serverVersion = String.format("%s-ShardingSphere-Proxy 5.0.0-RC1", version);
+        }
+    }
+    
+    /**
+     * get current server version.
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:57]: get should be capitalized.

Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:57]: follow an empty line.

File: shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/resources/bin/start.sh [hunk 4]
```diff
@@ -38,6 +38,17 @@ JAVA_MEM_OPTS=" -server -Xmx2g -Xms2g -Xmn1g -Xss256k -XX:+DisableExplicitGC -XX
 
 MAIN_CLASS=org.apache.shardingsphere.proxy.Bootstrap
 
+print_usage() {
```
Comment (tuohai666) [inline shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/resources/bin/start.sh:41]: What's this for?  I suggest delete it from this pr. If you would like to add help, please create a new issue to do this.

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java [hunk 5]
```diff
@@ -157,6 +162,26 @@ private static void initialize(final Authentication authentication, final Proper
...
+        try (Connection connection = singleDataSource.getConnection()) {
+            DatabaseMetaData meta = connection.getMetaData();
+            String name = meta.getDatabaseProductName();
+            String version = meta.getDatabaseProductVersion();
+            log.info("server name {} , server version {}", name, version);
+            MySQLServerInfo.setServerVersion(version);
+        } catch (SQLException e) {
+            log.error(e.getMessage(), e);
+        }
+
```
Comment (tuohai666) [inline shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:184]: remove meaningless empty line.

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java [hunk 6]
```diff
@@ -157,6 +162,26 @@ private static void initialize(final Authentication authentication, final Proper
...
+    
+    private static void updateServerInfo() {
+        List<String> schemaNames = ProxySchemaContexts.getInstance().getSchemaNames();
+        if (CollectionUtils.isEmpty(schemaNames)) {
+            return;
+        }
+        Map<String, DataSource> dataSources = ProxySchemaContexts.getInstance().getSchema(schemaNames.get(0)).getSchema().getDataSources();
+        DataSource singleDataSource = dataSources.values().iterator().next();
+        try (Connection connection = singleDataSource.getConnection()) {
+            DatabaseMetaData meta = connection.getMetaData();
```
Comment (tuohai666) [inline shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:176]: meta -> databaseMetaData, note that we rarely use abbreviation.

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java [hunk 7]
```diff
@@ -157,6 +162,26 @@ private static void initialize(final Authentication authentication, final Proper
...
+            String name = meta.getDatabaseProductName();
+            String version = meta.getDatabaseProductVersion();
+            log.info("server name {} , server version {}", name, version);
+            MySQLServerInfo.setServerVersion(version);
+        } catch (SQLException e) {
+            log.error(e.getMessage(), e);
```
Comment (tuohai666) [inline shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:182]: throw a ShardingSphereException instead of print log.

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java [hunk 8]
```diff
@@ -157,6 +162,26 @@ private static void initialize(final Authentication authentication, final Proper
...
+        }
+        Map<String, DataSource> dataSources = ProxySchemaContexts.getInstance().getSchema(schemaNames.get(0)).getSchema().getDataSources();
+        DataSource singleDataSource = dataSources.values().iterator().next();
+        try (Connection connection = singleDataSource.getConnection()) {
+            DatabaseMetaData meta = connection.getMetaData();
+            String name = meta.getDatabaseProductName();
+            String version = meta.getDatabaseProductVersion();
+            log.info("server name {} , server version {}", name, version);
+            MySQLServerInfo.setServerVersion(version);
+        } catch (SQLException e) {
```
Comment (tuohai666) [inline shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:181]: SQLException e -> final SQLException ex

File: shardingsphere-proxy/shardingsphere-proxy-common/src/main/java/org/apache/shardingsphere/proxy/config/ShardingConfigurationLoader.java [hunk 9]
```diff
@@ -52,9 +53,10 @@
      * @throws IOException IO exception
      */
     public ShardingConfiguration load(final String path) throws IOException {
+        //this is just check for schemaName duplication
```
Comment (tuohai666) [inline shardingsphere-proxy/shardingsphere-proxy-common/src/main/java/org/apache/shardingsphere/proxy/config/ShardingConfigurationLoader.java:56]: remove this change if it's not about the server version.

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java [hunk 10]
```diff
@@ -31,13 +31,33 @@
      */
     public static final int PROTOCOL_VERSION = 0x0A;
     
+    /**
+     * Charset code 0x21 is utf8_general_ci.
+     */
+    public static final int CHARSET = 0x21;
+    
+    private static final String DEFAULT_SERVER_VERSION = "8.0.20-ShardingSphere-Proxy 5.0.0-RC1";
```
[the remark this answers is not in the document]
Comment (xbkaishui) [reply shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:39]: ok

File: shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/resources/bin/start.sh (hunk 4 above)
Comment (xbkaishui) [reply shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/resources/bin/start.sh:41]: got it

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java [hunk 11]
```diff
@@ -31,13 +31,33 @@
...
      * Server version.
      */
-    public static final String SERVER_VERSION = "8.0.20-ShardingSphere-Proxy 5.0.0-RC1";
+    private static String serverVersion = "8.0.20-ShardingSphere-Proxy 5.0.0-RC1";
     
     /**
-     * Charset code 0x21 is utf8_general_ci.
+     * Set server version.
+     *
+     * @param version server version
```
Comment (tuohai666) [inline shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:47]: version server version -> server version

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java [hunk 12]
```diff
@@ -77,6 +81,7 @@
 /**
  * ShardingSphere-Proxy Bootstrap.
  */
+@Slf4j
```
Comment (tuohai666) [inline shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:84]: move @Slf4j after constructor

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java [hunk 13]
```diff
@@ -157,6 +162,25 @@ private static void initialize(final Authentication authentication, final Proper
...
+        if (CollectionUtils.isEmpty(schemaNames)) {
+            return;
+        }
+        Map<String, DataSource> dataSources = ProxySchemaContexts.getInstance().getSchema(schemaNames.get(0)).getSchema().getDataSources();
+        DataSource singleDataSource = dataSources.values().iterator().next();
+        try (Connection connection = singleDataSource.getConnection()) {
+            DatabaseMetaData databaseMetaData = connection.getMetaData();
+            String name = databaseMetaData.getDatabaseProductName();
+            String version = databaseMetaData.getDatabaseProductVersion();
+            log.info("server name {} , server version {}", name, version);
```
Comment (tuohai666) [inline shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:179]: Database name/Database version is better.

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java [hunk 14]
```diff
@@ -157,6 +162,25 @@ private static void initialize(final Authentication authentication, final Proper
...
+            MySQLServerInfo.setServerVersion(version);
+        } catch (final SQLException e) {
```
Comment (tuohai666) [inline shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:181]: e -> ex

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java (hunk 11 above)
Comment (xbkaishui) [reply shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java:47]: the checkstyle will fail if changes to server version 
` 'server' 的无用标签 @param 。 (47:8) [JavadocMethodCheck]`

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java (hunk 13 above)
Comment (xbkaishui) [reply shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java:179]: yes that's better

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java (hunk 14 above)
Comment (xbkaishui) [reply shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java]: done

File: shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java (hunk 13 above)
Comment (xbkaishui) [reply shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java]: done

File: shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java (hunk 11 above)
Comment (xbkaishui) [reply shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java]: done
