### PR TITLE
fix issue#9976

### LINKED ISSUE #9976: Proxy with empty configuration "show sharding rule" return empty set after "create sharding rule" when governance enabled
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT, commit: c7ea296

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Show sharding rule

### Actual behavior
```
mysql> show sharding rule;
Empty set
```

### Reason analyze (If you can)
`create sharding rule` persist `autoTables` only, `show sharding rule` inspect `tables`

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1, Enable governance in server.yaml
2, Clean configuration, include config-sharding.yaml and remote configuration in ZooKeeper governance_ds
3, Client connect to proxy, run commands:
```
CREATE DATABASE sharding_db;
USE sharding_db;
ADD RESOURCE (ds0 = localhost:3306:jepsen_ds_0:root:test);
ADD RESOURCE (ds1 = localhost:3306:jepsen_ds_1:root:test);

CREATE SHARDING RULE (
t_order resource(ds0, ds1) order_id MOD("sharding-count"=2) generated_key order_id snowflake("worker-id"=123)
);

CREATE TABLE `t_order` (
  `order_id` int NOT NULL,
  `user_id` int NOT NULL,
  `status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SHOW SHARDING RULE;
```

### PR DESCRIPTION
**Pull request by jingshanglu**
Fixes #9976 .

Changes proposed in this pull request:
- fix #9976 
- optimize error messages

### CODE REVIEW

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/main/java/org/apache/shardingsphere/sharding/rule/BindingTableRule.java [hunk 1]
```diff
@@ -80,7 +80,12 @@ public String getBindingActualTable(final String dataSource, final String logicT
         throw new ShardingSphereConfigurationException("Cannot find binding actual table, data source: %s, logic table: %s, other actual table: %s", dataSource, logicTable, otherActualTable);
     }
     
-    Collection<String> getAllLogicTables() {
+    /**
+     * Get list of logical table.
+     *
+     * @return logical tables.
+     */
```
Comment (tristaZero) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/main/java/org/apache/shardingsphere/sharding/rule/BindingTableRule.java:87]: If this function is just for this PR, maybe we can remove it?

**Review by tristaZero — CHANGES_REQUESTED** [review]

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/main/java/org/apache/shardingsphere/sharding/rule/BindingTableRule.java (hunk 1 above)
Comment (jingshanglu) [reply shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/main/java/org/apache/shardingsphere/sharding/rule/BindingTableRule.java:87]: @tristaZero 

There are three citations.

**Review by tristaZero — APPROVED** [review]
