### PR TITLE
Fix `SHOW SHARDING TABLE RULES USED ALGORITHM` not display tables used default strategy.

### LINKED ISSUE #18099: SHOW SHARDING TABLE RULES USED ALGORITHM not display tables used default strategy
### Which version of ShardingSphere did you use?
5.1.2-SNAPSHOT built from master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingProxy

### Expected behavior
SHOW SHARDING TABLE RULES USED ALGORITHM sharding_mod;

got:
table |  test_table

### Actual behavior
got:
Empty set

### Example codes for reproduce this issue (such as a github link).
yaml:
```
schemaName: yao
dataSources:
  ds_0:
    xxx
  ds_1:
    xxx
rules:
- !SHARDING
  tables:
    test_table:
      actualDataNodes: ds_${0..19}.test_table
      # databaseStrategy:
      #   standard:
      #     shardingAlgorithmName: sharding_mod
      #     shardingColumn: id
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    standard:
      shardingAlgorithmName: sharding_mod
      shardingColumn: id

  keyGenerators:
    snowflake:
      props:
        max-vibration-offset: 1
        worker-id: 0
      type: SNOWFLAKE

  shardingAlgorithms:
    sharding_mod:
      props:
        algorithm-expression: ds_${id % 2}
      type: INLINE
```

### PR DESCRIPTION
**Pull request by yx9o**
Fixes #18099 .

### CODE REVIEW

File: shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShardingTableRulesUsedAlgorithmQueryResultSet.java [hunk 1]
```diff
@@ -49,14 +49,20 @@ private void requireResult(final ShowShardingTableRulesUsedAlgorithmStatement st
...
+        boolean matchDefaultTableShardingStrategy = null != shardingRuleConfig.getDefaultTableShardingStrategy()
+                && algorithmName.equals(shardingRuleConfig.getDefaultTableShardingStrategy().getShardingAlgorithmName());
         shardingRuleConfig.getTables().forEach(each -> {
-            if (((null != each.getDatabaseShardingStrategy() && statement.getAlgorithmName().get().equals(each.getDatabaseShardingStrategy().getShardingAlgorithmName())))
-                    || (null != each.getTableShardingStrategy() && statement.getAlgorithmName().get().equals(each.getTableShardingStrategy().getShardingAlgorithmName()))) {
+            if (((null != each.getDatabaseShardingStrategy() && algorithmName.equals(each.getDatabaseShardingStrategy().getShardingAlgorithmName())))
+                    || (null != each.getTableShardingStrategy() && algorithmName.equals(each.getTableShardingStrategy().getShardingAlgorithmName()))
+                    || (null == each.getDatabaseShardingStrategy() && null == each.getTableShardingStrategy() && (matchDefaultDatabaseShardingStrategy || matchDefaultTableShardingStrategy))) {
```
Comment (RaigorJiang) [inline shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShardingTableRulesUsedAlgorithmQueryResultSet.java:60]: `databaseShardingStrategy` and `tableShardingStrategy` are not necessarily null at the same time.

**Comment by TeslaCN** [comment]
Hi @RaigorJiang @yx9o 
Any update here?

**Comment by RaigorJiang** [comment]
> Hi @RaigorJiang @yx9o Any update here?

@yx9o will update soon.

**Review by RaigorJiang — APPROVED** [review]
