### PR TITLE
Fix the separator problem under window.

### LINKED ISSUE #12157: windows test error when load yaml.
since #12155 merged.

In the windows environment, there is an error, but it is normal in other environments, I will solve it as soon as possible.

```
Error:  assertAppend(org.apache.shardingsphere.mode.persist.service.impl.DataSourcePersistServiceTest)  Time elapsed: 0.002 s  <<< FAILURE!
org.mockito.exceptions.verification.junit.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
repository.persist(
    "/metadata/foo_db/dataSources",
    "foo_ds:
  driverClassName: com.mysql.jdbc.Driver
  password: root
  dataSourceClassName: org.apache.shardingsphere.test.mock.MockedDataSource
  connectionInitSqls:
  - set names utf8mb4;
  - set names utf8;
  url: jdbc:mysql://localhost:3306/foo_ds
  username: root
"
);
-> at org.apache.shardingsphere.mode.persist.service.impl.DataSourcePersistServiceTest.assertAppend(DataSourcePersistServiceTest.java:87)
Actual invocation has different arguments:
repository.persist(
    "/metadata/foo_db/dataSources",
    "foo_ds:
  driverClassName: com.mysql.jdbc.Driver
  password: root
  dataSourceClassName: org.apache.shardingsphere.test.mock.MockedDataSource
  connectionInitSqls:
  - set names utf8mb4;
  - set names utf8;
  url: jdbc:mysql://localhost:3306/foo_ds
  username: root
"
);
-> at org.apache.shardingsphere.mode.persist.service.impl.DataSourcePersistService.persist(DataSourcePersistService.java:52)

	at org.apache.shardingsphere.mode.persist.service.impl.DataSourcePersistServiceTest.assertAppend(DataSourcePersistServiceTest.java:87)

[INFO] Running org.apache.shardingsphere.mode.persist.service.impl.PropertiesPersistServiceTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.shardingsphere.mode.persist.service.impl.PropertiesPersistServiceTest
[INFO] Running org.apache.shardingsphere.mode.persist.service.impl.SchemaRulePersistServiceTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.shardingsphere.mode.persist.service.impl.SchemaRulePersistServiceTest
[INFO] Running org.apache.shardingsphere.mode.persist.service.SchemaMetaDataPersistServiceTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 s - in org.apache.shardingsphere.mode.persist.service.SchemaMetaDataPersistServiceTest
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    DataSourcePersistServiceTest.assertAppend:87 
Argument(s) are different! Wanted:
repository.persist(
    "/metadata/foo_db/dataSources",
    "foo_ds:
  driverClassName: com.mysql.jdbc.Driver
  password: root
  dataSourceClassName: org.apache.shardingsphere.test.mock.MockedDataSource
  connectionInitSqls:
  - set names utf8mb4;
  - set names utf8;
  url: jdbc:mysql://localhost:3306/foo_ds
  username: root
"
);
-> at org.apache.shardingsphere.mode.persist.service.impl.DataSourcePersistServiceTest.assertAppend(DataSourcePersistServiceTest.java:87)
Actual invocation has different arguments:
repository.persist(
    "/metadata/foo_db/dataSources",
    "foo_ds:
  driverClassName: com.mysql.jdbc.Driver
  password: root
  dataSourceClassName: org.apache.shardingsphere.test.mock.MockedDataSource
  connectionInitSqls:
  - set names utf8mb4;
  - set names utf8;
  url: jdbc:mysql://localhost:3306/foo_ds
  username: root
"
);
-> at org.apache.shardingsphere.mode.persist.service.impl.DataSourcePersistService.persist(DataSourcePersistService.java:52)

```

### PR DESCRIPTION
**Pull request by totalo**
Fixes #12157.

Changes proposed in this pull request:
- Fix the separator problem under window.

### CODE REVIEW

**Review by terrymanu — COMMENTED** [review]
What is the result with `System.lineSeparator()` in windows?

**Comment by totalo** [comment]
> What is the result with `System.lineSeparator()` in windows?

Below win is /r/n.

File: shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/persist/service/impl/DataSourcePersistServiceTest.java [hunk 1]
```diff
@@ -61,7 +61,7 @@ public void assertLoad() {
     @SneakyThrows({IOException.class, URISyntaxException.class})
     private String readDataSourceYaml(final String path) {
         return Files.readAllLines(Paths.get(ClassLoader.getSystemResource(path).toURI()))
-                .stream().filter(each -> StringUtils.isNotBlank(each) && !each.startsWith("#")).map(each -> each + System.lineSeparator()).collect(Collectors.joining());
+                .stream().filter(each -> StringUtils.isNotBlank(each) && !each.startsWith("#")).map(each -> each + "\n").collect(Collectors.joining());
```
Comment (SteNicholas) [inline shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/persist/service/impl/DataSourcePersistServiceTest.java:64]: It shouldn't be fixed here. `System.lineSeparator()` does return the line separator, it will return the corresponding line separator according to the current computer system. Or you could try to use the `System.getProperty("line.separator")`.

**Review by SteNicholas — CHANGES_REQUESTED** [review]

**Comment by terrymanu** [comment]
> > What is the result with `System.lineSeparator()` in windows?
> 
> Below win is \r\n.

Why `\r\n` cause error?

**Comment by totalo** [comment]
> > > What is the result with `System.lineSeparator()` in windows?
> > 
> > 
> > Below win is \r\n.
> 
> Why `\r\n` cause error?



> > > What is the result with `System.lineSeparator()` in windows?
> > 
> > 
> > Below win is \r\n.
> 
> Why `\r\n` cause error?

It is because `YamlEngine.marshal(swapYamlDataSourceConfiguration(dataSourceConfigs))` returns are divided by `\n`, but our parameters are divided by` \r\n`. So the parameters are not equal.I am looking for why it will be divided by `\n ` in the windows environment.

**Comment by totalo** [comment]
> > > > What is the result with `System.lineSeparator()` in windows?
> > > 
> > > 
> > > Below win is \r\n.
> > 
> > 
> > Why `\r\n` cause error?
> 
> > > > What is the result with `System.lineSeparator()` in windows?
> > > 
> > > 
> > > Below win is \r\n.
> > 
> > 
> > Why `\r\n` cause error?
> 
> It is because `YamlEngine.marshal(swapYamlDataSourceConfiguration(dataSourceConfigs))` returns are divided by `\n`, but our parameters are divided by` \r\n`. So the parameters are not equal.I am looking for why it will be divided by `\n ` in the windows environment.

I found that when yaml conversion, the default Unix delimiter is used, and we need to automatically obtain the system delimiter when converting.


image

**Review by terrymanu — APPROVED** [review]
